// Generated by zinfer - Do not edit manually

export type FooInput = {
  id: string;
};

export type FooOutput = {
  value: import("../../fixtures/unique-symbol-cross-file-transform/types").Named;
};
