// Generated by zinfer - Do not edit manually

export type CycleInput = {
  value: string;
  next?: import("../../../fixtures/inline-external-types/cycle/node-b").NodeB;
};

export type CycleOutput = {
  value: string;
  next?: import("../../../fixtures/inline-external-types/cycle/node-b").NodeB;
};
