// Generated by zinfer - Do not edit manually

export type ChainInput = {
  label: string;
  nested: {
    name: string;
    deep: ("x" | "y" | "z");
    format: (((value: string) => string) | null);
  };
};

export type ChainOutput = {
  label: string;
  nested: {
    name: string;
    deep: ("x" | "y" | "z");
    format: (((value: string) => string) | null);
  };
};
