// Generated by zinfer - Do not edit manually

export type MethodCollisionInput = {
  holder: {
    Box(): string;
    value: {
      value: string;
    };
  };
};

export type MethodCollisionOutput = {
  holder: {
    Box(): string;
    value: {
      value: string;
    };
  };
};
