// Generated by zinfer - Do not edit manually

export type MethodCollisionInput = {
  holder: import("../../../fixtures/inline-external-types/method-collision/holder").Holder;
};

export type MethodCollisionOutput = {
  holder: import("../../../fixtures/inline-external-types/method-collision/holder").Holder;
};
