// Generated by vinfer - Do not edit manually

export type QuuxInput = import("../../fixtures/degenerate-explicit-type/aliased-export-explicit-type-schema").RenamedClass;

export type QuuxOutput = import("../../fixtures/degenerate-explicit-type/aliased-export-explicit-type-schema").RenamedClass;
