// Generated by vinfer - Do not edit manually

export type FooInput = import("../../fixtures/degenerate-explicit-type/class-explicit-type-schema").LocalClass;

export type FooOutput = import("../../fixtures/degenerate-explicit-type/class-explicit-type-schema").LocalClass;
