// Generated by vinfer - Do not edit manually

export type BarInput = import("../../fixtures/degenerate-explicit-type/interface-explicit-type-schema").LocalInterface;

export type BarOutput = import("../../fixtures/degenerate-explicit-type/interface-explicit-type-schema").LocalInterface;
