// Generated by zinfer - Do not edit manually

export type ChainInput = {
  label: string;
  nested: import("../../../fixtures/inline-external-types/chain/level2").Level2;
};

export type ChainOutput = {
  label: string;
  nested: import("../../../fixtures/inline-external-types/chain/level2").Level2;
};
