// Generated by zinfer - Do not edit manually

export type GenericMethodCollisionInput = {
  holder: import("../../../fixtures/inline-external-types/generic-method-collision/holder").Holder;
};

export type GenericMethodCollisionOutput = {
  holder: import("../../../fixtures/inline-external-types/generic-method-collision/holder").Holder;
};
