// Generated by zinfer - Do not edit manually

export type GenericMethodCollisionInput = {
  holder: {
    Box<T>(): T;
    value: {
      value: string;
    };
  };
};

export type GenericMethodCollisionOutput = {
  holder: {
    Box<T>(): T;
    value: {
      value: string;
    };
  };
};
