import { describe, it, expect } from "vitest";
import {
  formatResult,
  formatInputOnly,
  formatOutputOnly,
  formatAsDeclaration,
  generateDeclarationFile,
} from "../src/core/type-printer.js";
import { createNameMapper } from "../src/core/name-mapper.js";
import type { ExtractResult } from "../src/core/types.js";

const mapName = createNameMapper({ removeSuffix: "Schema" });

function result(overrides: Partial<ExtractResult> = {}): ExtractResult {
  return {
    schemaName: "UserSchema",
    input: "{ id: string; name: string; }",
    output: "{ id: string; name: string; }",
    isExported: true,
    ...overrides,
  };
}

describe("formatResult", () => {
  it("prints the input and output sections", () => {
    expect(formatResult(result())).toBe(
      [
        "// input",
        "{",
        "  id: string;",
        "  name: string;",
        "}",
        "",
        "// output",
        "{",
        "  id: string;",
        "  name: string;",
        "}",
      ].join("\n"),
    );
  });

  it("can include the schema name", () => {
    expect(formatResult(result(), { includeSchemaName: true })).toContain("// Schema: UserSchema");
  });

  it("leaves non-object types on one line", () => {
    expect(formatInputOnly(result({ input: '"a" | "b"' }))).toBe('"a" | "b"');
    expect(formatOutputOnly(result({ output: "string" }))).toBe("string");
  });

  it("honors a custom indent", () => {
    expect(formatInputOnly(result(), { indent: "    " })).toContain("    id: string;");
  });
});

describe("formatAsDeclaration", () => {
  it("emits both input and output types", () => {
    const output = formatAsDeclaration(result(), mapName("UserSchema"));
    expect(output).toContain("export type UserInput = {");
    expect(output).toContain("export type UserOutput = {");
  });

  it("omits the export keyword for non-exported schemas", () => {
    const output = formatAsDeclaration(result({ isExported: false }), mapName("UserSchema"));
    expect(output).not.toContain("export ");
    expect(output).toContain("type UserInput = {");
  });

  it("emits only the requested direction", () => {
    const names = mapName("UserSchema");
    expect(formatAsDeclaration(result(), names, { inputOnly: true })).not.toContain("UserOutput");
    expect(formatAsDeclaration(result(), names, { outputOnly: true })).not.toContain("UserInput");
  });

  it("merges identical types and aliases the directional names", () => {
    const output = formatAsDeclaration(result(), mapName("UserSchema"), { mergeSame: true });
    expect(output).toContain("export type User = {");
    expect(output).toContain("export type UserInput = User;");
    expect(output).toContain("export type UserOutput = User;");
  });

  it("does not merge when input and output differ", () => {
    const output = formatAsDeclaration(
      result({ output: "{ id: string; name: number; }" }),
      mapName("UserSchema"),
      { mergeSame: true },
    );
    expect(output).toContain("export type UserInput = {");
    expect(output).toContain("export type UserOutput = {");
  });

  it("renders the schema description as a TSDoc block", () => {
    const output = formatAsDeclaration(
      result({ description: "A user\nand its fields" }),
      mapName("UserSchema"),
    );
    expect(output).toContain("/**\n * A user\n * and its fields\n */\nexport type UserInput");
  });

  it("renders field descriptions as TSDoc comments", () => {
    const output = formatAsDeclaration(
      result({ fieldDescriptions: [{ path: "id", description: "The id" }] }),
      mapName("UserSchema"),
    );
    expect(output).toContain("  /** The id */\n  id: string;");
  });

  it("renders a multiline field description as a block comment", () => {
    const output = formatAsDeclaration(
      result({ fieldDescriptions: [{ path: "id", description: "The id\nis unique" }] }),
      mapName("UserSchema"),
    );
    expect(output).toContain("  /**\n   * The id\n   * is unique\n   */\n  id: string;");
  });

  it("scopes nested field descriptions by path", () => {
    const output = formatAsDeclaration(
      result({
        input: "{ meta: { id: string; }; id: string; }",
        output: "{ meta: { id: string; }; id: string; }",
        fieldDescriptions: [
          { path: "meta.id", description: "Nested id" },
          { path: "id", description: "Top-level id" },
        ],
      }),
      mapName("UserSchema"),
    );
    expect(output).toContain("    /** Nested id */\n    id: string;");
    expect(output).toContain("  /** Top-level id */\n  id: string;");
  });
});

describe("generateDeclarationFile", () => {
  it("prefixes the generated-file header", () => {
    expect(generateDeclarationFile([result()], mapName)).toMatch(
      /^\/\/ Generated by vinfer - Do not edit manually\n/,
    );
  });

  it("skips non-exported schemas", () => {
    const output = generateDeclarationFile(
      [result({ schemaName: "InternalSchema", isExported: false }), result()],
      mapName,
    );
    expect(output).not.toContain("Internal");
    expect(output).toContain("UserInput");
  });

  it("imports only the Valibot type helpers that are used", () => {
    expect(
      generateDeclarationFile([result({ output: 'string & Brand<"UserId">' })], mapName),
    ).toContain('import type { Brand } from "valibot";');

    expect(
      generateDeclarationFile([result({ output: 'string & Flavor<"Email">' })], mapName),
    ).toContain('import type { Flavor } from "valibot";');

    expect(
      generateDeclarationFile(
        [result({ output: '{ a: string & Brand<"A">; b: string & Flavor<"B">; }' })],
        mapName,
      ),
    ).toContain('import type { Brand, Flavor } from "valibot";');

    expect(generateDeclarationFile([result()], mapName)).not.toContain("valibot");
  });

  it("rewrites cross-schema references to the mapped type names", () => {
    const output = generateDeclarationFile(
      [
        result({
          schemaName: "AddressSchema",
          input: "{ city: string; }",
          output: "{ city: string; }",
        }),
        result({
          schemaName: "UserSchema",
          input: "{ address: AddressSchemaInput; }",
          output: "{ address: AddressSchemaOutput; }",
        }),
      ],
      mapName,
    );
    expect(output).toContain("address: AddressInput;");
    expect(output).toContain("address: AddressOutput;");
    expect(output).not.toContain("AddressSchemaInput");
  });

  it("merges transitively so a referencing schema can merge too", () => {
    const output = generateDeclarationFile(
      [
        result({
          schemaName: "AddressSchema",
          input: "{ city: string; }",
          output: "{ city: string; }",
        }),
        result({
          schemaName: "UserSchema",
          input: "{ address: AddressSchemaInput; }",
          output: "{ address: AddressSchemaOutput; }",
        }),
      ],
      mapName,
      { mergeSame: true },
    );
    expect(output).toContain("export type Address = {");
    expect(output).toContain("address: Address;");
    expect(output).toContain("export type User = {");
  });

  it("rewrites cross-schema references for a $-prefixed schema name", () => {
    // `\b` treats `$` as a non-word character, so `\b$NodeSchemaInput\b` never
    // matches - the replacement (and the check that the old name is gone) both
    // depend on identifier-aware boundary matching, not `\b`.
    const output = generateDeclarationFile(
      [
        result({
          schemaName: "$NodeSchema",
          input: "{ label: string; }",
          output: "{ label: string; }",
        }),
        result({
          schemaName: "TreeSchema",
          input: "{ root: $NodeSchemaInput; }",
          output: "{ root: $NodeSchemaOutput; }",
        }),
      ],
      mapName,
    );
    expect(output).toContain("root: $NodeInput;");
    expect(output).toContain("root: $NodeOutput;");
    expect(output).not.toContain("$NodeSchemaInput");
  });

  it("merges a $-prefixed schema under mergeSame", () => {
    const output = generateDeclarationFile(
      [
        result({
          schemaName: "$NodeSchema",
          input: "{ label: string; }",
          output: "{ label: string; }",
        }),
        result({
          schemaName: "TreeSchema",
          input: "{ root: $NodeSchemaInput; }",
          output: "{ root: $NodeSchemaOutput; }",
        }),
      ],
      mapName,
      { mergeSame: true },
    );
    expect(output).toContain("export type $Node = {");
    expect(output).toContain("root: $Node;");
  });

  it("does not rewrite an unrelated identifier that merely spells out another schema's Input/Output name inside a typeof operand or a method signature", () => {
    // WeirdSchema's explicit v.GenericSchema<T> annotation prints T verbatim,
    // which can contain arbitrary text - here it happens to spell out
    // "NodeSchemaInput"/"NodeSchemaOutput" both as a `typeof` operand
    // (referencing a real value declared in the user's own file) and as a
    // method name. Neither is a reference to NodeSchema's generated type;
    // identifierPattern's name substitution must not touch them just
    // because the text matches.
    const output = generateDeclarationFile(
      [
        result({
          schemaName: "NodeSchema",
          input: "any",
          output: "any",
        }),
        result({
          schemaName: "WeirdSchema",
          input:
            'typeof import("./types").NodeSchemaInput extends unknown ? { NodeSchemaInput(): string; } : never',
          output:
            'typeof import("./types").NodeSchemaOutput extends unknown ? { NodeSchemaOutput(): string; } : never',
        }),
      ],
      mapName,
    );
    // The generated NodeInput/NodeOutput declarations are unrelated to this -
    // only the corruption inside WeirdInput/WeirdOutput is under test.
    expect(output).toContain(
      'typeof import("./types").NodeSchemaInput extends unknown ? { NodeSchemaInput(): string; } : never',
    );
    expect(output).toContain(
      'typeof import("./types").NodeSchemaOutput extends unknown ? { NodeSchemaOutput(): string; } : never',
    );
  });

  it("does not rewrite a protected identifier across more than one space after `typeof` or before a method's `(`", () => {
    // TypeScript's own printer always normalizes to exactly one space after
    // `typeof` and none before a method's `(`, so this text never actually
    // reaches identifierPattern this way in practice - but the guard should
    // hold regardless of how many whitespace characters separate them,
    // rather than assuming the printer's normalization forever.
    const output = generateDeclarationFile(
      [
        result({ schemaName: "NodeSchema", input: "any", output: "any" }),
        result({
          schemaName: "WeirdSchema",
          input: "{ value: typeof  NodeSchemaInput; NodeSchemaInput  (): string; }",
          output: "{ value: typeof  NodeSchemaOutput; NodeSchemaOutput  (): string; }",
        }),
      ],
      mapName,
    );
    expect(output).toContain("value: typeof  NodeSchemaInput;");
    expect(output).toContain("NodeSchemaInput  (): string;");
    expect(output).toContain("value: typeof  NodeSchemaOutput;");
    expect(output).toContain("NodeSchemaOutput  (): string;");
  });
});

describe("brandStrategy: local-symbol", () => {
  it("rewrites a Brand<Tag> marker to a local symbol-keyed property instead of importing Brand", () => {
    const output = generateDeclarationFile(
      [result({ output: 'string & Brand<"UserId">' })],
      mapName,
      { brandStrategy: "local-symbol" },
    );
    expect(output).toContain("declare const __brand: unique symbol;");
    expect(output).toContain('string & { readonly [__brand]: "UserId" }');
    expect(output).not.toContain("__flavor");
    expect(output).not.toContain("valibot");
  });

  it("rewrites a Flavor<Tag> marker to an optional local symbol-keyed property instead of importing Flavor", () => {
    const output = generateDeclarationFile(
      [result({ output: 'string & Flavor<"Email">' })],
      mapName,
      { brandStrategy: "local-symbol" },
    );
    expect(output).toContain("declare const __flavor: unique symbol;");
    expect(output).toContain('string & { readonly [__flavor]?: "Email" }');
    expect(output).not.toContain("__brand");
    expect(output).not.toContain("valibot");
  });

  it("declares only the local symbols actually used, both when a file has both", () => {
    const output = generateDeclarationFile(
      [
        result({
          output: '{ a: string & Brand<"A">; b: string & Flavor<"B">; }',
        }),
      ],
      mapName,
      { brandStrategy: "local-symbol" },
    );
    expect(output).toContain("declare const __brand: unique symbol;");
    expect(output).toContain("declare const __flavor: unique symbol;");
  });

  it("does not declare a local symbol when no schema has a brand or flavor", () => {
    const output = generateDeclarationFile([result()], mapName, { brandStrategy: "local-symbol" });
    expect(output).not.toContain("__brand");
    expect(output).not.toContain("__flavor");
  });

  it("does not rewrite a plain string literal that merely contains the text Brand<", () => {
    const output = generateDeclarationFile(
      [result({ output: '{ kind: "Brand<Fake>"; }' })],
      mapName,
      { brandStrategy: "local-symbol" },
    );
    expect(output).toContain('kind: "Brand<Fake>";');
    expect(output).not.toContain("__brand");
  });

  it("does not rewrite an identifier that merely ends in ...Brand< (word-boundary check)", () => {
    const output = generateDeclarationFile([result({ output: "FooBrand<string>" })], mapName, {
      brandStrategy: "local-symbol",
    });
    expect(output).toContain("FooBrand<string>");
    expect(output).not.toContain("__brand");
  });

  it("treats $ as an identifier character too, since it's valid in a TypeScript identifier", () => {
    const output = generateDeclarationFile([result({ output: "Foo$Brand<string>" })], mapName, {
      brandStrategy: "local-symbol",
    });
    expect(output).toContain("Foo$Brand<string>");
    expect(output).not.toContain("__brand");
  });

  it("skips a > inside the tag's own string literal when finding the marker's end", () => {
    const output = generateDeclarationFile([result({ output: 'string & Brand<"a>b">' })], mapName, {
      brandStrategy: "local-symbol",
    });
    expect(output).toContain('{ readonly [__brand]: "a>b" }');
  });

  it("leaves Brand/Flavor markers and the valibot import untouched under the default strategy", () => {
    const output = generateDeclarationFile(
      [result({ output: 'string & Brand<"UserId">' })],
      mapName,
    );
    expect(output).toContain('import type { Brand } from "valibot";');
    expect(output).toContain('string & Brand<"UserId">');
    expect(output).not.toContain("__brand");
  });
});
