// Generated by zinfer - Do not edit manually

export type NodeInput = {
  value: string;
  children?: Record<string, NodeInput>;
};

export type NodeOutput = {
  value: string;
  children?: Record<string, NodeOutput>;
};
