// Generated by zinfer - Do not edit manually

export type DirectQualifiedInput = {
  kind: import("../../../fixtures/inline-external-types/qualified/kind").Kind.A;
  box: import("../../../fixtures/inline-external-types/qualified/kind").Box<string>;
};

export type DirectQualifiedOutput = {
  kind: import("../../../fixtures/inline-external-types/qualified/kind").Kind.A;
  box: import("../../../fixtures/inline-external-types/qualified/kind").Box<string>;
};
