// Generated by zinfer - Do not edit manually

export type FooInput = {
  id: string;
  value: import("../../fixtures/composite-explicit-type-cross-file/types").Named;
};

export type FooOutput = {
  id: string;
  value: import("../../fixtures/composite-explicit-type-cross-file/types").Named;
};
