// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- alias-getter-schema ---
import { AliasedCategorySchema as AliasGetterSchemaAliasedCategorySchema } from "../fixtures/alias-getter-schema";
import type { AliasedCategoryInput as AliasGetterSchemaAliasedCategoryInput, AliasedCategoryOutput as AliasGetterSchemaAliasedCategoryOutput } from "./alias-getter-schema";

describe("Type equality tests", () => {
  describe("alias-getter-schema", () => {
    it("AliasedCategorySchema input matches z.input", () => {
      expectTypeOf<AliasGetterSchemaAliasedCategoryInput>().toEqualTypeOf<z.input<typeof AliasGetterSchemaAliasedCategorySchema>>();
    });

    it("AliasedCategorySchema output matches z.output", () => {
      expectTypeOf<AliasGetterSchemaAliasedCategoryOutput>().toEqualTypeOf<z.output<typeof AliasGetterSchemaAliasedCategorySchema>>();
    });
  });
});
