// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- alias-cross-reference-schema ---
import { ContainerSchema as AliasCrossReferenceSchemaContainerSchema, AliasedNode as AliasCrossReferenceSchemaAliasedNode } from "../fixtures/alias-cross-reference-schema";
import type {
  ContainerInput as AliasCrossReferenceSchemaContainerInput,
  ContainerOutput as AliasCrossReferenceSchemaContainerOutput,
  AliasedNodeInput as AliasCrossReferenceSchemaAliasedNodeInput,
  AliasedNodeOutput as AliasCrossReferenceSchemaAliasedNodeOutput,
} from "./alias-cross-reference-schema";

describe("Type equality tests", () => {
  describe("alias-cross-reference-schema", () => {
    it("ContainerSchema input matches z.input", () => {
      expectTypeOf<AliasCrossReferenceSchemaContainerInput>().toEqualTypeOf<z.input<typeof AliasCrossReferenceSchemaContainerSchema>>();
    });

    it("ContainerSchema output matches z.output", () => {
      expectTypeOf<AliasCrossReferenceSchemaContainerOutput>().toEqualTypeOf<z.output<typeof AliasCrossReferenceSchemaContainerSchema>>();
    });

    it("AliasedNode input matches z.input", () => {
      expectTypeOf<AliasCrossReferenceSchemaAliasedNodeInput>().toEqualTypeOf<z.input<typeof AliasCrossReferenceSchemaAliasedNode>>();
    });

    it("AliasedNode output matches z.output", () => {
      expectTypeOf<AliasCrossReferenceSchemaAliasedNodeOutput>().toEqualTypeOf<z.output<typeof AliasCrossReferenceSchemaAliasedNode>>();
    });
  });
});
