// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- annotated-ref-schema ---
import { NodeSchema as AnnotatedRefSchemaNodeSchema, TreeSchema as AnnotatedRefSchemaTreeSchema } from "../fixtures/annotated-ref-schema";
import type {
  NodeInput as AnnotatedRefSchemaNodeInput,
  NodeOutput as AnnotatedRefSchemaNodeOutput,
  TreeInput as AnnotatedRefSchemaTreeInput,
  TreeOutput as AnnotatedRefSchemaTreeOutput,
} from "./annotated-ref-schema";

describe("Type equality tests", () => {
  describe("annotated-ref-schema", () => {
    it("NodeSchema input matches z.input", () => {
      expectTypeOf<AnnotatedRefSchemaNodeInput>().toEqualTypeOf<z.input<typeof AnnotatedRefSchemaNodeSchema>>();
    });

    it("NodeSchema output matches z.output", () => {
      expectTypeOf<AnnotatedRefSchemaNodeOutput>().toEqualTypeOf<z.output<typeof AnnotatedRefSchemaNodeSchema>>();
    });

    it("TreeSchema input matches z.input", () => {
      expectTypeOf<AnnotatedRefSchemaTreeInput>().toEqualTypeOf<z.input<typeof AnnotatedRefSchemaTreeSchema>>();
    });

    it("TreeSchema output matches z.output", () => {
      expectTypeOf<AnnotatedRefSchemaTreeOutput>().toEqualTypeOf<z.output<typeof AnnotatedRefSchemaTreeSchema>>();
    });
  });
});
