// Generated by zinfer - Do not edit manually

export type NodeInput = import("../fixtures/annotated-ref-schema").NodeShape;

export type NodeOutput = import("../fixtures/annotated-ref-schema").NodeShape;

export type TreeInput = {
  root: NodeInput;
  nodes: NodeInput[];
  index: {
    [x: string]: NodeInput;
  };
};

export type TreeOutput = {
  root: NodeOutput;
  nodes: NodeOutput[];
  index: {
    [x: string]: NodeOutput;
  };
};
