// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- array-brand-schema ---
import { TagsSchema as ArrayBrandSchemaTagsSchema } from "../fixtures/array-brand-schema";
import type { TagsInput as ArrayBrandSchemaTagsInput, TagsOutput as ArrayBrandSchemaTagsOutput } from "./array-brand-schema";

describe("Type equality tests", () => {
  describe("array-brand-schema", () => {
    it("TagsSchema input matches z.input", () => {
      expectTypeOf<ArrayBrandSchemaTagsInput>().toEqualTypeOf<z.input<typeof ArrayBrandSchemaTagsSchema>>();
    });

    it("TagsSchema output matches z.output", () => {
      expectTypeOf<ArrayBrandSchemaTagsOutput>().toEqualTypeOf<z.output<typeof ArrayBrandSchemaTagsSchema>>();
    });
  });
});
