// Generated by zinfer - Do not edit manually

export type UserInput = {
  id: string;
  name: string;
  age?: number | undefined; 
};

export type UserOutput = {
  id: string;
  name: string;
  age?: number | undefined; 
};
