// Generated by zinfer - Do not edit manually

/**
 * User account information
 */
export type UserInput = {
  /** Unique user identifier */
  id: string;
  /** User's display name */
  name: string;
  /** User's email address */
  email: string;
  /** User's role in the system */
  role: "admin" | "user" | "guest";
  /** User's age in years */
  age?: number | undefined;
};

export type UserOutput = {
  /** Unique user identifier */
  id: string;
  /** User's display name */
  name: string;
  /** User's email address */
  email: string;
  /** User's role in the system */
  role: "admin" | "user" | "guest";
  /** User's age in years */
  age?: number | undefined;
};

export type AddressInput = {
  /** Street address */
  street: string;
  /** City name */
  city: string;
  /** Country code (ISO 3166-1 alpha-2) */
  country: string;
  /** Postal/ZIP code */
  zipCode?: string | undefined;
};

export type AddressOutput = {
  /** Street address */
  street: string;
  /** City name */
  city: string;
  /** Country code (ISO 3166-1 alpha-2) */
  country: string;
  /** Postal/ZIP code */
  zipCode?: string | undefined;
};

export type ProfileInput = {
  /** User information */
  user: {
    id: string;
    name: string;
    email: string;
    role: "admin" | "user" | "guest";
    age?: number | undefined;
  };
  /** User tags for categorization */
  tags: readonly string[];
  /** User's primary address */
  address?: {
    street: string;
    city: string;
    country: string;
    zipCode?: string | undefined;
  } | undefined;
};

export type ProfileOutput = {
  /** User information */
  user: {
    id: string;
    name: string;
    email: string;
    role: "admin" | "user" | "guest";
    age?: number | undefined;
  };
  /** User tags for categorization */
  tags: readonly string[];
  /** User's primary address */
  address?: {
    street: string;
    city: string;
    country: string;
    zipCode?: string | undefined;
  } | undefined;
};
