// Generated by zinfer - Do not edit manually

export type UserInput = {
  id: string;
  name: string;
  email: string;
  role: "admin" | "user" | "guest";
  age?: number | undefined;
};

export type UserOutput = {
  id: string;
  name: string;
  email: string;
  role: "admin" | "user" | "guest";
  age?: number | undefined;
};

export type AddressInput = {
  street: string;
  city: string;
  country: string;
  zipCode?: string | undefined;
};

export type AddressOutput = {
  street: string;
  city: string;
  country: string;
  zipCode?: string | undefined;
};

export type ProfileInput = {
  user: UserInput;
  tags: string[];
  address?: AddressInput;
};

export type ProfileOutput = {
  user: UserOutput;
  tags: string[];
  address?: AddressOutput;
};
