// Generated by zinfer - Do not edit manually

export type UserInput = {
  id: string;
  name: string;
  email: string;
  role: "admin" | "user" | "guest";
  age?: number | undefined;
};

export type UserOutput = {
  id: string;
  name: string;
  email: string;
  role: "admin" | "user" | "guest";
  age?: number | undefined;
};

export type AddressInput = {
  street: string;
  city: string;
  country: string;
  zipCode?: string | undefined;
};

export type AddressOutput = {
  street: string;
  city: string;
  country: string;
  zipCode?: string | undefined;
};

export type ProfileInput = {
  user: {
    id: string;
    name: string;
    email: string;
    role: "admin" | "user" | "guest";
    age?: number | undefined;
  };
  tags: readonly string[];
  address?: {
    street: string;
    city: string;
    country: string;
    zipCode?: string | undefined;
  } | undefined;
};

export type ProfileOutput = {
  user: {
    id: string;
    name: string;
    email: string;
    role: "admin" | "user" | "guest";
    age?: number | undefined;
  };
  tags: readonly string[];
  address?: {
    street: string;
    city: string;
    country: string;
    zipCode?: string | undefined;
  } | undefined;
};
