// Generated by zinfer - Do not edit manually

/**
 * User account information
 */
export type UserInput = {
  /** Unique user identifier */
  id: string;
  /** User's display name */
  name: string;
  /** User's email address */
  email: string;
  /** User's age in years */
  age?: number | undefined;
  /** User's role in the system */
  role: "admin" | "guest" | "user";
};

export type UserOutput = {
  /** Unique user identifier */
  id: string;
  /** User's display name */
  name: string;
  /** User's email address */
  email: string;
  /** User's age in years */
  age?: number | undefined;
  /** User's role in the system */
  role: "admin" | "guest" | "user";
};

export type AddressInput = {
  /** Street address */
  street: string;
  /** City name */
  city: string;
  /** Country code (ISO 3166-1 alpha-2) */
  country: string;
  /** Postal/ZIP code */
  zipCode?: string | undefined;
};

export type AddressOutput = {
  /** Street address */
  street: string;
  /** City name */
  city: string;
  /** Country code (ISO 3166-1 alpha-2) */
  country: string;
  /** Postal/ZIP code */
  zipCode?: string | undefined;
};

export type ProfileInput = {
  /** User information */
  user: UserInput;
  /** User's primary address */
  address?: AddressInput;
  /** User tags for categorization */
  tags: string[];
};

export type ProfileOutput = {
  /** User information */
  user: UserOutput;
  /** User's primary address */
  address?: AddressOutput;
  /** User tags for categorization */
  tags: string[];
};
