// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- duplicate-field-name-schema ---
import { ValueSchema as DuplicateFieldNameSchemaValueSchema, DuplicateFieldNameSchema as DuplicateFieldNameSchemaDuplicateFieldNameSchema } from "../fixtures/duplicate-field-name-schema";
import type {
  ValueInput as DuplicateFieldNameSchemaValueInput,
  ValueOutput as DuplicateFieldNameSchemaValueOutput,
  DuplicateFieldNameInput as DuplicateFieldNameSchemaDuplicateFieldNameInput,
  DuplicateFieldNameOutput as DuplicateFieldNameSchemaDuplicateFieldNameOutput,
} from "./duplicate-field-name-schema";

describe("Type equality tests", () => {
  describe("duplicate-field-name-schema", () => {
    it("ValueSchema input matches z.input", () => {
      expectTypeOf<DuplicateFieldNameSchemaValueInput>().toEqualTypeOf<z.input<typeof DuplicateFieldNameSchemaValueSchema>>();
    });

    it("ValueSchema output matches z.output", () => {
      expectTypeOf<DuplicateFieldNameSchemaValueOutput>().toEqualTypeOf<z.output<typeof DuplicateFieldNameSchemaValueSchema>>();
    });

    it("DuplicateFieldNameSchema input matches z.input", () => {
      expectTypeOf<DuplicateFieldNameSchemaDuplicateFieldNameInput>().toEqualTypeOf<z.input<typeof DuplicateFieldNameSchemaDuplicateFieldNameSchema>>();
    });

    it("DuplicateFieldNameSchema output matches z.output", () => {
      expectTypeOf<DuplicateFieldNameSchemaDuplicateFieldNameOutput>().toEqualTypeOf<z.output<typeof DuplicateFieldNameSchemaDuplicateFieldNameSchema>>();
    });
  });
});
