// Generated by zinfer - Do not edit manually

export type DirectionInput = "north" | "south" | "east" | "west";

export type DirectionOutput = "north" | "south" | "east" | "west";

export type ColorInput = Color;

export type ColorOutput = Color;

export type PriorityInput = Priority;

export type PriorityOutput = Priority;
