// Generated by zinfer - Do not edit manually

export type DirectionInput = "east" | "north" | "south" | "west";

export type DirectionOutput = "east" | "north" | "south" | "west";

export type ColorInput = "red" | "green" | "blue";

export type ColorOutput = "red" | "green" | "blue";

export type PriorityInput = 0 | 1 | 2;

export type PriorityOutput = 0 | 1 | 2;
