// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- enum-schema ---
import { DirectionSchema as EnumSchemaDirectionSchema, ColorSchema as EnumSchemaColorSchema, PrioritySchema as EnumSchemaPrioritySchema } from "../fixtures/enum-schema";
import type {
  DirectionInput as EnumSchemaDirectionInput,
  DirectionOutput as EnumSchemaDirectionOutput,
  ColorInput as EnumSchemaColorInput,
  ColorOutput as EnumSchemaColorOutput,
  PriorityInput as EnumSchemaPriorityInput,
  PriorityOutput as EnumSchemaPriorityOutput,
} from "./enum-schema";

describe("Type equality tests", () => {
  describe("enum-schema", () => {
    it("DirectionSchema input matches z.input", () => {
      expectTypeOf<EnumSchemaDirectionInput>().toEqualTypeOf<z.input<typeof EnumSchemaDirectionSchema>>();
    });

    it("DirectionSchema output matches z.output", () => {
      expectTypeOf<EnumSchemaDirectionOutput>().toEqualTypeOf<z.output<typeof EnumSchemaDirectionSchema>>();
    });

    it("ColorSchema input matches z.input", () => {
      expectTypeOf<EnumSchemaColorInput>().toEqualTypeOf<z.input<typeof EnumSchemaColorSchema>>();
    });

    it("ColorSchema output matches z.output", () => {
      expectTypeOf<EnumSchemaColorOutput>().toEqualTypeOf<z.output<typeof EnumSchemaColorSchema>>();
    });

    it("PrioritySchema input matches z.input", () => {
      expectTypeOf<EnumSchemaPriorityInput>().toEqualTypeOf<z.input<typeof EnumSchemaPrioritySchema>>();
    });

    it("PrioritySchema output matches z.output", () => {
      expectTypeOf<EnumSchemaPriorityOutput>().toEqualTypeOf<z.output<typeof EnumSchemaPrioritySchema>>();
    });
  });
});
