// Generated by zinfer - Do not edit manually

export type TreeNodeInput = {
  value: string;
  children?: readonly TreeNodeInput[] | undefined; 
};

export type TreeNodeOutput = {
  value: string;
  children?: readonly TreeNodeOutput[] | undefined; 
};

export type NestedRecordInput = {
  name: string;
  items: {
    [x: string]: NestedRecordInput; 
  }; 
};

export type NestedRecordOutput = {
  name: string;
  items: {
    [x: string]: NestedRecordOutput; 
  }; 
};

export type CallbackInput = {
  name: string;
  callback: functionInput;
  optionalCallback?: Function | undefined; 
};

export type CallbackOutput = {
  name: string;
  callback: functionOutput;
  optionalCallback?: Function | undefined; 
};
