// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- lazy-schema ---
import { CategorySchema as LazySchemaCategorySchema, TreeNodeSchema as LazySchemaTreeNodeSchema, JsonValueSchema as LazySchemaJsonValueSchema } from "../fixtures/lazy-schema";
import type {
  CategoryInput as LazySchemaCategoryInput,
  CategoryOutput as LazySchemaCategoryOutput,
  TreeNodeInput as LazySchemaTreeNodeInput,
  TreeNodeOutput as LazySchemaTreeNodeOutput,
  JsonValueInput as LazySchemaJsonValueInput,
  JsonValueOutput as LazySchemaJsonValueOutput,
} from "./lazy-schema";

describe("Type equality tests", () => {
  describe("lazy-schema", () => {
    it("CategorySchema input matches z.input", () => {
      expectTypeOf<LazySchemaCategoryInput>().toEqualTypeOf<z.input<typeof LazySchemaCategorySchema>>();
    });

    it("CategorySchema output matches z.output", () => {
      expectTypeOf<LazySchemaCategoryOutput>().toEqualTypeOf<z.output<typeof LazySchemaCategorySchema>>();
    });

    it("TreeNodeSchema input matches z.input", () => {
      expectTypeOf<LazySchemaTreeNodeInput>().toEqualTypeOf<z.input<typeof LazySchemaTreeNodeSchema>>();
    });

    it("TreeNodeSchema output matches z.output", () => {
      expectTypeOf<LazySchemaTreeNodeOutput>().toEqualTypeOf<z.output<typeof LazySchemaTreeNodeSchema>>();
    });

    it("JsonValueSchema input matches z.input", () => {
      expectTypeOf<LazySchemaJsonValueInput>().toEqualTypeOf<z.input<typeof LazySchemaJsonValueSchema>>();
    });

    it("JsonValueSchema output matches z.output", () => {
      expectTypeOf<LazySchemaJsonValueOutput>().toEqualTypeOf<z.output<typeof LazySchemaJsonValueSchema>>();
    });
  });
});
