// Generated by zinfer - Do not edit manually

export type PublicDataInput = {
  id: string;
  name: string;
  meta: InternalMetaInput; 
};

export type PublicDataOutput = {
  id: string;
  name: string;
  meta: InternalMetaOutput; 
};
