// Generated by zinfer - Do not edit manually

import type { functionInput, functionOutput } from "./mixed-union-reference-common";

export type JsonValueInput = string | number | boolean | JsonValueInput[] | { [key: string]: JsonValueInput; } | null;

export type JsonValueOutput = string | number | boolean | JsonValueOutput[] | { [key: string]: JsonValueOutput; } | null;

export type MixedValueInput = JsonValueInput | functionInput;

export type MixedValueOutput = JsonValueOutput | functionOutput;

export type ReferencedValueInput = {
  reference: {
    name: string;
  };
  kind: "reference";
  value?: MixedValueInput;
} | {
  referenceName: string;
  kind: "reference";
  value?: MixedValueInput;
};

export type ReferencedValueOutput = {
  referenceName: string;
  kind: "reference";
  value?: MixedValueOutput;
} | {
  referenceName: string;
  kind: "reference";
  value?: MixedValueOutput;
};

export type CallableValueInput = {
  kind: "callable";
  value: functionInput;
};

export type CallableValueOutput = {
  kind: "callable";
  value: functionOutput;
};

export type ValueInput = CallableValueInput | ReferencedValueInput;

export type ValueOutput = CallableValueOutput | ReferencedValueOutput;

export type EnvelopeInput = {
  value: ValueInput;
};

export type EnvelopeOutput = {
  value: ValueOutput;
};

export type SpreadOverrideInput = {
  value?: {
    [x: string]: unknown;
  } | undefined;
};

export type SpreadOverrideOutput = {
  value?: {
    [x: string]: unknown;
  } | undefined;
};

export type SatisfiedSpreadOverrideInput = {
  value?: {
    [x: string]: unknown;
  } | undefined;
};

export type SatisfiedSpreadOverrideOutput = {
  value?: {
    [x: string]: unknown;
  } | undefined;
};

export type RecursiveLeafInput = {
  value: string;
};

export type RecursiveLeafOutput = {
  value: string;
};

export type RecursiveUnionInput = {
  children: any[];
} | {
  value: string;
};

export type RecursiveUnionOutput = {
  children: any[];
} | {
  value: string;
};

export type PublicPlainInput = {
  public: string;
};

export type PublicPlainOutput = {
  public: string;
};

export type MixedPlainUnionInput = {
  internal: string;
} | {
  public: string;
};

export type MixedPlainUnionOutput = {
  internal: string;
} | {
  public: string;
};

export type InlineImportedUnionInput = string | Function;

export type InlineImportedUnionOutput = string | Function;
