// Generated by zinfer - Do not edit manually

export type PublicDataInput = {
  id: string;
  name: string;
  meta: {
    version: number;
    createdAt: Date;
  };
};

export type PublicDataOutput = {
  id: string;
  name: string;
  meta: {
    version: number;
    createdAt: Date;
  };
};
