// Generated by zinfer - Do not edit manually

export type UserInput = {
  id: string;
  name: string;
  email: string; 
};

export type UserOutput = {
  id: string;
  name: string;
  email: string; 
};

export type PostInput = {
  id: string;
  title: string;
  content: string;
  authorId: string;
  publishedAt?: Date | undefined; 
};

export type PostOutput = {
  id: string;
  title: string;
  content: string;
  authorId: string;
  publishedAt?: Date | undefined; 
};

export type CommentInput = {
  id: string;
  content: string;
  postId: string;
  authorId: string;
  createdAt: Date; 
};

export type CommentOutput = {
  id: string;
  content: string;
  postId: string;
  authorId: string;
  createdAt: Date; 
};

export type DateStringInput = {
  date: string; 
};

export type DateStringOutput = {
  date: Date; 
};

export type AliasedInput = any;

export type AliasedOutput = any;
