// Generated by zinfer - Do not edit manually

/**
 * A schema with
 * multiline description
 */
export type MultilineInput = {
  /**
   * User name
   * Must be unique
   */
  name: string;
  /** Age in years */
  age?: number | undefined;
};

export type MultilineOutput = {
  /**
   * User name
   * Must be unique
   */
  name: string;
  /** Age in years */
  age?: number | undefined;
};
