// Generated by zinfer - Do not edit manually

export type PersonInput = {
  name: string;
  address: {
    street: string;
    city: string;
    zipCode: string;
  };
  alternateAddresses: readonly {
    street: string;
    city: string;
    zipCode: string;
  }[];
};

export type PersonOutput = {
  name: string;
  address: {
    street: string;
    city: string;
    zipCode: string;
  };
  alternateAddresses: readonly {
    street: string;
    city: string;
    zipCode: string;
  }[];
};
