// Generated by zinfer - Do not edit manually

export type PersonInput = {
  name: string;
  address: AddressInput;
  alternateAddresses: readonly AddressInput[]; 
};

export type PersonOutput = {
  name: string;
  address: AddressOutput;
  alternateAddresses: readonly AddressOutput[]; 
};
