// Generated by zinfer - Do not edit manually

/**
 * A group of items, or 'none'
 */
export type GroupInput = "none" | readonly { flag: boolean; description?: string | undefined; }[];

export type GroupOutput = "none" | readonly { flag: boolean; description?: string | undefined; }[];

export type ContainerInput = {
  name: string;
  /** Container-level description */
  description?: string | undefined;
  /** A group of items, or 'none' */
  group?: "none" | readonly {
    flag: boolean;
    /** Item description, distinct from container description */
    description?: string | undefined;
  }[] | undefined;
};

export type ContainerOutput = {
  name: string;
  /** Container-level description */
  description?: string | undefined;
  /** A group of items, or 'none' */
  group?: "none" | readonly {
    flag: boolean;
    /** Item description, distinct from container description */
    description?: string | undefined;
  }[] | undefined;
};

export type SiblingUnionInput = {
  choice: {
    /** A description */
    a: string;
  } | {
    /** B description */
    b: string;
  };
};

export type SiblingUnionOutput = {
  choice: {
    /** A description */
    a: string;
  } | {
    /** B description */
    b: string;
  };
};
