// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- nested-schema ---
import { PersonSchema as NestedSchemaPersonSchema } from "../fixtures/nested-schema";
import type { PersonInput as NestedSchemaPersonInput, PersonOutput as NestedSchemaPersonOutput } from "./nested-schema";

describe("Type equality tests", () => {
  describe("nested-schema", () => {
    it("PersonSchema input matches z.input", () => {
      expectTypeOf<NestedSchemaPersonInput>().toEqualTypeOf<z.input<typeof NestedSchemaPersonSchema>>();
    });

    it("PersonSchema output matches z.output", () => {
      expectTypeOf<NestedSchemaPersonOutput>().toEqualTypeOf<z.output<typeof NestedSchemaPersonSchema>>();
    });
  });
});
