// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- nongenerated-ref-schema ---
import { NodeSchema as NongeneratedRefSchemaNodeSchema, TreeSchema as NongeneratedRefSchemaTreeSchema } from "../fixtures/nongenerated-ref-schema";
import type {
  NodeInput as NongeneratedRefSchemaNodeInput,
  NodeOutput as NongeneratedRefSchemaNodeOutput,
  TreeInput as NongeneratedRefSchemaTreeInput,
  TreeOutput as NongeneratedRefSchemaTreeOutput,
} from "./nongenerated-ref-schema";

describe("Type equality tests", () => {
  describe("nongenerated-ref-schema", () => {
    it("NodeSchema input matches z.input", () => {
      expectTypeOf<NongeneratedRefSchemaNodeInput>().toEqualTypeOf<z.input<typeof NongeneratedRefSchemaNodeSchema>>();
    });

    it("NodeSchema output matches z.output", () => {
      expectTypeOf<NongeneratedRefSchemaNodeOutput>().toEqualTypeOf<z.output<typeof NongeneratedRefSchemaNodeSchema>>();
    });

    it("TreeSchema input matches z.input", () => {
      expectTypeOf<NongeneratedRefSchemaTreeInput>().toEqualTypeOf<z.input<typeof NongeneratedRefSchemaTreeSchema>>();
    });

    it("TreeSchema output matches z.output", () => {
      expectTypeOf<NongeneratedRefSchemaTreeOutput>().toEqualTypeOf<z.output<typeof NongeneratedRefSchemaTreeSchema>>();
    });
  });
});
