// Generated by zinfer - Do not edit manually

export type NodeInput = {
  name: string;
  children: {
    [x: string]: NodeInput;
  };
};

export type NodeOutput = {
  name: string;
  children: {
    [x: string]: NodeOutput;
  };
};

export type TreeInput = {
  direct: NodeInput;
  viaGroup: {
    members: NodeInput[];
  };
  viaRegistry: {
    primary: NodeInput;
    groups: {
      members: NodeInput[];
    }[];
  };
};

export type TreeOutput = {
  direct: NodeOutput;
  viaGroup: {
    members: NodeOutput[];
  };
  viaRegistry: {
    primary: NodeOutput;
    groups: {
      members: NodeOutput[];
    }[];
  };
};
