// Generated by zinfer - Do not edit manually

export type CategoryInput = {
  /** Category name */
  name: string;
  /** Nested subcategories */
  subcategories?: any[] | undefined;
};

export type CategoryOutput = {
  /** Category name */
  name: string;
  /** Nested subcategories */
  subcategories?: any[] | undefined;
};

export type CatalogInput = {
  /** Catalog title */
  title: string;
  wrapper: {
    inner: {
      root: CategoryInput;
    };
  };
};

export type CatalogOutput = {
  /** Catalog title */
  title: string;
  wrapper: {
    inner: {
      root: CategoryOutput;
    };
  };
};
