// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- rest-tuple-schema ---
import { RestTupleSchema as RestTupleSchemaRestTupleSchema } from "../fixtures/rest-tuple-schema";
import type { RestTupleInput as RestTupleSchemaRestTupleInput, RestTupleOutput as RestTupleSchemaRestTupleOutput } from "./rest-tuple-schema";

describe("Type equality tests", () => {
  describe("rest-tuple-schema", () => {
    it("RestTupleSchema input matches z.input", () => {
      expectTypeOf<RestTupleSchemaRestTupleInput>().toEqualTypeOf<z.input<typeof RestTupleSchemaRestTupleSchema>>();
    });

    it("RestTupleSchema output matches z.output", () => {
      expectTypeOf<RestTupleSchemaRestTupleOutput>().toEqualTypeOf<z.output<typeof RestTupleSchemaRestTupleSchema>>();
    });
  });
});
