// Generated by zinfer - Do not edit manually

export type AddressInput = {
  street: string;
  city: string;
};

export type AddressOutput = {
  street: string;
  city: string;
};

export type UserInput = {
  name: string;
  address: AddressInput;
  previousAddresses?: AddressInput[];
};

export type UserOutput = {
  name: string;
  address: AddressOutput;
  previousAddresses?: AddressOutput[];
};

export type LooseProfileInput = {
  [x: string]: unknown;
  address: AddressInput;
};

export type LooseProfileOutput = {
  [x: string]: unknown;
  address: AddressOutput;
};
