// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- tuple-schema ---
import { PointSchema as TupleSchemaPointSchema, MixedTupleSchema as TupleSchemaMixedTupleSchema } from "../fixtures/tuple-schema";
import type {
  PointInput as TupleSchemaPointInput,
  PointOutput as TupleSchemaPointOutput,
  MixedTupleInput as TupleSchemaMixedTupleInput,
  MixedTupleOutput as TupleSchemaMixedTupleOutput,
} from "./tuple-schema";

describe("Type equality tests", () => {
  describe("tuple-schema", () => {
    it("PointSchema input matches z.input", () => {
      expectTypeOf<TupleSchemaPointInput>().toEqualTypeOf<z.input<typeof TupleSchemaPointSchema>>();
    });

    it("PointSchema output matches z.output", () => {
      expectTypeOf<TupleSchemaPointOutput>().toEqualTypeOf<z.output<typeof TupleSchemaPointSchema>>();
    });

    it("MixedTupleSchema input matches z.input", () => {
      expectTypeOf<TupleSchemaMixedTupleInput>().toEqualTypeOf<z.input<typeof TupleSchemaMixedTupleSchema>>();
    });

    it("MixedTupleSchema output matches z.output", () => {
      expectTypeOf<TupleSchemaMixedTupleOutput>().toEqualTypeOf<z.output<typeof TupleSchemaMixedTupleSchema>>();
    });
  });
});
