// Generated by zinfer - Do not edit manually

export type StatusInput = "active" | "inactive" | "pending";

export type StatusOutput = "active" | "inactive" | "pending";

export type ResultInput = {
  type: "success";
  data: string; 
} | {
  type: "error";
  message: string; 
};

export type ResultOutput = {
  type: "success";
  data: string; 
} | {
  type: "error";
  message: string; 
};

export type StringOrNumberInput = string | number;

export type StringOrNumberOutput = string | number;
