// Generated by zinfer - Do not edit manually

export type PartialUserInput = {
  id?: string | undefined;
  name?: string | undefined;
  email?: string | undefined;
  age?: number | undefined;
};

export type PartialUserOutput = {
  id?: string | undefined;
  name?: string | undefined;
  email?: string | undefined;
  age?: number | undefined;
};

export type UserIdNameInput = {
  id: string;
  name: string;
};

export type UserIdNameOutput = {
  id: string;
  name: string;
};

export type UserWithoutEmailInput = {
  id: string;
  name: string;
  age: number;
};

export type UserWithoutEmailOutput = {
  id: string;
  name: string;
  age: number;
};

export type RequiredUserInput = {
  id: string;
  name: string;
  email: string;
  age: number;
};

export type RequiredUserOutput = {
  id: string;
  name: string;
  email: string;
  age: number;
};

export type DeepPartialNestedInput = {
  user?: {
    id?: string | undefined;
    name?: string | undefined;
    email?: string | undefined;
    age?: number | undefined;
  } | undefined;
  settings?: {
    theme?: string | undefined;
    notifications?: boolean | undefined;
  } | undefined;
};

export type DeepPartialNestedOutput = {
  user?: {
    id?: string | undefined;
    name?: string | undefined;
    email?: string | undefined;
    age?: number | undefined;
  } | undefined;
  settings?: {
    theme?: string | undefined;
    notifications?: boolean | undefined;
  } | undefined;
};
