// Generated by zinfer-mini - Do not edit manually

export type ContainerInput = {
  root: {
    value: string;
    children?: Record<string, any>;
  };
};

export type ContainerOutput = {
  root: {
    value: string;
    children?: Record<string, any>;
  };
};
