// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- alias-union-member-schema ---
import { BSchema as AliasUnionMemberSchemaBSchema, UnionSchema as AliasUnionMemberSchemaUnionSchema, AliasedA as AliasUnionMemberSchemaAliasedA } from "../fixtures/alias-union-member-schema";
import type {
  BInput as AliasUnionMemberSchemaBInput,
  BOutput as AliasUnionMemberSchemaBOutput,
  UnionInput as AliasUnionMemberSchemaUnionInput,
  UnionOutput as AliasUnionMemberSchemaUnionOutput,
  AliasedAInput as AliasUnionMemberSchemaAliasedAInput,
  AliasedAOutput as AliasUnionMemberSchemaAliasedAOutput,
} from "./alias-union-member-schema";

describe("Type equality tests", () => {
  describe("alias-union-member-schema", () => {
    it("BSchema input matches z.input", () => {
      expectTypeOf<AliasUnionMemberSchemaBInput>().toEqualTypeOf<z.input<typeof AliasUnionMemberSchemaBSchema>>();
    });

    it("BSchema output matches z.output", () => {
      expectTypeOf<AliasUnionMemberSchemaBOutput>().toEqualTypeOf<z.output<typeof AliasUnionMemberSchemaBSchema>>();
    });

    it("UnionSchema input matches z.input", () => {
      expectTypeOf<AliasUnionMemberSchemaUnionInput>().toEqualTypeOf<z.input<typeof AliasUnionMemberSchemaUnionSchema>>();
    });

    it("UnionSchema output matches z.output", () => {
      expectTypeOf<AliasUnionMemberSchemaUnionOutput>().toEqualTypeOf<z.output<typeof AliasUnionMemberSchemaUnionSchema>>();
    });

    it("AliasedA input matches z.input", () => {
      expectTypeOf<AliasUnionMemberSchemaAliasedAInput>().toEqualTypeOf<z.input<typeof AliasUnionMemberSchemaAliasedA>>();
    });

    it("AliasedA output matches z.output", () => {
      expectTypeOf<AliasUnionMemberSchemaAliasedAOutput>().toEqualTypeOf<z.output<typeof AliasUnionMemberSchemaAliasedA>>();
    });
  });
});
