// Generated by zinfer - Do not edit manually

export type ContainerInput = {
  node: AliasedNodeInput;
};

export type ContainerOutput = {
  node: AliasedNodeOutput;
};

export type AliasedNodeInput = {
  id: string;
};

export type AliasedNodeOutput = {
  id: string;
};
