// Generated by zinfer - Do not edit manually

export type BInput = {
  kind: "b";
  b: number;
};

export type BOutput = {
  kind: "b";
  b: number;
};

export type UnionInput = AliasedAInput | BInput;

export type UnionOutput = AliasedAOutput | BOutput;

export type AliasedAInput = {
  kind: "a";
  a: string;
};

export type AliasedAOutput = {
  kind: "a";
  a: string;
};
