// Generated by zinfer - Do not edit manually

export type AliasedCategoryInput = {
  name: string;
  subcategories: AliasedCategoryInput[];
};

export type AliasedCategoryOutput = {
  name: string;
  subcategories: AliasedCategoryOutput[];
};
