// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- array-readonly-schema ---
import { ListSchema as ArrayReadonlySchemaListSchema } from "../fixtures/array-readonly-schema";
import type { ListInput as ArrayReadonlySchemaListInput, ListOutput as ArrayReadonlySchemaListOutput } from "./array-readonly-schema";

describe("Type equality tests", () => {
  describe("array-readonly-schema", () => {
    it("ListSchema input matches z.input", () => {
      expectTypeOf<ArrayReadonlySchemaListInput>().toEqualTypeOf<z.input<typeof ArrayReadonlySchemaListSchema>>();
    });

    it("ListSchema output matches z.output", () => {
      expectTypeOf<ArrayReadonlySchemaListOutput>().toEqualTypeOf<z.output<typeof ArrayReadonlySchemaListSchema>>();
    });
  });
});
