// Generated by zinfer - Do not edit manually

import type { BRAND } from "zod";

export type TagsInput = {
  tags: string[];
  lookup: {
    [x: string]: string;
  };
};

export type TagsOutput = {
  tags: (string & BRAND<"Tag">)[];
  lookup: {
    [x: string]: string & BRAND<"Tag">;
  };
};
