// Generated by zinfer - Do not edit manually

import type { BRAND } from "zod";

export type UserIdInput = string;

export type UserIdOutput = string & BRAND<"UserId">;

export type UserInput = {
  id: string;
  name: string;
  email: string;
};

export type UserOutput = {
  id: string & BRAND<"UserId">;
  name: string;
  email: string;
};
