// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- brand-schema ---
import { UserIdSchema as BrandSchemaUserIdSchema, UserSchema as BrandSchemaUserSchema } from "../fixtures/brand-schema";
import type {
  UserIdInput as BrandSchemaUserIdInput,
  UserIdOutput as BrandSchemaUserIdOutput,
  UserInput as BrandSchemaUserInput,
  UserOutput as BrandSchemaUserOutput,
} from "./brand-schema";

describe("Type equality tests", () => {
  describe("brand-schema", () => {
    it("UserIdSchema input matches z.input", () => {
      expectTypeOf<BrandSchemaUserIdInput>().toEqualTypeOf<z.input<typeof BrandSchemaUserIdSchema>>();
    });

    it("UserIdSchema output matches z.output", () => {
      expectTypeOf<BrandSchemaUserIdOutput>().toEqualTypeOf<z.output<typeof BrandSchemaUserIdSchema>>();
    });

    it("UserSchema input matches z.input", () => {
      expectTypeOf<BrandSchemaUserInput>().toEqualTypeOf<z.input<typeof BrandSchemaUserSchema>>();
    });

    it("UserSchema output matches z.output", () => {
      expectTypeOf<BrandSchemaUserOutput>().toEqualTypeOf<z.output<typeof BrandSchemaUserSchema>>();
    });
  });
});
