// Generated by zinfer - Do not edit manually

export type AddressInput = {
  street: string;
  city: string;
  country: string;
};

export type AddressOutput = {
  street: string;
  city: string;
  country: string;
};

export type UserInput = {
  name: string;
  address: AddressInput;
  previousAddresses?: AddressInput[];
};

export type UserOutput = {
  name: string;
  address: AddressOutput;
  previousAddresses?: AddressOutput[];
};

export type CompanyInput = {
  name: string;
  headquarters: AddressInput;
  employees: UserInput[];
};

export type CompanyOutput = {
  name: string;
  headquarters: AddressOutput;
  employees: UserOutput[];
};
