// Generated by zinfer - Do not edit manually

export type AddressInput = {
  street: string;
  note: "it's here";
};

export type AddressOutput = {
  street: string;
  note: "it's here";
};

export type UserInput = {
  name: string;
  address: AddressInput;
};

export type UserOutput = {
  name: string;
  address: AddressOutput;
};
