// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- cross-ref-schema ---
import { AddressSchema as CrossRefSchemaAddressSchema, UserSchema as CrossRefSchemaUserSchema, CompanySchema as CrossRefSchemaCompanySchema } from "../fixtures/cross-ref-schema";
import type {
  AddressInput as CrossRefSchemaAddressInput,
  AddressOutput as CrossRefSchemaAddressOutput,
  UserInput as CrossRefSchemaUserInput,
  UserOutput as CrossRefSchemaUserOutput,
  CompanyInput as CrossRefSchemaCompanyInput,
  CompanyOutput as CrossRefSchemaCompanyOutput,
} from "./cross-ref-schema";

describe("Type equality tests", () => {
  describe("cross-ref-schema", () => {
    it("AddressSchema input matches z.input", () => {
      expectTypeOf<CrossRefSchemaAddressInput>().toEqualTypeOf<z.input<typeof CrossRefSchemaAddressSchema>>();
    });

    it("AddressSchema output matches z.output", () => {
      expectTypeOf<CrossRefSchemaAddressOutput>().toEqualTypeOf<z.output<typeof CrossRefSchemaAddressSchema>>();
    });

    it("UserSchema input matches z.input", () => {
      expectTypeOf<CrossRefSchemaUserInput>().toEqualTypeOf<z.input<typeof CrossRefSchemaUserSchema>>();
    });

    it("UserSchema output matches z.output", () => {
      expectTypeOf<CrossRefSchemaUserOutput>().toEqualTypeOf<z.output<typeof CrossRefSchemaUserSchema>>();
    });

    it("CompanySchema input matches z.input", () => {
      expectTypeOf<CrossRefSchemaCompanyInput>().toEqualTypeOf<z.input<typeof CrossRefSchemaCompanySchema>>();
    });

    it("CompanySchema output matches z.output", () => {
      expectTypeOf<CrossRefSchemaCompanyOutput>().toEqualTypeOf<z.output<typeof CrossRefSchemaCompanySchema>>();
    });
  });
});
