// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- describe-order-schema ---
import { OrderSchema as DescribeOrderSchemaOrderSchema } from "../fixtures/describe-order-schema";
import type { OrderInput as DescribeOrderSchemaOrderInput, OrderOutput as DescribeOrderSchemaOrderOutput } from "./describe-order-schema";

describe("Type equality tests", () => {
  describe("describe-order-schema", () => {
    it("OrderSchema input matches z.input", () => {
      expectTypeOf<DescribeOrderSchemaOrderInput>().toEqualTypeOf<z.input<typeof DescribeOrderSchemaOrderSchema>>();
    });

    it("OrderSchema output matches z.output", () => {
      expectTypeOf<DescribeOrderSchemaOrderOutput>().toEqualTypeOf<z.output<typeof DescribeOrderSchemaOrderSchema>>();
    });
  });
});
