// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- described-ref-schema ---
import { JsonValueSchema as DescribedRefSchemaJsonValueSchema, FunctionOperationSchema as DescribedRefSchemaFunctionOperationSchema, WorkflowOperationSchema as DescribedRefSchemaWorkflowOperationSchema, OperationSchema as DescribedRefSchemaOperationSchema, ExecutorSchema as DescribedRefSchemaExecutorSchema } from "../fixtures/described-ref-schema";
import type {
  JsonValueInput as DescribedRefSchemaJsonValueInput,
  JsonValueOutput as DescribedRefSchemaJsonValueOutput,
  FunctionOperationInput as DescribedRefSchemaFunctionOperationInput,
  FunctionOperationOutput as DescribedRefSchemaFunctionOperationOutput,
  WorkflowOperationInput as DescribedRefSchemaWorkflowOperationInput,
  WorkflowOperationOutput as DescribedRefSchemaWorkflowOperationOutput,
  OperationInput as DescribedRefSchemaOperationInput,
  OperationOutput as DescribedRefSchemaOperationOutput,
  ExecutorInput as DescribedRefSchemaExecutorInput,
  ExecutorOutput as DescribedRefSchemaExecutorOutput,
} from "./described-ref-schema";

describe("Type equality tests", () => {
  describe("described-ref-schema", () => {
    it("JsonValueSchema input matches z.input", () => {
      expectTypeOf<DescribedRefSchemaJsonValueInput>().toEqualTypeOf<z.input<typeof DescribedRefSchemaJsonValueSchema>>();
    });

    it("JsonValueSchema output matches z.output", () => {
      expectTypeOf<DescribedRefSchemaJsonValueOutput>().toEqualTypeOf<z.output<typeof DescribedRefSchemaJsonValueSchema>>();
    });

    it("FunctionOperationSchema input matches z.input", () => {
      expectTypeOf<DescribedRefSchemaFunctionOperationInput>().toEqualTypeOf<z.input<typeof DescribedRefSchemaFunctionOperationSchema>>();
    });

    it("FunctionOperationSchema output matches z.output", () => {
      expectTypeOf<DescribedRefSchemaFunctionOperationOutput>().toEqualTypeOf<z.output<typeof DescribedRefSchemaFunctionOperationSchema>>();
    });

    it("WorkflowOperationSchema input matches z.input", () => {
      expectTypeOf<DescribedRefSchemaWorkflowOperationInput>().toEqualTypeOf<z.input<typeof DescribedRefSchemaWorkflowOperationSchema>>();
    });

    it("WorkflowOperationSchema output matches z.output", () => {
      expectTypeOf<DescribedRefSchemaWorkflowOperationOutput>().toEqualTypeOf<z.output<typeof DescribedRefSchemaWorkflowOperationSchema>>();
    });

    it("OperationSchema input matches z.input", () => {
      expectTypeOf<DescribedRefSchemaOperationInput>().toEqualTypeOf<z.input<typeof DescribedRefSchemaOperationSchema>>();
    });

    it("OperationSchema output matches z.output", () => {
      expectTypeOf<DescribedRefSchemaOperationOutput>().toEqualTypeOf<z.output<typeof DescribedRefSchemaOperationSchema>>();
    });

    it("ExecutorSchema input matches z.input", () => {
      expectTypeOf<DescribedRefSchemaExecutorInput>().toEqualTypeOf<z.input<typeof DescribedRefSchemaExecutorSchema>>();
    });

    it("ExecutorSchema output matches z.output", () => {
      expectTypeOf<DescribedRefSchemaExecutorOutput>().toEqualTypeOf<z.output<typeof DescribedRefSchemaExecutorSchema>>();
    });
  });
});
