// Generated by zinfer - Do not edit manually

export type OrderInput = {
  a?: string | undefined;
  b?: string | undefined;
};

export type OrderOutput = {
  a?: string | undefined;
  b?: string | undefined;
};
