// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- described-schema ---
import { UserSchema as DescribedSchemaUserSchema, AddressSchema as DescribedSchemaAddressSchema, ProfileSchema as DescribedSchemaProfileSchema } from "../fixtures/described-schema";
import type {
  UserInput as DescribedSchemaUserInput,
  UserOutput as DescribedSchemaUserOutput,
  AddressInput as DescribedSchemaAddressInput,
  AddressOutput as DescribedSchemaAddressOutput,
  ProfileInput as DescribedSchemaProfileInput,
  ProfileOutput as DescribedSchemaProfileOutput,
} from "./described-schema";

describe("Type equality tests", () => {
  describe("described-schema", () => {
    it("UserSchema input matches z.input", () => {
      expectTypeOf<DescribedSchemaUserInput>().toEqualTypeOf<z.input<typeof DescribedSchemaUserSchema>>();
    });

    it("UserSchema output matches z.output", () => {
      expectTypeOf<DescribedSchemaUserOutput>().toEqualTypeOf<z.output<typeof DescribedSchemaUserSchema>>();
    });

    it("AddressSchema input matches z.input", () => {
      expectTypeOf<DescribedSchemaAddressInput>().toEqualTypeOf<z.input<typeof DescribedSchemaAddressSchema>>();
    });

    it("AddressSchema output matches z.output", () => {
      expectTypeOf<DescribedSchemaAddressOutput>().toEqualTypeOf<z.output<typeof DescribedSchemaAddressSchema>>();
    });

    it("ProfileSchema input matches z.input", () => {
      expectTypeOf<DescribedSchemaProfileInput>().toEqualTypeOf<z.input<typeof DescribedSchemaProfileSchema>>();
    });

    it("ProfileSchema output matches z.output", () => {
      expectTypeOf<DescribedSchemaProfileOutput>().toEqualTypeOf<z.output<typeof DescribedSchemaProfileSchema>>();
    });
  });
});
