// Generated by zinfer - Do not edit manually

export type ValueInput = {
  id: string;
};

export type ValueOutput = {
  id: string;
};

export type DuplicateFieldNameInput = {
  child: {
    value: any;
  };
  value: ValueInput;
};

export type DuplicateFieldNameOutput = {
  child: {
    value: any;
  };
  value: ValueOutput;
};
