// Generated by zinfer - Do not edit manually

export type TreeNodeInput = {
  value: string;
  children?: TreeNodeInput[] | undefined;
};

export type TreeNodeOutput = {
  value: string;
  children?: TreeNodeOutput[] | undefined;
};

export type NullableTreeNodeInput = {
  value: string;
  children?: NullableTreeNodeInput[] | null | undefined;
};

export type NullableTreeNodeOutput = {
  value: string;
  children?: NullableTreeNodeOutput[] | null | undefined;
};

export type NestedRecordInput = {
  name: string;
  items: {
    [x: string]: NestedRecordInput;
  };
};

export type NestedRecordOutput = {
  name: string;
  items: {
    [x: string]: NestedRecordOutput;
  };
};

export type CallbackInput = {
  name: string;
  callback: Function;
  optionalCallback?: Function | undefined;
};

export type CallbackOutput = {
  name: string;
  callback: Function;
  optionalCallback?: Function | undefined;
};
