// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- getter-schema ---
import { TreeNodeSchema as GetterSchemaTreeNodeSchema, NestedRecordSchema as GetterSchemaNestedRecordSchema, CallbackSchema as GetterSchemaCallbackSchema } from "../fixtures/getter-schema";
import type {
  TreeNodeInput as GetterSchemaTreeNodeInput,
  TreeNodeOutput as GetterSchemaTreeNodeOutput,
  NestedRecordInput as GetterSchemaNestedRecordInput,
  NestedRecordOutput as GetterSchemaNestedRecordOutput,
  CallbackInput as GetterSchemaCallbackInput,
  CallbackOutput as GetterSchemaCallbackOutput,
} from "./getter-schema";

describe("Type equality tests", () => {
  describe("getter-schema", () => {
    it("TreeNodeSchema input matches z.input", () => {
      expectTypeOf<GetterSchemaTreeNodeInput>().toEqualTypeOf<z.input<typeof GetterSchemaTreeNodeSchema>>();
    });

    it("TreeNodeSchema output matches z.output", () => {
      expectTypeOf<GetterSchemaTreeNodeOutput>().toEqualTypeOf<z.output<typeof GetterSchemaTreeNodeSchema>>();
    });

    it("NestedRecordSchema input matches z.input", () => {
      expectTypeOf<GetterSchemaNestedRecordInput>().toEqualTypeOf<z.input<typeof GetterSchemaNestedRecordSchema>>();
    });

    it("NestedRecordSchema output matches z.output", () => {
      expectTypeOf<GetterSchemaNestedRecordOutput>().toEqualTypeOf<z.output<typeof GetterSchemaNestedRecordSchema>>();
    });

    it("CallbackSchema input matches z.input", () => {
      expectTypeOf<GetterSchemaCallbackInput>().toEqualTypeOf<z.input<typeof GetterSchemaCallbackSchema>>();
    });

    it("CallbackSchema output matches z.output", () => {
      expectTypeOf<GetterSchemaCallbackOutput>().toEqualTypeOf<z.output<typeof GetterSchemaCallbackSchema>>();
    });
  });
});
