// Generated by zinfer - Do not edit manually

export type EntityInput = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
};

export type EntityOutput = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
};

export type MergedInput = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
};

export type MergedOutput = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
};

export type AndInput = {
  id: string;
  version: number;
};

export type AndOutput = {
  id: string;
  version: number;
};
