// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- intersection-schema ---
import { EntitySchema as IntersectionSchemaEntitySchema, MergedSchema as IntersectionSchemaMergedSchema, AndSchema as IntersectionSchemaAndSchema } from "../fixtures/intersection-schema";
import type {
  EntityInput as IntersectionSchemaEntityInput,
  EntityOutput as IntersectionSchemaEntityOutput,
  MergedInput as IntersectionSchemaMergedInput,
  MergedOutput as IntersectionSchemaMergedOutput,
  AndInput as IntersectionSchemaAndInput,
  AndOutput as IntersectionSchemaAndOutput,
} from "./intersection-schema";

describe("Type equality tests", () => {
  describe("intersection-schema", () => {
    it("EntitySchema input matches z.input", () => {
      expectTypeOf<IntersectionSchemaEntityInput>().toEqualTypeOf<z.input<typeof IntersectionSchemaEntitySchema>>();
    });

    it("EntitySchema output matches z.output", () => {
      expectTypeOf<IntersectionSchemaEntityOutput>().toEqualTypeOf<z.output<typeof IntersectionSchemaEntitySchema>>();
    });

    it("MergedSchema input matches z.input", () => {
      expectTypeOf<IntersectionSchemaMergedInput>().toEqualTypeOf<z.input<typeof IntersectionSchemaMergedSchema>>();
    });

    it("MergedSchema output matches z.output", () => {
      expectTypeOf<IntersectionSchemaMergedOutput>().toEqualTypeOf<z.output<typeof IntersectionSchemaMergedSchema>>();
    });

    it("AndSchema input matches z.input", () => {
      expectTypeOf<IntersectionSchemaAndInput>().toEqualTypeOf<z.input<typeof IntersectionSchemaAndSchema>>();
    });

    it("AndSchema output matches z.output", () => {
      expectTypeOf<IntersectionSchemaAndOutput>().toEqualTypeOf<z.output<typeof IntersectionSchemaAndSchema>>();
    });
  });
});
