// Generated by zinfer - Do not edit manually

export type CategoryInput = {
  name: string;
  subcategories: CategoryInput[];
};

export type CategoryOutput = {
  name: string;
  subcategories: CategoryOutput[];
};

export type TreeNodeInput = {
  value: string;
  children: TreeNodeInput[];
  parent?: TreeNodeInput | undefined;
};

export type TreeNodeOutput = {
  value: string;
  children: TreeNodeOutput[];
  parent?: TreeNodeOutput | undefined;
};

export type JsonValueInput = string | number | boolean | JsonValueInput[] | { [key: string]: JsonValueInput; } | null;

export type JsonValueOutput = string | number | boolean | JsonValueOutput[] | { [key: string]: JsonValueOutput; } | null;
