// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- mergeSame-multi-schema ---
import { AddressSchema as MergeSameMultiSchemaAddressSchema, PersonSchema as MergeSameMultiSchemaPersonSchema } from "../fixtures/mergeSame-multi-schema";
import type {
  AddressInput as MergeSameMultiSchemaAddressInput,
  AddressOutput as MergeSameMultiSchemaAddressOutput,
  PersonInput as MergeSameMultiSchemaPersonInput,
  PersonOutput as MergeSameMultiSchemaPersonOutput,
} from "./mergeSame-multi-schema";

describe("Type equality tests", () => {
  describe("mergeSame-multi-schema", () => {
    it("AddressSchema input matches z.input", () => {
      expectTypeOf<MergeSameMultiSchemaAddressInput>().toEqualTypeOf<z.input<typeof MergeSameMultiSchemaAddressSchema>>();
    });

    it("AddressSchema output matches z.output", () => {
      expectTypeOf<MergeSameMultiSchemaAddressOutput>().toEqualTypeOf<z.output<typeof MergeSameMultiSchemaAddressSchema>>();
    });

    it("PersonSchema input matches z.input", () => {
      expectTypeOf<MergeSameMultiSchemaPersonInput>().toEqualTypeOf<z.input<typeof MergeSameMultiSchemaPersonSchema>>();
    });

    it("PersonSchema output matches z.output", () => {
      expectTypeOf<MergeSameMultiSchemaPersonOutput>().toEqualTypeOf<z.output<typeof MergeSameMultiSchemaPersonSchema>>();
    });
  });
});
