// Generated by zinfer - Do not edit manually

export type AddressInput = {
  street: string;
  city: string;
};

export type AddressOutput = {
  street: string;
  city: string;
};

export type PersonInput = {
  name: string;
  address: AddressInput;
  tags: string[];
};

export type PersonOutput = {
  name: string;
  address: AddressOutput;
  tags: string[];
};
