// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- mixed-union-reference-common ---
import { functionSchema as MixedUnionReferenceCommonfunctionSchema } from "../fixtures/mixed-union-reference-common";
import type { functionInput as MixedUnionReferenceCommonfunctionInput, functionOutput as MixedUnionReferenceCommonfunctionOutput } from "./mixed-union-reference-common";

describe("Type equality tests", () => {
  describe("mixed-union-reference-common", () => {
    it("functionSchema input matches z.input", () => {
      expectTypeOf<MixedUnionReferenceCommonfunctionInput>().toEqualTypeOf<z.input<typeof MixedUnionReferenceCommonfunctionSchema>>();
    });

    it("functionSchema output matches z.output", () => {
      expectTypeOf<MixedUnionReferenceCommonfunctionOutput>().toEqualTypeOf<z.output<typeof MixedUnionReferenceCommonfunctionSchema>>();
    });
  });
});
