// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- mixed-export-schema ---
import { PublicDataSchema as MixedExportSchemaPublicDataSchema } from "../fixtures/mixed-export-schema";
import type { PublicDataInput as MixedExportSchemaPublicDataInput, PublicDataOutput as MixedExportSchemaPublicDataOutput } from "./mixed-export-schema";

describe("Type equality tests", () => {
  describe("mixed-export-schema", () => {
    it("PublicDataSchema input matches z.input", () => {
      expectTypeOf<MixedExportSchemaPublicDataInput>().toEqualTypeOf<z.input<typeof MixedExportSchemaPublicDataSchema>>();
    });

    it("PublicDataSchema output matches z.output", () => {
      expectTypeOf<MixedExportSchemaPublicDataOutput>().toEqualTypeOf<z.output<typeof MixedExportSchemaPublicDataSchema>>();
    });
  });
});
