// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- mixed-union-reference-schema ---
import { JsonValueSchema as MixedUnionReferenceSchemaJsonValueSchema, MixedValueSchema as MixedUnionReferenceSchemaMixedValueSchema, ReferencedValueSchema as MixedUnionReferenceSchemaReferencedValueSchema, CallableValueSchema as MixedUnionReferenceSchemaCallableValueSchema, ValueSchema as MixedUnionReferenceSchemaValueSchema, EnvelopeSchema as MixedUnionReferenceSchemaEnvelopeSchema, SpreadOverrideSchema as MixedUnionReferenceSchemaSpreadOverrideSchema, SatisfiedSpreadOverrideSchema as MixedUnionReferenceSchemaSatisfiedSpreadOverrideSchema, RecursiveLeafSchema as MixedUnionReferenceSchemaRecursiveLeafSchema, RecursiveUnionSchema as MixedUnionReferenceSchemaRecursiveUnionSchema, PublicPlainSchema as MixedUnionReferenceSchemaPublicPlainSchema, MixedPlainUnionSchema as MixedUnionReferenceSchemaMixedPlainUnionSchema, InlineImportedUnionSchema as MixedUnionReferenceSchemaInlineImportedUnionSchema } from "../fixtures/mixed-union-reference-schema";
import type {
  JsonValueInput as MixedUnionReferenceSchemaJsonValueInput,
  JsonValueOutput as MixedUnionReferenceSchemaJsonValueOutput,
  MixedValueInput as MixedUnionReferenceSchemaMixedValueInput,
  MixedValueOutput as MixedUnionReferenceSchemaMixedValueOutput,
  ReferencedValueInput as MixedUnionReferenceSchemaReferencedValueInput,
  ReferencedValueOutput as MixedUnionReferenceSchemaReferencedValueOutput,
  CallableValueInput as MixedUnionReferenceSchemaCallableValueInput,
  CallableValueOutput as MixedUnionReferenceSchemaCallableValueOutput,
  ValueInput as MixedUnionReferenceSchemaValueInput,
  ValueOutput as MixedUnionReferenceSchemaValueOutput,
  EnvelopeInput as MixedUnionReferenceSchemaEnvelopeInput,
  EnvelopeOutput as MixedUnionReferenceSchemaEnvelopeOutput,
  SpreadOverrideInput as MixedUnionReferenceSchemaSpreadOverrideInput,
  SpreadOverrideOutput as MixedUnionReferenceSchemaSpreadOverrideOutput,
  SatisfiedSpreadOverrideInput as MixedUnionReferenceSchemaSatisfiedSpreadOverrideInput,
  SatisfiedSpreadOverrideOutput as MixedUnionReferenceSchemaSatisfiedSpreadOverrideOutput,
  RecursiveLeafInput as MixedUnionReferenceSchemaRecursiveLeafInput,
  RecursiveLeafOutput as MixedUnionReferenceSchemaRecursiveLeafOutput,
  RecursiveUnionInput as MixedUnionReferenceSchemaRecursiveUnionInput,
  RecursiveUnionOutput as MixedUnionReferenceSchemaRecursiveUnionOutput,
  PublicPlainInput as MixedUnionReferenceSchemaPublicPlainInput,
  PublicPlainOutput as MixedUnionReferenceSchemaPublicPlainOutput,
  MixedPlainUnionInput as MixedUnionReferenceSchemaMixedPlainUnionInput,
  MixedPlainUnionOutput as MixedUnionReferenceSchemaMixedPlainUnionOutput,
  InlineImportedUnionInput as MixedUnionReferenceSchemaInlineImportedUnionInput,
  InlineImportedUnionOutput as MixedUnionReferenceSchemaInlineImportedUnionOutput,
} from "./mixed-union-reference-schema";

describe("Type equality tests", () => {
  describe("mixed-union-reference-schema", () => {
    it("JsonValueSchema input matches z.input", () => {
      expectTypeOf<MixedUnionReferenceSchemaJsonValueInput>().toEqualTypeOf<z.input<typeof MixedUnionReferenceSchemaJsonValueSchema>>();
    });

    it("JsonValueSchema output matches z.output", () => {
      expectTypeOf<MixedUnionReferenceSchemaJsonValueOutput>().toEqualTypeOf<z.output<typeof MixedUnionReferenceSchemaJsonValueSchema>>();
    });

    it("MixedValueSchema input matches z.input", () => {
      expectTypeOf<MixedUnionReferenceSchemaMixedValueInput>().toEqualTypeOf<z.input<typeof MixedUnionReferenceSchemaMixedValueSchema>>();
    });

    it("MixedValueSchema output matches z.output", () => {
      expectTypeOf<MixedUnionReferenceSchemaMixedValueOutput>().toEqualTypeOf<z.output<typeof MixedUnionReferenceSchemaMixedValueSchema>>();
    });

    it("ReferencedValueSchema input matches z.input", () => {
      expectTypeOf<MixedUnionReferenceSchemaReferencedValueInput>().toEqualTypeOf<z.input<typeof MixedUnionReferenceSchemaReferencedValueSchema>>();
    });

    it("ReferencedValueSchema output matches z.output", () => {
      expectTypeOf<MixedUnionReferenceSchemaReferencedValueOutput>().toEqualTypeOf<z.output<typeof MixedUnionReferenceSchemaReferencedValueSchema>>();
    });

    it("CallableValueSchema input matches z.input", () => {
      expectTypeOf<MixedUnionReferenceSchemaCallableValueInput>().toEqualTypeOf<z.input<typeof MixedUnionReferenceSchemaCallableValueSchema>>();
    });

    it("CallableValueSchema output matches z.output", () => {
      expectTypeOf<MixedUnionReferenceSchemaCallableValueOutput>().toEqualTypeOf<z.output<typeof MixedUnionReferenceSchemaCallableValueSchema>>();
    });

    it("ValueSchema input matches z.input", () => {
      expectTypeOf<MixedUnionReferenceSchemaValueInput>().toEqualTypeOf<z.input<typeof MixedUnionReferenceSchemaValueSchema>>();
    });

    it("ValueSchema output matches z.output", () => {
      expectTypeOf<MixedUnionReferenceSchemaValueOutput>().toEqualTypeOf<z.output<typeof MixedUnionReferenceSchemaValueSchema>>();
    });

    it("EnvelopeSchema input matches z.input", () => {
      expectTypeOf<MixedUnionReferenceSchemaEnvelopeInput>().toEqualTypeOf<z.input<typeof MixedUnionReferenceSchemaEnvelopeSchema>>();
    });

    it("EnvelopeSchema output matches z.output", () => {
      expectTypeOf<MixedUnionReferenceSchemaEnvelopeOutput>().toEqualTypeOf<z.output<typeof MixedUnionReferenceSchemaEnvelopeSchema>>();
    });

    it("SpreadOverrideSchema input matches z.input", () => {
      expectTypeOf<MixedUnionReferenceSchemaSpreadOverrideInput>().toEqualTypeOf<z.input<typeof MixedUnionReferenceSchemaSpreadOverrideSchema>>();
    });

    it("SpreadOverrideSchema output matches z.output", () => {
      expectTypeOf<MixedUnionReferenceSchemaSpreadOverrideOutput>().toEqualTypeOf<z.output<typeof MixedUnionReferenceSchemaSpreadOverrideSchema>>();
    });

    it("SatisfiedSpreadOverrideSchema input matches z.input", () => {
      expectTypeOf<MixedUnionReferenceSchemaSatisfiedSpreadOverrideInput>().toEqualTypeOf<z.input<typeof MixedUnionReferenceSchemaSatisfiedSpreadOverrideSchema>>();
    });

    it("SatisfiedSpreadOverrideSchema output matches z.output", () => {
      expectTypeOf<MixedUnionReferenceSchemaSatisfiedSpreadOverrideOutput>().toEqualTypeOf<z.output<typeof MixedUnionReferenceSchemaSatisfiedSpreadOverrideSchema>>();
    });

    it("RecursiveLeafSchema input matches z.input", () => {
      expectTypeOf<MixedUnionReferenceSchemaRecursiveLeafInput>().toEqualTypeOf<z.input<typeof MixedUnionReferenceSchemaRecursiveLeafSchema>>();
    });

    it("RecursiveLeafSchema output matches z.output", () => {
      expectTypeOf<MixedUnionReferenceSchemaRecursiveLeafOutput>().toEqualTypeOf<z.output<typeof MixedUnionReferenceSchemaRecursiveLeafSchema>>();
    });

    it("RecursiveUnionSchema input matches z.input", () => {
      expectTypeOf<MixedUnionReferenceSchemaRecursiveUnionInput>().toEqualTypeOf<z.input<typeof MixedUnionReferenceSchemaRecursiveUnionSchema>>();
    });

    it("RecursiveUnionSchema output matches z.output", () => {
      expectTypeOf<MixedUnionReferenceSchemaRecursiveUnionOutput>().toEqualTypeOf<z.output<typeof MixedUnionReferenceSchemaRecursiveUnionSchema>>();
    });

    it("PublicPlainSchema input matches z.input", () => {
      expectTypeOf<MixedUnionReferenceSchemaPublicPlainInput>().toEqualTypeOf<z.input<typeof MixedUnionReferenceSchemaPublicPlainSchema>>();
    });

    it("PublicPlainSchema output matches z.output", () => {
      expectTypeOf<MixedUnionReferenceSchemaPublicPlainOutput>().toEqualTypeOf<z.output<typeof MixedUnionReferenceSchemaPublicPlainSchema>>();
    });

    it("MixedPlainUnionSchema input matches z.input", () => {
      expectTypeOf<MixedUnionReferenceSchemaMixedPlainUnionInput>().toEqualTypeOf<z.input<typeof MixedUnionReferenceSchemaMixedPlainUnionSchema>>();
    });

    it("MixedPlainUnionSchema output matches z.output", () => {
      expectTypeOf<MixedUnionReferenceSchemaMixedPlainUnionOutput>().toEqualTypeOf<z.output<typeof MixedUnionReferenceSchemaMixedPlainUnionSchema>>();
    });

    it("InlineImportedUnionSchema input matches z.input", () => {
      expectTypeOf<MixedUnionReferenceSchemaInlineImportedUnionInput>().toEqualTypeOf<z.input<typeof MixedUnionReferenceSchemaInlineImportedUnionSchema>>();
    });

    it("InlineImportedUnionSchema output matches z.output", () => {
      expectTypeOf<MixedUnionReferenceSchemaInlineImportedUnionOutput>().toEqualTypeOf<z.output<typeof MixedUnionReferenceSchemaInlineImportedUnionSchema>>();
    });
  });
});
