// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- multi-schema ---
import { UserSchema as MultiSchemaUserSchema, PostSchema as MultiSchemaPostSchema, CommentSchema as MultiSchemaCommentSchema, DateStringSchema as MultiSchemaDateStringSchema, AliasedSchema as MultiSchemaAliasedSchema } from "../fixtures/multi-schema";
import type {
  UserInput as MultiSchemaUserInput,
  UserOutput as MultiSchemaUserOutput,
  PostInput as MultiSchemaPostInput,
  PostOutput as MultiSchemaPostOutput,
  CommentInput as MultiSchemaCommentInput,
  CommentOutput as MultiSchemaCommentOutput,
  DateStringInput as MultiSchemaDateStringInput,
  DateStringOutput as MultiSchemaDateStringOutput,
  AliasedInput as MultiSchemaAliasedInput,
  AliasedOutput as MultiSchemaAliasedOutput,
} from "./multi-schema";

describe("Type equality tests", () => {
  describe("multi-schema", () => {
    it("UserSchema input matches z.input", () => {
      expectTypeOf<MultiSchemaUserInput>().toEqualTypeOf<z.input<typeof MultiSchemaUserSchema>>();
    });

    it("UserSchema output matches z.output", () => {
      expectTypeOf<MultiSchemaUserOutput>().toEqualTypeOf<z.output<typeof MultiSchemaUserSchema>>();
    });

    it("PostSchema input matches z.input", () => {
      expectTypeOf<MultiSchemaPostInput>().toEqualTypeOf<z.input<typeof MultiSchemaPostSchema>>();
    });

    it("PostSchema output matches z.output", () => {
      expectTypeOf<MultiSchemaPostOutput>().toEqualTypeOf<z.output<typeof MultiSchemaPostSchema>>();
    });

    it("CommentSchema input matches z.input", () => {
      expectTypeOf<MultiSchemaCommentInput>().toEqualTypeOf<z.input<typeof MultiSchemaCommentSchema>>();
    });

    it("CommentSchema output matches z.output", () => {
      expectTypeOf<MultiSchemaCommentOutput>().toEqualTypeOf<z.output<typeof MultiSchemaCommentSchema>>();
    });

    it("DateStringSchema input matches z.input", () => {
      expectTypeOf<MultiSchemaDateStringInput>().toEqualTypeOf<z.input<typeof MultiSchemaDateStringSchema>>();
    });

    it("DateStringSchema output matches z.output", () => {
      expectTypeOf<MultiSchemaDateStringOutput>().toEqualTypeOf<z.output<typeof MultiSchemaDateStringSchema>>();
    });

    it("AliasedSchema input matches z.input", () => {
      expectTypeOf<MultiSchemaAliasedInput>().toEqualTypeOf<z.input<typeof MultiSchemaAliasedSchema>>();
    });

    it("AliasedSchema output matches z.output", () => {
      expectTypeOf<MultiSchemaAliasedOutput>().toEqualTypeOf<z.output<typeof MultiSchemaAliasedSchema>>();
    });
  });
});
