// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- nonexported-brand-schema ---
import { PublicPlainSchema as NonexportedBrandSchemaPublicPlainSchema } from "../fixtures/nonexported-brand-schema";
import type { PublicPlainInput as NonexportedBrandSchemaPublicPlainInput, PublicPlainOutput as NonexportedBrandSchemaPublicPlainOutput } from "./nonexported-brand-schema";

describe("Type equality tests", () => {
  describe("nonexported-brand-schema", () => {
    it("PublicPlainSchema input matches z.input", () => {
      expectTypeOf<NonexportedBrandSchemaPublicPlainInput>().toEqualTypeOf<z.input<typeof NonexportedBrandSchemaPublicPlainSchema>>();
    });

    it("PublicPlainSchema output matches z.output", () => {
      expectTypeOf<NonexportedBrandSchemaPublicPlainOutput>().toEqualTypeOf<z.output<typeof NonexportedBrandSchemaPublicPlainSchema>>();
    });
  });
});
