// Generated by zinfer - Do not edit manually

type NodeInput = {
  value: string;
  children?: Record<string, NodeInput>;
};

type NodeOutput = {
  value: string;
  children?: Record<string, NodeOutput>;
};

export type ContainerInput = {
  name: string;
  root: NodeInput;
};

export type ContainerOutput = {
  name: string;
  root: NodeOutput;
};
