// Generated by zinfer - Do not edit manually

import type { BRAND } from "zod";

export type WrapperInput = {
  tags: string[];
};

export type WrapperOutput = { tags: (string & BRAND<"Tag">)[]; } & BRAND<"Wrapper">;
