// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- object-brand-schema ---
import { WrapperSchema as ObjectBrandSchemaWrapperSchema } from "../fixtures/object-brand-schema";
import type { WrapperInput as ObjectBrandSchemaWrapperInput, WrapperOutput as ObjectBrandSchemaWrapperOutput } from "./object-brand-schema";

describe("Type equality tests", () => {
  describe("object-brand-schema", () => {
    it("WrapperSchema input matches z.input", () => {
      expectTypeOf<ObjectBrandSchemaWrapperInput>().toEqualTypeOf<z.input<typeof ObjectBrandSchemaWrapperSchema>>();
    });

    it("WrapperSchema output matches z.output", () => {
      expectTypeOf<ObjectBrandSchemaWrapperOutput>().toEqualTypeOf<z.output<typeof ObjectBrandSchemaWrapperSchema>>();
    });
  });
});
