// Generated by zinfer - Do not edit manually

export type Address = {
  street: string;
  city: string;
};
export type AddressInput = Address;
export type AddressOutput = Address;

export type Person = {
  name: string;
  address: Address;
  tags: string[];
};
export type PersonInput = Person;
export type PersonOutput = Person;
