// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- recursive-json-schema ---
import { JsonSchema as RecursiveJsonSchemaJsonSchema } from "../fixtures/recursive-json-schema";
import type { JsonInput as RecursiveJsonSchemaJsonInput, JsonOutput as RecursiveJsonSchemaJsonOutput } from "./recursive-json-schema";

describe("Type equality tests", () => {
  describe("recursive-json-schema", () => {
    it("JsonSchema input matches z.input", () => {
      expectTypeOf<RecursiveJsonSchemaJsonInput>().toEqualTypeOf<z.input<typeof RecursiveJsonSchemaJsonSchema>>();
    });

    it("JsonSchema output matches z.output", () => {
      expectTypeOf<RecursiveJsonSchemaJsonOutput>().toEqualTypeOf<z.output<typeof RecursiveJsonSchemaJsonSchema>>();
    });
  });
});
