// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- recursive-record-schema ---
import { RecursiveRecordSchema as RecursiveRecordSchemaRecursiveRecordSchema, OptionalRecursiveRecordSchema as RecursiveRecordSchemaOptionalRecursiveRecordSchema, InferredOptionalRecordSchema as RecursiveRecordSchemaInferredOptionalRecordSchema, RecursiveArraySchema as RecursiveRecordSchemaRecursiveArraySchema, LeafRecordSchema as RecursiveRecordSchemaLeafRecordSchema } from "../fixtures/recursive-record-schema";
import type {
  RecursiveRecordInput as RecursiveRecordSchemaRecursiveRecordInput,
  RecursiveRecordOutput as RecursiveRecordSchemaRecursiveRecordOutput,
  OptionalRecursiveRecordInput as RecursiveRecordSchemaOptionalRecursiveRecordInput,
  OptionalRecursiveRecordOutput as RecursiveRecordSchemaOptionalRecursiveRecordOutput,
  InferredOptionalRecordInput as RecursiveRecordSchemaInferredOptionalRecordInput,
  InferredOptionalRecordOutput as RecursiveRecordSchemaInferredOptionalRecordOutput,
  RecursiveArrayInput as RecursiveRecordSchemaRecursiveArrayInput,
  RecursiveArrayOutput as RecursiveRecordSchemaRecursiveArrayOutput,
  LeafRecordInput as RecursiveRecordSchemaLeafRecordInput,
  LeafRecordOutput as RecursiveRecordSchemaLeafRecordOutput,
} from "./recursive-record-schema";

describe("Type equality tests", () => {
  describe("recursive-record-schema", () => {
    it("RecursiveRecordSchema input matches z.input", () => {
      expectTypeOf<RecursiveRecordSchemaRecursiveRecordInput>().toEqualTypeOf<z.input<typeof RecursiveRecordSchemaRecursiveRecordSchema>>();
    });

    it("RecursiveRecordSchema output matches z.output", () => {
      expectTypeOf<RecursiveRecordSchemaRecursiveRecordOutput>().toEqualTypeOf<z.output<typeof RecursiveRecordSchemaRecursiveRecordSchema>>();
    });

    it("OptionalRecursiveRecordSchema input matches z.input", () => {
      expectTypeOf<RecursiveRecordSchemaOptionalRecursiveRecordInput>().toEqualTypeOf<z.input<typeof RecursiveRecordSchemaOptionalRecursiveRecordSchema>>();
    });

    it("OptionalRecursiveRecordSchema output matches z.output", () => {
      expectTypeOf<RecursiveRecordSchemaOptionalRecursiveRecordOutput>().toEqualTypeOf<z.output<typeof RecursiveRecordSchemaOptionalRecursiveRecordSchema>>();
    });

    it("InferredOptionalRecordSchema input matches z.input", () => {
      expectTypeOf<RecursiveRecordSchemaInferredOptionalRecordInput>().toEqualTypeOf<z.input<typeof RecursiveRecordSchemaInferredOptionalRecordSchema>>();
    });

    it("InferredOptionalRecordSchema output matches z.output", () => {
      expectTypeOf<RecursiveRecordSchemaInferredOptionalRecordOutput>().toEqualTypeOf<z.output<typeof RecursiveRecordSchemaInferredOptionalRecordSchema>>();
    });

    it("RecursiveArraySchema input matches z.input", () => {
      expectTypeOf<RecursiveRecordSchemaRecursiveArrayInput>().toEqualTypeOf<z.input<typeof RecursiveRecordSchemaRecursiveArraySchema>>();
    });

    it("RecursiveArraySchema output matches z.output", () => {
      expectTypeOf<RecursiveRecordSchemaRecursiveArrayOutput>().toEqualTypeOf<z.output<typeof RecursiveRecordSchemaRecursiveArraySchema>>();
    });

    it("LeafRecordSchema input matches z.input", () => {
      expectTypeOf<RecursiveRecordSchemaLeafRecordInput>().toEqualTypeOf<z.input<typeof RecursiveRecordSchemaLeafRecordSchema>>();
    });

    it("LeafRecordSchema output matches z.output", () => {
      expectTypeOf<RecursiveRecordSchemaLeafRecordOutput>().toEqualTypeOf<z.output<typeof RecursiveRecordSchemaLeafRecordSchema>>();
    });
  });
});
