// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- recursive-reference-schema ---
import { RefNodeSchema as RecursiveReferenceSchemaRefNodeSchema, RefHolderSchema as RecursiveReferenceSchemaRefHolderSchema } from "../fixtures/recursive-reference-schema";
import type {
  RefNodeInput as RecursiveReferenceSchemaRefNodeInput,
  RefNodeOutput as RecursiveReferenceSchemaRefNodeOutput,
  RefHolderInput as RecursiveReferenceSchemaRefHolderInput,
  RefHolderOutput as RecursiveReferenceSchemaRefHolderOutput,
} from "./recursive-reference-schema";

describe("Type equality tests", () => {
  describe("recursive-reference-schema", () => {
    it("RefNodeSchema input matches z.input", () => {
      expectTypeOf<RecursiveReferenceSchemaRefNodeInput>().toEqualTypeOf<z.input<typeof RecursiveReferenceSchemaRefNodeSchema>>();
    });

    it("RefNodeSchema output matches z.output", () => {
      expectTypeOf<RecursiveReferenceSchemaRefNodeOutput>().toEqualTypeOf<z.output<typeof RecursiveReferenceSchemaRefNodeSchema>>();
    });

    it("RefHolderSchema input matches z.input", () => {
      expectTypeOf<RecursiveReferenceSchemaRefHolderInput>().toEqualTypeOf<z.input<typeof RecursiveReferenceSchemaRefHolderSchema>>();
    });

    it("RefHolderSchema output matches z.output", () => {
      expectTypeOf<RecursiveReferenceSchemaRefHolderOutput>().toEqualTypeOf<z.output<typeof RecursiveReferenceSchemaRefHolderSchema>>();
    });
  });
});
