// Generated by zinfer - Do not edit manually

export type RefNodeInput = {
  name: string;
  children: RefNodeInput[];
};

export type RefNodeOutput = {
  name: string;
  children: RefNodeOutput[];
};

export type RefHolderInput = {
  one: RefNodeInput;
  list: RefNodeInput[];
  map: {
    [x: string]: RefNodeInput;
  };
  optional?: RefNodeInput;
};

export type RefHolderOutput = {
  one: RefNodeOutput;
  list: RefNodeOutput[];
  map: {
    [x: string]: RefNodeOutput;
  };
  optional?: RefNodeOutput;
};
