// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- strict-object-schema ---
import { AddressSchema as StrictObjectSchemaAddressSchema, UserSchema as StrictObjectSchemaUserSchema, LooseProfileSchema as StrictObjectSchemaLooseProfileSchema } from "../fixtures/strict-object-schema";
import type {
  AddressInput as StrictObjectSchemaAddressInput,
  AddressOutput as StrictObjectSchemaAddressOutput,
  UserInput as StrictObjectSchemaUserInput,
  UserOutput as StrictObjectSchemaUserOutput,
  LooseProfileInput as StrictObjectSchemaLooseProfileInput,
  LooseProfileOutput as StrictObjectSchemaLooseProfileOutput,
} from "./strict-object-schema";

describe("Type equality tests", () => {
  describe("strict-object-schema", () => {
    it("AddressSchema input matches z.input", () => {
      expectTypeOf<StrictObjectSchemaAddressInput>().toEqualTypeOf<z.input<typeof StrictObjectSchemaAddressSchema>>();
    });

    it("AddressSchema output matches z.output", () => {
      expectTypeOf<StrictObjectSchemaAddressOutput>().toEqualTypeOf<z.output<typeof StrictObjectSchemaAddressSchema>>();
    });

    it("UserSchema input matches z.input", () => {
      expectTypeOf<StrictObjectSchemaUserInput>().toEqualTypeOf<z.input<typeof StrictObjectSchemaUserSchema>>();
    });

    it("UserSchema output matches z.output", () => {
      expectTypeOf<StrictObjectSchemaUserOutput>().toEqualTypeOf<z.output<typeof StrictObjectSchemaUserSchema>>();
    });

    it("LooseProfileSchema input matches z.input", () => {
      expectTypeOf<StrictObjectSchemaLooseProfileInput>().toEqualTypeOf<z.input<typeof StrictObjectSchemaLooseProfileSchema>>();
    });

    it("LooseProfileSchema output matches z.output", () => {
      expectTypeOf<StrictObjectSchemaLooseProfileOutput>().toEqualTypeOf<z.output<typeof StrictObjectSchemaLooseProfileSchema>>();
    });
  });
});
