// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- template-literal-schema ---
import { LevelSchema as TemplateLiteralSchemaLevelSchema, GreetingSchema as TemplateLiteralSchemaGreetingSchema, VersionSchema as TemplateLiteralSchemaVersionSchema, LogLineSchema as TemplateLiteralSchemaLogLineSchema, LocalePathSchema as TemplateLiteralSchemaLocalePathSchema, SlugSchema as TemplateLiteralSchemaSlugSchema, PortSchema as TemplateLiteralSchemaPortSchema, FlagSchema as TemplateLiteralSchemaFlagSchema, BigIntSchema as TemplateLiteralSchemaBigIntSchema, FixedSchema as TemplateLiteralSchemaFixedSchema, NestedSchema as TemplateLiteralSchemaNestedSchema, OptionalSchema as TemplateLiteralSchemaOptionalSchema, BrandedSchema as TemplateLiteralSchemaBrandedSchema, LengthSchema as TemplateLiteralSchemaLengthSchema, RouteSchema as TemplateLiteralSchemaRouteSchema, CountsSchema as TemplateLiteralSchemaCountsSchema, MixedSchema as TemplateLiteralSchemaMixedSchema, QuotedSchema as TemplateLiteralSchemaQuotedSchema } from "../fixtures/template-literal-schema";
import type {
  LevelInput as TemplateLiteralSchemaLevelInput,
  LevelOutput as TemplateLiteralSchemaLevelOutput,
  GreetingInput as TemplateLiteralSchemaGreetingInput,
  GreetingOutput as TemplateLiteralSchemaGreetingOutput,
  VersionInput as TemplateLiteralSchemaVersionInput,
  VersionOutput as TemplateLiteralSchemaVersionOutput,
  LogLineInput as TemplateLiteralSchemaLogLineInput,
  LogLineOutput as TemplateLiteralSchemaLogLineOutput,
  LocalePathInput as TemplateLiteralSchemaLocalePathInput,
  LocalePathOutput as TemplateLiteralSchemaLocalePathOutput,
  SlugInput as TemplateLiteralSchemaSlugInput,
  SlugOutput as TemplateLiteralSchemaSlugOutput,
  PortInput as TemplateLiteralSchemaPortInput,
  PortOutput as TemplateLiteralSchemaPortOutput,
  FlagInput as TemplateLiteralSchemaFlagInput,
  FlagOutput as TemplateLiteralSchemaFlagOutput,
  BigIntInput as TemplateLiteralSchemaBigIntInput,
  BigIntOutput as TemplateLiteralSchemaBigIntOutput,
  FixedInput as TemplateLiteralSchemaFixedInput,
  FixedOutput as TemplateLiteralSchemaFixedOutput,
  NestedInput as TemplateLiteralSchemaNestedInput,
  NestedOutput as TemplateLiteralSchemaNestedOutput,
  OptionalInput as TemplateLiteralSchemaOptionalInput,
  OptionalOutput as TemplateLiteralSchemaOptionalOutput,
  BrandedInput as TemplateLiteralSchemaBrandedInput,
  BrandedOutput as TemplateLiteralSchemaBrandedOutput,
  LengthInput as TemplateLiteralSchemaLengthInput,
  LengthOutput as TemplateLiteralSchemaLengthOutput,
  RouteInput as TemplateLiteralSchemaRouteInput,
  RouteOutput as TemplateLiteralSchemaRouteOutput,
  CountsInput as TemplateLiteralSchemaCountsInput,
  CountsOutput as TemplateLiteralSchemaCountsOutput,
  MixedInput as TemplateLiteralSchemaMixedInput,
  MixedOutput as TemplateLiteralSchemaMixedOutput,
  QuotedInput as TemplateLiteralSchemaQuotedInput,
  QuotedOutput as TemplateLiteralSchemaQuotedOutput,
} from "./template-literal-schema";

describe("Type equality tests", () => {
  describe("template-literal-schema", () => {
    it("LevelSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaLevelInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaLevelSchema>>();
    });

    it("LevelSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaLevelOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaLevelSchema>>();
    });

    it("GreetingSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaGreetingInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaGreetingSchema>>();
    });

    it("GreetingSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaGreetingOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaGreetingSchema>>();
    });

    it("VersionSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaVersionInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaVersionSchema>>();
    });

    it("VersionSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaVersionOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaVersionSchema>>();
    });

    it("LogLineSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaLogLineInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaLogLineSchema>>();
    });

    it("LogLineSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaLogLineOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaLogLineSchema>>();
    });

    it("LocalePathSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaLocalePathInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaLocalePathSchema>>();
    });

    it("LocalePathSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaLocalePathOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaLocalePathSchema>>();
    });

    it("SlugSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaSlugInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaSlugSchema>>();
    });

    it("SlugSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaSlugOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaSlugSchema>>();
    });

    it("PortSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaPortInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaPortSchema>>();
    });

    it("PortSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaPortOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaPortSchema>>();
    });

    it("FlagSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaFlagInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaFlagSchema>>();
    });

    it("FlagSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaFlagOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaFlagSchema>>();
    });

    it("BigIntSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaBigIntInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaBigIntSchema>>();
    });

    it("BigIntSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaBigIntOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaBigIntSchema>>();
    });

    it("FixedSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaFixedInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaFixedSchema>>();
    });

    it("FixedSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaFixedOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaFixedSchema>>();
    });

    it("NestedSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaNestedInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaNestedSchema>>();
    });

    it("NestedSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaNestedOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaNestedSchema>>();
    });

    it("OptionalSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaOptionalInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaOptionalSchema>>();
    });

    it("OptionalSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaOptionalOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaOptionalSchema>>();
    });

    it("BrandedSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaBrandedInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaBrandedSchema>>();
    });

    it("BrandedSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaBrandedOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaBrandedSchema>>();
    });

    it("LengthSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaLengthInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaLengthSchema>>();
    });

    it("LengthSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaLengthOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaLengthSchema>>();
    });

    it("RouteSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaRouteInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaRouteSchema>>();
    });

    it("RouteSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaRouteOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaRouteSchema>>();
    });

    it("CountsSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaCountsInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaCountsSchema>>();
    });

    it("CountsSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaCountsOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaCountsSchema>>();
    });

    it("MixedSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaMixedInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaMixedSchema>>();
    });

    it("MixedSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaMixedOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaMixedSchema>>();
    });

    it("QuotedSchema input matches z.input", () => {
      expectTypeOf<TemplateLiteralSchemaQuotedInput>().toEqualTypeOf<z.input<typeof TemplateLiteralSchemaQuotedSchema>>();
    });

    it("QuotedSchema output matches z.output", () => {
      expectTypeOf<TemplateLiteralSchemaQuotedOutput>().toEqualTypeOf<z.output<typeof TemplateLiteralSchemaQuotedSchema>>();
    });
  });
});
