// Generated by zinfer - Do not edit manually

import type { BRAND } from "zod";

export type LevelInput = "debug" | "info";

export type LevelOutput = "debug" | "info";

export type GreetingInput = `hello, ${string}!`;

export type GreetingOutput = `hello, ${string}!`;

export type VersionInput = "v1" | "v2";

export type VersionOutput = "v1" | "v2";

export type LogLineInput = "log:debug" | "log:info";

export type LogLineOutput = "log:debug" | "log:info";

export type LocalePathInput = "/en" | "/ja";

export type LocalePathOutput = "/en" | "/ja";

export type SlugInput = "a-x" | "a-y" | "b-x" | "b-y";

export type SlugOutput = "a-x" | "a-y" | "b-x" | "b-y";

export type PortInput = `port:${number}`;

export type PortOutput = `port:${number}`;

export type FlagInput = "flag=false" | "flag=true";

export type FlagOutput = "flag=false" | "flag=true";

export type BigIntInput = `big:${bigint}`;

export type BigIntOutput = `big:${bigint}`;

export type FixedInput = "id_x";

export type FixedOutput = "id_x";

export type NestedInput = "outer-log:debug" | "outer-log:info";

export type NestedOutput = "outer-log:debug" | "outer-log:info";

export type OptionalInput = "opt-a" | "opt-b" | undefined;

export type OptionalOutput = "opt-a" | "opt-b" | undefined;

export type BrandedInput = `u_${string}`;

export type BrandedOutput = `u_${string}` & BRAND<"UserId">;

export type LengthInput = "ta" | "tb";

export type LengthOutput = number;

export type RouteInput = {
  path: `/users/${number}` | `/posts/${number}`;
  tags: ("tag:a" | "tag:b")[];
};

export type RouteOutput = {
  path: `/users/${number}` | `/posts/${number}`;
  tags: ("tag:a" | "tag:b")[];
};

export type CountsInput = {
  ka: number;
  kb: number;
};

export type CountsOutput = {
  ka: number;
  kb: number;
};

export type MixedInput = "pa" | "plain";

export type MixedOutput = "pa" | "plain";

export type QuotedInput = "say \"hi\"";

export type QuotedOutput = "say \"hi\"";
