// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- transform-schema ---
import { DateSchema as TransformSchemaDateSchema } from "../fixtures/transform-schema";
import type { DateInput as TransformSchemaDateInput, DateOutput as TransformSchemaDateOutput } from "./transform-schema";

describe("Type equality tests", () => {
  describe("transform-schema", () => {
    it("DateSchema input matches z.input", () => {
      expectTypeOf<TransformSchemaDateInput>().toEqualTypeOf<z.input<typeof TransformSchemaDateSchema>>();
    });

    it("DateSchema output matches z.output", () => {
      expectTypeOf<TransformSchemaDateOutput>().toEqualTypeOf<z.output<typeof TransformSchemaDateSchema>>();
    });
  });
});
