// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- tuple-brand-schema ---
import { CoordSchema as TupleBrandSchemaCoordSchema, TagListSchema as TupleBrandSchemaTagListSchema, FrozenPairSchema as TupleBrandSchemaFrozenPairSchema, HeadedListSchema as TupleBrandSchemaHeadedListSchema, ShapeSchema as TupleBrandSchemaShapeSchema } from "../fixtures/tuple-brand-schema";
import type {
  CoordInput as TupleBrandSchemaCoordInput,
  CoordOutput as TupleBrandSchemaCoordOutput,
  TagListInput as TupleBrandSchemaTagListInput,
  TagListOutput as TupleBrandSchemaTagListOutput,
  FrozenPairInput as TupleBrandSchemaFrozenPairInput,
  FrozenPairOutput as TupleBrandSchemaFrozenPairOutput,
  HeadedListInput as TupleBrandSchemaHeadedListInput,
  HeadedListOutput as TupleBrandSchemaHeadedListOutput,
  ShapeInput as TupleBrandSchemaShapeInput,
  ShapeOutput as TupleBrandSchemaShapeOutput,
} from "./tuple-brand-schema";

describe("Type equality tests", () => {
  describe("tuple-brand-schema", () => {
    it("CoordSchema input matches z.input", () => {
      expectTypeOf<TupleBrandSchemaCoordInput>().toEqualTypeOf<z.input<typeof TupleBrandSchemaCoordSchema>>();
    });

    it("CoordSchema output matches z.output", () => {
      expectTypeOf<TupleBrandSchemaCoordOutput>().toEqualTypeOf<z.output<typeof TupleBrandSchemaCoordSchema>>();
    });

    it("TagListSchema input matches z.input", () => {
      expectTypeOf<TupleBrandSchemaTagListInput>().toEqualTypeOf<z.input<typeof TupleBrandSchemaTagListSchema>>();
    });

    it("TagListSchema output matches z.output", () => {
      expectTypeOf<TupleBrandSchemaTagListOutput>().toEqualTypeOf<z.output<typeof TupleBrandSchemaTagListSchema>>();
    });

    it("FrozenPairSchema input matches z.input", () => {
      expectTypeOf<TupleBrandSchemaFrozenPairInput>().toEqualTypeOf<z.input<typeof TupleBrandSchemaFrozenPairSchema>>();
    });

    it("FrozenPairSchema output matches z.output", () => {
      expectTypeOf<TupleBrandSchemaFrozenPairOutput>().toEqualTypeOf<z.output<typeof TupleBrandSchemaFrozenPairSchema>>();
    });

    it("HeadedListSchema input matches z.input", () => {
      expectTypeOf<TupleBrandSchemaHeadedListInput>().toEqualTypeOf<z.input<typeof TupleBrandSchemaHeadedListSchema>>();
    });

    it("HeadedListSchema output matches z.output", () => {
      expectTypeOf<TupleBrandSchemaHeadedListOutput>().toEqualTypeOf<z.output<typeof TupleBrandSchemaHeadedListSchema>>();
    });

    it("ShapeSchema input matches z.input", () => {
      expectTypeOf<TupleBrandSchemaShapeInput>().toEqualTypeOf<z.input<typeof TupleBrandSchemaShapeSchema>>();
    });

    it("ShapeSchema output matches z.output", () => {
      expectTypeOf<TupleBrandSchemaShapeOutput>().toEqualTypeOf<z.output<typeof TupleBrandSchemaShapeSchema>>();
    });
  });
});
