// Generated by zinfer - Do not edit manually

import type { BRAND } from "zod";

export type CoordInput = [number, number];

export type CoordOutput = [number, number] & BRAND<"Coord">;

export type TagListInput = string[];

export type TagListOutput = string[] & BRAND<"TagList">;

export type FrozenPairInput = readonly [string, number];

export type FrozenPairOutput = readonly [string, number] & BRAND<"FrozenPair">;

export type HeadedListInput = [string, ...number[]];

export type HeadedListOutput = [string, ...number[]] & BRAND<"HeadedList">;

export type ShapeInput = {
  origin: [number, number];
  size: [number, number];
};

export type ShapeOutput = {
  origin: [number, number] & BRAND<"Coord">;
  size: [number, number];
};
