// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- union-nonexport-member-schema ---
import { ResponseSchema as UnionNonexportMemberSchemaResponseSchema } from "../fixtures/union-nonexport-member-schema";
import type { ResponseInput as UnionNonexportMemberSchemaResponseInput, ResponseOutput as UnionNonexportMemberSchemaResponseOutput } from "./union-nonexport-member-schema";

describe("Type equality tests", () => {
  describe("union-nonexport-member-schema", () => {
    it("ResponseSchema input matches z.input", () => {
      expectTypeOf<UnionNonexportMemberSchemaResponseInput>().toEqualTypeOf<z.input<typeof UnionNonexportMemberSchemaResponseSchema>>();
    });

    it("ResponseSchema output matches z.output", () => {
      expectTypeOf<UnionNonexportMemberSchemaResponseOutput>().toEqualTypeOf<z.output<typeof UnionNonexportMemberSchemaResponseSchema>>();
    });
  });
});
