// Generated by zinfer - Do not edit manually

export type DogInput = {
  kind: "dog";
  name: string;
  breed: string;
};

export type DogOutput = {
  kind: "dog";
  name: string;
  breed: string;
};

export type CatInput = {
  kind: "cat";
  name: string;
  indoor: boolean;
};

export type CatOutput = {
  kind: "cat";
  name: string;
  indoor: boolean;
};

export type BirdInput = {
  kind: "bird";
  name: string;
  canFly: boolean;
};

export type BirdOutput = {
  kind: "bird";
  name: string;
  canFly: boolean;
};

export type PetInput = DogInput | CatInput | BirdInput;

export type PetOutput = DogOutput | CatOutput | BirdOutput;

export type AnimalInput = DogInput | CatInput;

export type AnimalOutput = DogOutput | CatOutput;
