// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- union-ref-schema ---
import { DogSchema as UnionRefSchemaDogSchema, CatSchema as UnionRefSchemaCatSchema, BirdSchema as UnionRefSchemaBirdSchema, PetSchema as UnionRefSchemaPetSchema, AnimalSchema as UnionRefSchemaAnimalSchema } from "../fixtures/union-ref-schema";
import type {
  DogInput as UnionRefSchemaDogInput,
  DogOutput as UnionRefSchemaDogOutput,
  CatInput as UnionRefSchemaCatInput,
  CatOutput as UnionRefSchemaCatOutput,
  BirdInput as UnionRefSchemaBirdInput,
  BirdOutput as UnionRefSchemaBirdOutput,
  PetInput as UnionRefSchemaPetInput,
  PetOutput as UnionRefSchemaPetOutput,
  AnimalInput as UnionRefSchemaAnimalInput,
  AnimalOutput as UnionRefSchemaAnimalOutput,
} from "./union-ref-schema";

describe("Type equality tests", () => {
  describe("union-ref-schema", () => {
    it("DogSchema input matches z.input", () => {
      expectTypeOf<UnionRefSchemaDogInput>().toEqualTypeOf<z.input<typeof UnionRefSchemaDogSchema>>();
    });

    it("DogSchema output matches z.output", () => {
      expectTypeOf<UnionRefSchemaDogOutput>().toEqualTypeOf<z.output<typeof UnionRefSchemaDogSchema>>();
    });

    it("CatSchema input matches z.input", () => {
      expectTypeOf<UnionRefSchemaCatInput>().toEqualTypeOf<z.input<typeof UnionRefSchemaCatSchema>>();
    });

    it("CatSchema output matches z.output", () => {
      expectTypeOf<UnionRefSchemaCatOutput>().toEqualTypeOf<z.output<typeof UnionRefSchemaCatSchema>>();
    });

    it("BirdSchema input matches z.input", () => {
      expectTypeOf<UnionRefSchemaBirdInput>().toEqualTypeOf<z.input<typeof UnionRefSchemaBirdSchema>>();
    });

    it("BirdSchema output matches z.output", () => {
      expectTypeOf<UnionRefSchemaBirdOutput>().toEqualTypeOf<z.output<typeof UnionRefSchemaBirdSchema>>();
    });

    it("PetSchema input matches z.input", () => {
      expectTypeOf<UnionRefSchemaPetInput>().toEqualTypeOf<z.input<typeof UnionRefSchemaPetSchema>>();
    });

    it("PetSchema output matches z.output", () => {
      expectTypeOf<UnionRefSchemaPetOutput>().toEqualTypeOf<z.output<typeof UnionRefSchemaPetSchema>>();
    });

    it("AnimalSchema input matches z.input", () => {
      expectTypeOf<UnionRefSchemaAnimalInput>().toEqualTypeOf<z.input<typeof UnionRefSchemaAnimalSchema>>();
    });

    it("AnimalSchema output matches z.output", () => {
      expectTypeOf<UnionRefSchemaAnimalOutput>().toEqualTypeOf<z.output<typeof UnionRefSchemaAnimalSchema>>();
    });
  });
});
