// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- union-schema ---
import { StatusSchema as UnionSchemaStatusSchema, ResultSchema as UnionSchemaResultSchema, StringOrNumberSchema as UnionSchemaStringOrNumberSchema } from "../fixtures/union-schema";
import type {
  StatusInput as UnionSchemaStatusInput,
  StatusOutput as UnionSchemaStatusOutput,
  ResultInput as UnionSchemaResultInput,
  ResultOutput as UnionSchemaResultOutput,
  StringOrNumberInput as UnionSchemaStringOrNumberInput,
  StringOrNumberOutput as UnionSchemaStringOrNumberOutput,
} from "./union-schema";

describe("Type equality tests", () => {
  describe("union-schema", () => {
    it("StatusSchema input matches z.input", () => {
      expectTypeOf<UnionSchemaStatusInput>().toEqualTypeOf<z.input<typeof UnionSchemaStatusSchema>>();
    });

    it("StatusSchema output matches z.output", () => {
      expectTypeOf<UnionSchemaStatusOutput>().toEqualTypeOf<z.output<typeof UnionSchemaStatusSchema>>();
    });

    it("ResultSchema input matches z.input", () => {
      expectTypeOf<UnionSchemaResultInput>().toEqualTypeOf<z.input<typeof UnionSchemaResultSchema>>();
    });

    it("ResultSchema output matches z.output", () => {
      expectTypeOf<UnionSchemaResultOutput>().toEqualTypeOf<z.output<typeof UnionSchemaResultSchema>>();
    });

    it("StringOrNumberSchema input matches z.input", () => {
      expectTypeOf<UnionSchemaStringOrNumberInput>().toEqualTypeOf<z.input<typeof UnionSchemaStringOrNumberSchema>>();
    });

    it("StringOrNumberSchema output matches z.output", () => {
      expectTypeOf<UnionSchemaStringOrNumberOutput>().toEqualTypeOf<z.output<typeof UnionSchemaStringOrNumberSchema>>();
    });
  });
});
