// Generated by zinfer - Do not edit manually

export type ResponseInput = {
  status: "success";
  data: string;
} | {
  status: "error";
  message: string;
};

export type ResponseOutput = {
  status: "success";
  data: string;
} | {
  status: "error";
  message: string;
};
