// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- utility-types-schema ---
import { PartialUserSchema as UtilityTypesSchemaPartialUserSchema, UserIdNameSchema as UtilityTypesSchemaUserIdNameSchema, UserWithoutEmailSchema as UtilityTypesSchemaUserWithoutEmailSchema, RequiredUserSchema as UtilityTypesSchemaRequiredUserSchema, NestedSchema as UtilityTypesSchemaNestedSchema, DeepPartialNestedSchema as UtilityTypesSchemaDeepPartialNestedSchema } from "../fixtures/utility-types-schema";
import type {
  PartialUserInput as UtilityTypesSchemaPartialUserInput,
  PartialUserOutput as UtilityTypesSchemaPartialUserOutput,
  UserIdNameInput as UtilityTypesSchemaUserIdNameInput,
  UserIdNameOutput as UtilityTypesSchemaUserIdNameOutput,
  UserWithoutEmailInput as UtilityTypesSchemaUserWithoutEmailInput,
  UserWithoutEmailOutput as UtilityTypesSchemaUserWithoutEmailOutput,
  RequiredUserInput as UtilityTypesSchemaRequiredUserInput,
  RequiredUserOutput as UtilityTypesSchemaRequiredUserOutput,
  NestedInput as UtilityTypesSchemaNestedInput,
  NestedOutput as UtilityTypesSchemaNestedOutput,
  DeepPartialNestedInput as UtilityTypesSchemaDeepPartialNestedInput,
  DeepPartialNestedOutput as UtilityTypesSchemaDeepPartialNestedOutput,
} from "./utility-types-schema";

describe("Type equality tests", () => {
  describe("utility-types-schema", () => {
    it("PartialUserSchema input matches z.input", () => {
      expectTypeOf<UtilityTypesSchemaPartialUserInput>().toEqualTypeOf<z.input<typeof UtilityTypesSchemaPartialUserSchema>>();
    });

    it("PartialUserSchema output matches z.output", () => {
      expectTypeOf<UtilityTypesSchemaPartialUserOutput>().toEqualTypeOf<z.output<typeof UtilityTypesSchemaPartialUserSchema>>();
    });

    it("UserIdNameSchema input matches z.input", () => {
      expectTypeOf<UtilityTypesSchemaUserIdNameInput>().toEqualTypeOf<z.input<typeof UtilityTypesSchemaUserIdNameSchema>>();
    });

    it("UserIdNameSchema output matches z.output", () => {
      expectTypeOf<UtilityTypesSchemaUserIdNameOutput>().toEqualTypeOf<z.output<typeof UtilityTypesSchemaUserIdNameSchema>>();
    });

    it("UserWithoutEmailSchema input matches z.input", () => {
      expectTypeOf<UtilityTypesSchemaUserWithoutEmailInput>().toEqualTypeOf<z.input<typeof UtilityTypesSchemaUserWithoutEmailSchema>>();
    });

    it("UserWithoutEmailSchema output matches z.output", () => {
      expectTypeOf<UtilityTypesSchemaUserWithoutEmailOutput>().toEqualTypeOf<z.output<typeof UtilityTypesSchemaUserWithoutEmailSchema>>();
    });

    it("RequiredUserSchema input matches z.input", () => {
      expectTypeOf<UtilityTypesSchemaRequiredUserInput>().toEqualTypeOf<z.input<typeof UtilityTypesSchemaRequiredUserSchema>>();
    });

    it("RequiredUserSchema output matches z.output", () => {
      expectTypeOf<UtilityTypesSchemaRequiredUserOutput>().toEqualTypeOf<z.output<typeof UtilityTypesSchemaRequiredUserSchema>>();
    });

    it("NestedSchema input matches z.input", () => {
      expectTypeOf<UtilityTypesSchemaNestedInput>().toEqualTypeOf<z.input<typeof UtilityTypesSchemaNestedSchema>>();
    });

    it("NestedSchema output matches z.output", () => {
      expectTypeOf<UtilityTypesSchemaNestedOutput>().toEqualTypeOf<z.output<typeof UtilityTypesSchemaNestedSchema>>();
    });

    it("DeepPartialNestedSchema input matches z.input", () => {
      expectTypeOf<UtilityTypesSchemaDeepPartialNestedInput>().toEqualTypeOf<z.input<typeof UtilityTypesSchemaDeepPartialNestedSchema>>();
    });

    it("DeepPartialNestedSchema output matches z.output", () => {
      expectTypeOf<UtilityTypesSchemaDeepPartialNestedOutput>().toEqualTypeOf<z.output<typeof UtilityTypesSchemaDeepPartialNestedSchema>>();
    });
  });
});
