// Generated by zinfer - Do not edit manually

export type EmailInput = string;

export type EmailOutput = string;

export type UrlInput = string;

export type UrlOutput = string;

export type UuidInput = string;

export type UuidOutput = string;

export type Uuidv4Input = string;

export type Uuidv4Output = string;

export type GuidInput = string;

export type GuidOutput = string;

export type NanoidInput = string;

export type NanoidOutput = string;

export type Cuid2Input = string;

export type Cuid2Output = string;

export type UlidInput = string;

export type UlidOutput = string;

export type Ipv4Input = string;

export type Ipv4Output = string;

export type Cidrv4Input = string;

export type Cidrv4Output = string;

export type MacInput = string;

export type MacOutput = string;

export type Base64Input = string;

export type Base64Output = string;

export type JwtInput = string;

export type JwtOutput = string;

export type EmojiInput = string;

export type EmojiOutput = string;

export type HostnameInput = string;

export type HostnameOutput = string;

export type HexInput = string;

export type HexOutput = string;

export type E164Input = string;

export type E164Output = string;

export type HttpUrlInput = string;

export type HttpUrlOutput = string;

export type StringFormatInput = string;

export type StringFormatOutput = string;

export type IsoDateInput = string;

export type IsoDateOutput = string;

export type IsoDateTimeInput = string;

export type IsoDateTimeOutput = string;

export type IntInput = number;

export type IntOutput = number;

export type Int32Input = number;

export type Int32Output = number;

export type Uint32Input = number;

export type Uint32Output = number;

export type Float64Input = number;

export type Float64Output = number;

export type Int64Input = bigint;

export type Int64Output = bigint;

export type NanInput = number;

export type NanOutput = number;

export type StringBoolInput = string;

export type StringBoolOutput = boolean;

export type KeyofInput = "id" | "count";

export type KeyofOutput = "id" | "count";

export type PartialRecordInput = {
  a?: string | undefined;
  b?: string | undefined;
};

export type PartialRecordOutput = {
  a?: string | undefined;
  b?: string | undefined;
};

export type LooseRecordInput = {
  [x: string]: number;
};

export type LooseRecordOutput = {
  [x: string]: number;
};

export type XorInput = {
  a: string;
} | {
  b: number;
};

export type XorOutput = {
  a: string;
} | {
  b: number;
};

export type ReadonlyInput = {
  readonly id: string;
  readonly count: number;
};

export type ReadonlyOutput = {
  readonly id: string;
  readonly count: number;
};

export type NullishInput = string | null | undefined;

export type NullishOutput = string | null | undefined;

export type NonOptionalInput = string;

export type NonOptionalOutput = string;

export type SuccessInput = string;

export type SuccessOutput = boolean;

export type ExactOptionalInput = {
  maybe?: string | undefined;
};

export type ExactOptionalOutput = {
  maybe?: string | undefined;
};

export type CatchInput = number;

export type CatchOutput = number;

export type PrefaultInput = string | undefined;

export type PrefaultOutput = string;

export type PipeInput = string;

export type PipeOutput = number;

export type CodecInput = string;

export type CodecOutput = number;

export type TransformInput = string;

export type TransformOutput = number;

export type InvertCodecInput = number;

export type InvertCodecOutput = string;
