// Generated by zinfer - Do not edit manually

export type DeepPartialNestedInput = {
  user?: {
    id?: string | undefined;
    name?: string | undefined;
    email?: string | undefined;
    age?: number | undefined;
  } | undefined;
  settings?: {
    theme?: string | undefined;
    notifications?: boolean | undefined;
  } | undefined;
};

export type DeepPartialNestedOutput = {
  user?: {
    id?: string | undefined;
    name?: string | undefined;
    email?: string | undefined;
    age?: number | undefined;
  } | undefined;
  settings?: {
    theme?: string | undefined;
    notifications?: boolean | undefined;
  } | undefined;
};

export type NumberFromStringInputInput = string;

export type NumberFromStringInputOutput = string;

export type NumberFromStringOutputInput = number;

export type NumberFromStringOutputOutput = number;
