// Generated by vinfer - Do not edit manually

export type AnnotatedHolderInput = {
  node: {
    kind: string;
    meta: {
      required?: boolean | undefined;
      label?: string | undefined;
    };
  };
};

export type AnnotatedHolderOutput = {
  node: {
    kind: string;
    meta: {
      required?: boolean | undefined;
      label?: string | undefined;
    };
  };
};

export type LiteralUndefinedInput = {
  label: "a | undefined | undefined";
};

export type LiteralUndefinedOutput = {
  label: "a | undefined | undefined";
};

export type AnnotatedNodeInput = {
  kind: string;
  meta: import("../fixtures/annotated-inline-types").AnnotatedMeta;
};

export type AnnotatedNodeOutput = {
  kind: string;
  meta: import("../fixtures/annotated-inline-types").AnnotatedMeta;
};
