// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- annotated-inline-schema ---
import { AnnotatedHolderSchema as AnnotatedInlineSchemaAnnotatedHolderSchema, LiteralUndefinedSchema as AnnotatedInlineSchemaLiteralUndefinedSchema, AnnotatedNodeSchema as AnnotatedInlineSchemaAnnotatedNodeSchema } from "../fixtures/annotated-inline-schema";
import type {
  AnnotatedHolderInput as AnnotatedInlineSchemaAnnotatedHolderInput,
  AnnotatedHolderOutput as AnnotatedInlineSchemaAnnotatedHolderOutput,
  LiteralUndefinedInput as AnnotatedInlineSchemaLiteralUndefinedInput,
  LiteralUndefinedOutput as AnnotatedInlineSchemaLiteralUndefinedOutput,
  AnnotatedNodeInput as AnnotatedInlineSchemaAnnotatedNodeInput,
  AnnotatedNodeOutput as AnnotatedInlineSchemaAnnotatedNodeOutput,
} from "./annotated-inline-schema";

describe("Type equality tests", () => {
  describe("annotated-inline-schema", () => {
    it("AnnotatedHolderSchema input matches v.InferInput", () => {
      expectTypeOf<AnnotatedInlineSchemaAnnotatedHolderInput>().toEqualTypeOf<v.InferInput<typeof AnnotatedInlineSchemaAnnotatedHolderSchema>>();
    });

    it("AnnotatedHolderSchema output matches v.InferOutput", () => {
      expectTypeOf<AnnotatedInlineSchemaAnnotatedHolderOutput>().toEqualTypeOf<v.InferOutput<typeof AnnotatedInlineSchemaAnnotatedHolderSchema>>();
    });

    it("LiteralUndefinedSchema input matches v.InferInput", () => {
      expectTypeOf<AnnotatedInlineSchemaLiteralUndefinedInput>().toEqualTypeOf<v.InferInput<typeof AnnotatedInlineSchemaLiteralUndefinedSchema>>();
    });

    it("LiteralUndefinedSchema output matches v.InferOutput", () => {
      expectTypeOf<AnnotatedInlineSchemaLiteralUndefinedOutput>().toEqualTypeOf<v.InferOutput<typeof AnnotatedInlineSchemaLiteralUndefinedSchema>>();
    });

    it("AnnotatedNodeSchema input matches v.InferInput", () => {
      expectTypeOf<AnnotatedInlineSchemaAnnotatedNodeInput>().toEqualTypeOf<v.InferInput<typeof AnnotatedInlineSchemaAnnotatedNodeSchema>>();
    });

    it("AnnotatedNodeSchema output matches v.InferOutput", () => {
      expectTypeOf<AnnotatedInlineSchemaAnnotatedNodeOutput>().toEqualTypeOf<v.InferOutput<typeof AnnotatedInlineSchemaAnnotatedNodeSchema>>();
    });
  });
});
