// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- array-readonly-schema ---
import { ListSchema as ArrayReadonlySchemaListSchema, FrozenListSchema as ArrayReadonlySchemaFrozenListSchema } from "../fixtures/array-readonly-schema";
import type {
  ListInput as ArrayReadonlySchemaListInput,
  ListOutput as ArrayReadonlySchemaListOutput,
  FrozenListInput as ArrayReadonlySchemaFrozenListInput,
  FrozenListOutput as ArrayReadonlySchemaFrozenListOutput,
} from "./array-readonly-schema";

describe("Type equality tests", () => {
  describe("array-readonly-schema", () => {
    it("ListSchema input matches v.InferInput", () => {
      expectTypeOf<ArrayReadonlySchemaListInput>().toEqualTypeOf<v.InferInput<typeof ArrayReadonlySchemaListSchema>>();
    });

    it("ListSchema output matches v.InferOutput", () => {
      expectTypeOf<ArrayReadonlySchemaListOutput>().toEqualTypeOf<v.InferOutput<typeof ArrayReadonlySchemaListSchema>>();
    });

    it("FrozenListSchema input matches v.InferInput", () => {
      expectTypeOf<ArrayReadonlySchemaFrozenListInput>().toEqualTypeOf<v.InferInput<typeof ArrayReadonlySchemaFrozenListSchema>>();
    });

    it("FrozenListSchema output matches v.InferOutput", () => {
      expectTypeOf<ArrayReadonlySchemaFrozenListOutput>().toEqualTypeOf<v.InferOutput<typeof ArrayReadonlySchemaFrozenListSchema>>();
    });
  });
});
