// Generated by vinfer - Do not edit manually

export type ListInput = {
  items: string[];
  nested: number[][];
};

export type ListOutput = {
  items: string[];
  nested: number[][];
};

export type FrozenListInput = {
  items: string[];
};

export type FrozenListOutput = {
  readonly items: readonly string[];
};
