// Generated by vinfer - Do not edit manually

export type AsyncAddressInput = {
  street: string;
};

export type AsyncAddressOutput = {
  street: string;
};

export type AsyncUserInput = {
  name: string;
  address: AsyncAddressInput;
  addresses: AsyncAddressInput[];
  nickname?: string | undefined;
  age: string;
};

export type AsyncUserOutput = {
  name: string;
  address: AsyncAddressOutput;
  addresses: AsyncAddressOutput[];
  nickname?: string | undefined;
  age: number;
};
