// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- async-schema ---
import { AsyncAddressSchema as AsyncSchemaAsyncAddressSchema, AsyncUserSchema as AsyncSchemaAsyncUserSchema } from "../fixtures/async-schema";
import type {
  AsyncAddressInput as AsyncSchemaAsyncAddressInput,
  AsyncAddressOutput as AsyncSchemaAsyncAddressOutput,
  AsyncUserInput as AsyncSchemaAsyncUserInput,
  AsyncUserOutput as AsyncSchemaAsyncUserOutput,
} from "./async-schema";

describe("Type equality tests", () => {
  describe("async-schema", () => {
    it("AsyncAddressSchema input matches v.InferInput", () => {
      expectTypeOf<AsyncSchemaAsyncAddressInput>().toEqualTypeOf<v.InferInput<typeof AsyncSchemaAsyncAddressSchema>>();
    });

    it("AsyncAddressSchema output matches v.InferOutput", () => {
      expectTypeOf<AsyncSchemaAsyncAddressOutput>().toEqualTypeOf<v.InferOutput<typeof AsyncSchemaAsyncAddressSchema>>();
    });

    it("AsyncUserSchema input matches v.InferInput", () => {
      expectTypeOf<AsyncSchemaAsyncUserInput>().toEqualTypeOf<v.InferInput<typeof AsyncSchemaAsyncUserSchema>>();
    });

    it("AsyncUserSchema output matches v.InferOutput", () => {
      expectTypeOf<AsyncSchemaAsyncUserOutput>().toEqualTypeOf<v.InferOutput<typeof AsyncSchemaAsyncUserSchema>>();
    });
  });
});
