// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- basic-schema ---
import { UserSchema as BasicSchemaUserSchema } from "../fixtures/basic-schema";
import type { UserInput as BasicSchemaUserInput, UserOutput as BasicSchemaUserOutput } from "./basic-schema";

describe("Type equality tests", () => {
  describe("basic-schema", () => {
    it("UserSchema input matches v.InferInput", () => {
      expectTypeOf<BasicSchemaUserInput>().toEqualTypeOf<v.InferInput<typeof BasicSchemaUserSchema>>();
    });

    it("UserSchema output matches v.InferOutput", () => {
      expectTypeOf<BasicSchemaUserOutput>().toEqualTypeOf<v.InferOutput<typeof BasicSchemaUserSchema>>();
    });
  });
});
