// Generated by vinfer - Do not edit manually

export type UserInput = {
  id: string;
  name: string;
  age?: number | undefined;
};

export type UserOutput = {
  id: string;
  name: string;
  age?: number | undefined;
};
