// Generated by vinfer - Do not edit manually

import type { Brand, Flavor } from "valibot";

export type UserIdInput = string;

export type UserIdOutput = string & Brand<"UserId">;

export type UserInput = {
  id: string;
  name: string;
  email: string;
  score: number;
  tags: string[];
  optionalTag?: string | undefined;
  lookup: {
    [x: string]: string;
  };
};

export type UserOutput = {
  id: string & Brand<"UserId">;
  name: string;
  email: string;
  score: number & Brand<"Score">;
  tags: (string & Brand<"Tag">)[];
  optionalTag?: (string & Brand<"Tag">) | undefined;
  lookup: {
    [x: string]: string & Brand<"Tag">;
  };
};

export type EmailInput = string;

export type EmailOutput = string & Flavor<"Email">;

export type BrandedUserInput = {
  id: string;
  name: string;
};

export type BrandedUserOutput = { id: string; name: string; } & Brand<"BrandedUser">;
