// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- brand-schema ---
import { UserIdSchema as BrandSchemaUserIdSchema, UserSchema as BrandSchemaUserSchema, EmailSchema as BrandSchemaEmailSchema } from "../fixtures/brand-schema";
import type {
  UserIdInput as BrandSchemaUserIdInput,
  UserIdOutput as BrandSchemaUserIdOutput,
  UserInput as BrandSchemaUserInput,
  UserOutput as BrandSchemaUserOutput,
  EmailInput as BrandSchemaEmailInput,
  EmailOutput as BrandSchemaEmailOutput,
} from "./brand-schema";

describe("Type equality tests", () => {
  describe("brand-schema", () => {
    it("UserIdSchema input matches v.InferInput", () => {
      expectTypeOf<BrandSchemaUserIdInput>().toEqualTypeOf<v.InferInput<typeof BrandSchemaUserIdSchema>>();
    });

    it("UserIdSchema output matches v.InferOutput", () => {
      expectTypeOf<BrandSchemaUserIdOutput>().toEqualTypeOf<v.InferOutput<typeof BrandSchemaUserIdSchema>>();
    });

    it("UserSchema input matches v.InferInput", () => {
      expectTypeOf<BrandSchemaUserInput>().toEqualTypeOf<v.InferInput<typeof BrandSchemaUserSchema>>();
    });

    it("UserSchema output matches v.InferOutput", () => {
      expectTypeOf<BrandSchemaUserOutput>().toEqualTypeOf<v.InferOutput<typeof BrandSchemaUserSchema>>();
    });

    it("EmailSchema input matches v.InferInput", () => {
      expectTypeOf<BrandSchemaEmailInput>().toEqualTypeOf<v.InferInput<typeof BrandSchemaEmailSchema>>();
    });

    it("EmailSchema output matches v.InferOutput", () => {
      expectTypeOf<BrandSchemaEmailOutput>().toEqualTypeOf<v.InferOutput<typeof BrandSchemaEmailSchema>>();
    });
  });
});
