// Generated by vinfer - Do not edit manually

declare const __brand: unique symbol;
declare const __flavor: unique symbol;

export type UserIdInput = string;

export type UserIdOutput = string & { readonly [__brand]: "UserId" };

export type UserInput = {
  id: string;
  name: string;
  email: string;
  score: number;
  tags: string[];
  optionalTag?: string | undefined;
  lookup: {
    [x: string]: string;
  };
};

export type UserOutput = {
  id: string & {
    readonly [__brand]: "UserId"
  };
  name: string;
  email: string;
  score: number & {
    readonly [__brand]: "Score"
  };
  tags: (string & {
    readonly [__brand]: "Tag"
  })[];
  optionalTag?: (string & {
    readonly [__brand]: "Tag"
  }) | undefined;
  lookup: {
    [x: string]: string & {
      readonly [__brand]: "Tag"
    };
  };
};

export type EmailInput = string;

export type EmailOutput = string & { readonly [__flavor]?: "Email" };

export type BrandedUserInput = {
  id: string;
  name: string;
};

export type BrandedUserOutput = {
  id: string;
  name: string;
} & {
  readonly [__brand]: "BrandedUser"
};
