// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- collection-schema ---
import { EntrySchema as CollectionSchemaEntrySchema, CollectionSchema as CollectionSchemaCollectionSchema } from "../fixtures/collection-schema";
import type {
  EntryInput as CollectionSchemaEntryInput,
  EntryOutput as CollectionSchemaEntryOutput,
  CollectionInput as CollectionSchemaCollectionInput,
  CollectionOutput as CollectionSchemaCollectionOutput,
} from "./collection-schema";

describe("Type equality tests", () => {
  describe("collection-schema", () => {
    it("EntrySchema input matches v.InferInput", () => {
      expectTypeOf<CollectionSchemaEntryInput>().toEqualTypeOf<v.InferInput<typeof CollectionSchemaEntrySchema>>();
    });

    it("EntrySchema output matches v.InferOutput", () => {
      expectTypeOf<CollectionSchemaEntryOutput>().toEqualTypeOf<v.InferOutput<typeof CollectionSchemaEntrySchema>>();
    });

    it("CollectionSchema input matches v.InferInput", () => {
      expectTypeOf<CollectionSchemaCollectionInput>().toEqualTypeOf<v.InferInput<typeof CollectionSchemaCollectionSchema>>();
    });

    it("CollectionSchema output matches v.InferOutput", () => {
      expectTypeOf<CollectionSchemaCollectionOutput>().toEqualTypeOf<v.InferOutput<typeof CollectionSchemaCollectionSchema>>();
    });
  });
});
