// Generated by vinfer - Do not edit manually

export type EntryInput = {
  id: string;
  label: string;
};

export type EntryOutput = {
  id: string;
  label: string;
};

export type CollectionInput = {
  byId: {
    [x: string]: EntryInput;
  };
  labels: Map<string, number>;
  ids: Set<string>;
  matrix: number[][];
  timestamps: Date[];
};

export type CollectionOutput = {
  byId: {
    [x: string]: EntryOutput;
  };
  labels: Map<string, number>;
  ids: Set<string>;
  matrix: number[][];
  timestamps: Date[];
};
