// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- cross-ref-schema ---
import { AddressSchema as CrossRefSchemaAddressSchema, UserSchema as CrossRefSchemaUserSchema, CompanySchema as CrossRefSchemaCompanySchema } from "../fixtures/cross-ref-schema";
import type {
  AddressInput as CrossRefSchemaAddressInput,
  AddressOutput as CrossRefSchemaAddressOutput,
  UserInput as CrossRefSchemaUserInput,
  UserOutput as CrossRefSchemaUserOutput,
  CompanyInput as CrossRefSchemaCompanyInput,
  CompanyOutput as CrossRefSchemaCompanyOutput,
} from "./cross-ref-schema";

describe("Type equality tests", () => {
  describe("cross-ref-schema", () => {
    it("AddressSchema input matches v.InferInput", () => {
      expectTypeOf<CrossRefSchemaAddressInput>().toEqualTypeOf<v.InferInput<typeof CrossRefSchemaAddressSchema>>();
    });

    it("AddressSchema output matches v.InferOutput", () => {
      expectTypeOf<CrossRefSchemaAddressOutput>().toEqualTypeOf<v.InferOutput<typeof CrossRefSchemaAddressSchema>>();
    });

    it("UserSchema input matches v.InferInput", () => {
      expectTypeOf<CrossRefSchemaUserInput>().toEqualTypeOf<v.InferInput<typeof CrossRefSchemaUserSchema>>();
    });

    it("UserSchema output matches v.InferOutput", () => {
      expectTypeOf<CrossRefSchemaUserOutput>().toEqualTypeOf<v.InferOutput<typeof CrossRefSchemaUserSchema>>();
    });

    it("CompanySchema input matches v.InferInput", () => {
      expectTypeOf<CrossRefSchemaCompanyInput>().toEqualTypeOf<v.InferInput<typeof CrossRefSchemaCompanySchema>>();
    });

    it("CompanySchema output matches v.InferOutput", () => {
      expectTypeOf<CrossRefSchemaCompanyOutput>().toEqualTypeOf<v.InferOutput<typeof CrossRefSchemaCompanySchema>>();
    });
  });
});
