// Generated by vinfer - Do not edit manually

export type JsonValueInput = string | number | boolean | JsonValueInput[] | { [key: string]: JsonValueInput; } | null;

export type JsonValueOutput = string | number | boolean | JsonValueOutput[] | { [key: string]: JsonValueOutput; } | null;

export type FunctionOperationInput = {
  kind: "function";
  name: string;
};

export type FunctionOperationOutput = {
  kind: "function";
  name: string;
};

export type WorkflowOperationInput = {
  kind: "workflow";
  args?: JsonValueInput;
};

export type WorkflowOperationOutput = {
  kind: "workflow";
  args?: JsonValueOutput;
};

export type OperationInput = FunctionOperationInput | WorkflowOperationInput;

export type OperationOutput = FunctionOperationOutput | WorkflowOperationOutput;

export type ExecutorInput = {
  name: string;
  operation: OperationInput;
  fallback?: WorkflowOperationInput;
};

export type ExecutorOutput = {
  name: string;
  operation: OperationOutput;
  fallback?: WorkflowOperationOutput;
};
