// Generated by vinfer - Do not edit manually

export type UserInput = {
  id: string;
  name: string;
  email: string;
  age?: number | undefined;
  role: "admin" | "user" | "guest";
};

export type UserOutput = {
  id: string;
  name: string;
  email: string;
  age?: number | undefined;
  role: "admin" | "user" | "guest";
};

export type AddressInput = {
  street: string;
  city: string;
  country: string;
  zipCode?: string | undefined;
};

export type AddressOutput = {
  street: string;
  city: string;
  country: string;
  zipCode?: string | undefined;
};

export type ProfileInput = {
  user: UserInput;
  address?: AddressInput;
  tags: string[];
};

export type ProfileOutput = {
  user: UserOutput;
  address?: AddressOutput;
  tags: string[];
};

export type MetadataDescribedInput = {
  token: string;
};

export type MetadataDescribedOutput = {
  token: string;
};
