// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- described-ref-schema ---
import { JsonValueSchema as DescribedRefSchemaJsonValueSchema, FunctionOperationSchema as DescribedRefSchemaFunctionOperationSchema, WorkflowOperationSchema as DescribedRefSchemaWorkflowOperationSchema, OperationSchema as DescribedRefSchemaOperationSchema, ExecutorSchema as DescribedRefSchemaExecutorSchema } from "../fixtures/described-ref-schema";
import type {
  JsonValueInput as DescribedRefSchemaJsonValueInput,
  JsonValueOutput as DescribedRefSchemaJsonValueOutput,
  FunctionOperationInput as DescribedRefSchemaFunctionOperationInput,
  FunctionOperationOutput as DescribedRefSchemaFunctionOperationOutput,
  WorkflowOperationInput as DescribedRefSchemaWorkflowOperationInput,
  WorkflowOperationOutput as DescribedRefSchemaWorkflowOperationOutput,
  OperationInput as DescribedRefSchemaOperationInput,
  OperationOutput as DescribedRefSchemaOperationOutput,
  ExecutorInput as DescribedRefSchemaExecutorInput,
  ExecutorOutput as DescribedRefSchemaExecutorOutput,
} from "./described-ref-schema";

describe("Type equality tests", () => {
  describe("described-ref-schema", () => {
    it("JsonValueSchema input matches v.InferInput", () => {
      expectTypeOf<DescribedRefSchemaJsonValueInput>().toEqualTypeOf<v.InferInput<typeof DescribedRefSchemaJsonValueSchema>>();
    });

    it("JsonValueSchema output matches v.InferOutput", () => {
      expectTypeOf<DescribedRefSchemaJsonValueOutput>().toEqualTypeOf<v.InferOutput<typeof DescribedRefSchemaJsonValueSchema>>();
    });

    it("FunctionOperationSchema input matches v.InferInput", () => {
      expectTypeOf<DescribedRefSchemaFunctionOperationInput>().toEqualTypeOf<v.InferInput<typeof DescribedRefSchemaFunctionOperationSchema>>();
    });

    it("FunctionOperationSchema output matches v.InferOutput", () => {
      expectTypeOf<DescribedRefSchemaFunctionOperationOutput>().toEqualTypeOf<v.InferOutput<typeof DescribedRefSchemaFunctionOperationSchema>>();
    });

    it("WorkflowOperationSchema input matches v.InferInput", () => {
      expectTypeOf<DescribedRefSchemaWorkflowOperationInput>().toEqualTypeOf<v.InferInput<typeof DescribedRefSchemaWorkflowOperationSchema>>();
    });

    it("WorkflowOperationSchema output matches v.InferOutput", () => {
      expectTypeOf<DescribedRefSchemaWorkflowOperationOutput>().toEqualTypeOf<v.InferOutput<typeof DescribedRefSchemaWorkflowOperationSchema>>();
    });

    it("OperationSchema input matches v.InferInput", () => {
      expectTypeOf<DescribedRefSchemaOperationInput>().toEqualTypeOf<v.InferInput<typeof DescribedRefSchemaOperationSchema>>();
    });

    it("OperationSchema output matches v.InferOutput", () => {
      expectTypeOf<DescribedRefSchemaOperationOutput>().toEqualTypeOf<v.InferOutput<typeof DescribedRefSchemaOperationSchema>>();
    });

    it("ExecutorSchema input matches v.InferInput", () => {
      expectTypeOf<DescribedRefSchemaExecutorInput>().toEqualTypeOf<v.InferInput<typeof DescribedRefSchemaExecutorSchema>>();
    });

    it("ExecutorSchema output matches v.InferOutput", () => {
      expectTypeOf<DescribedRefSchemaExecutorOutput>().toEqualTypeOf<v.InferOutput<typeof DescribedRefSchemaExecutorSchema>>();
    });
  });
});
