// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- described-schema ---
import { UserSchema as DescribedSchemaUserSchema, AddressSchema as DescribedSchemaAddressSchema, ProfileSchema as DescribedSchemaProfileSchema, MetadataDescribedSchema as DescribedSchemaMetadataDescribedSchema } from "../fixtures/described-schema";
import type {
  UserInput as DescribedSchemaUserInput,
  UserOutput as DescribedSchemaUserOutput,
  AddressInput as DescribedSchemaAddressInput,
  AddressOutput as DescribedSchemaAddressOutput,
  ProfileInput as DescribedSchemaProfileInput,
  ProfileOutput as DescribedSchemaProfileOutput,
  MetadataDescribedInput as DescribedSchemaMetadataDescribedInput,
  MetadataDescribedOutput as DescribedSchemaMetadataDescribedOutput,
} from "./described-schema";

describe("Type equality tests", () => {
  describe("described-schema", () => {
    it("UserSchema input matches v.InferInput", () => {
      expectTypeOf<DescribedSchemaUserInput>().toEqualTypeOf<v.InferInput<typeof DescribedSchemaUserSchema>>();
    });

    it("UserSchema output matches v.InferOutput", () => {
      expectTypeOf<DescribedSchemaUserOutput>().toEqualTypeOf<v.InferOutput<typeof DescribedSchemaUserSchema>>();
    });

    it("AddressSchema input matches v.InferInput", () => {
      expectTypeOf<DescribedSchemaAddressInput>().toEqualTypeOf<v.InferInput<typeof DescribedSchemaAddressSchema>>();
    });

    it("AddressSchema output matches v.InferOutput", () => {
      expectTypeOf<DescribedSchemaAddressOutput>().toEqualTypeOf<v.InferOutput<typeof DescribedSchemaAddressSchema>>();
    });

    it("ProfileSchema input matches v.InferInput", () => {
      expectTypeOf<DescribedSchemaProfileInput>().toEqualTypeOf<v.InferInput<typeof DescribedSchemaProfileSchema>>();
    });

    it("ProfileSchema output matches v.InferOutput", () => {
      expectTypeOf<DescribedSchemaProfileOutput>().toEqualTypeOf<v.InferOutput<typeof DescribedSchemaProfileSchema>>();
    });

    it("MetadataDescribedSchema input matches v.InferInput", () => {
      expectTypeOf<DescribedSchemaMetadataDescribedInput>().toEqualTypeOf<v.InferInput<typeof DescribedSchemaMetadataDescribedSchema>>();
    });

    it("MetadataDescribedSchema output matches v.InferOutput", () => {
      expectTypeOf<DescribedSchemaMetadataDescribedOutput>().toEqualTypeOf<v.InferOutput<typeof DescribedSchemaMetadataDescribedSchema>>();
    });
  });
});
