// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- enum-schema ---
import { DirectionSchema as EnumSchemaDirectionSchema, ColorSchema as EnumSchemaColorSchema, PrioritySchema as EnumSchemaPrioritySchema } from "../fixtures/enum-schema";
import type {
  DirectionInput as EnumSchemaDirectionInput,
  DirectionOutput as EnumSchemaDirectionOutput,
  ColorInput as EnumSchemaColorInput,
  ColorOutput as EnumSchemaColorOutput,
  PriorityInput as EnumSchemaPriorityInput,
  PriorityOutput as EnumSchemaPriorityOutput,
} from "./enum-schema";

describe("Type equality tests", () => {
  describe("enum-schema", () => {
    it("DirectionSchema input matches v.InferInput", () => {
      expectTypeOf<EnumSchemaDirectionInput>().toEqualTypeOf<v.InferInput<typeof EnumSchemaDirectionSchema>>();
    });

    it("DirectionSchema output matches v.InferOutput", () => {
      expectTypeOf<EnumSchemaDirectionOutput>().toEqualTypeOf<v.InferOutput<typeof EnumSchemaDirectionSchema>>();
    });

    it("ColorSchema input matches v.InferInput", () => {
      expectTypeOf<EnumSchemaColorInput>().toEqualTypeOf<v.InferInput<typeof EnumSchemaColorSchema>>();
    });

    it("ColorSchema output matches v.InferOutput", () => {
      expectTypeOf<EnumSchemaColorOutput>().toEqualTypeOf<v.InferOutput<typeof EnumSchemaColorSchema>>();
    });

    it("PrioritySchema input matches v.InferInput", () => {
      expectTypeOf<EnumSchemaPriorityInput>().toEqualTypeOf<v.InferInput<typeof EnumSchemaPrioritySchema>>();
    });

    it("PrioritySchema output matches v.InferOutput", () => {
      expectTypeOf<EnumSchemaPriorityOutput>().toEqualTypeOf<v.InferOutput<typeof EnumSchemaPrioritySchema>>();
    });
  });
});
