// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- intersection-schema ---
import { EntitySchema as IntersectionSchemaEntitySchema, MergedSchema as IntersectionSchemaMergedSchema, AndSchema as IntersectionSchemaAndSchema } from "../fixtures/intersection-schema";
import type {
  EntityInput as IntersectionSchemaEntityInput,
  EntityOutput as IntersectionSchemaEntityOutput,
  MergedInput as IntersectionSchemaMergedInput,
  MergedOutput as IntersectionSchemaMergedOutput,
  AndInput as IntersectionSchemaAndInput,
  AndOutput as IntersectionSchemaAndOutput,
} from "./intersection-schema";

describe("Type equality tests", () => {
  describe("intersection-schema", () => {
    it("EntitySchema input matches v.InferInput", () => {
      expectTypeOf<IntersectionSchemaEntityInput>().toEqualTypeOf<v.InferInput<typeof IntersectionSchemaEntitySchema>>();
    });

    it("EntitySchema output matches v.InferOutput", () => {
      expectTypeOf<IntersectionSchemaEntityOutput>().toEqualTypeOf<v.InferOutput<typeof IntersectionSchemaEntitySchema>>();
    });

    it("MergedSchema input matches v.InferInput", () => {
      expectTypeOf<IntersectionSchemaMergedInput>().toEqualTypeOf<v.InferInput<typeof IntersectionSchemaMergedSchema>>();
    });

    it("MergedSchema output matches v.InferOutput", () => {
      expectTypeOf<IntersectionSchemaMergedOutput>().toEqualTypeOf<v.InferOutput<typeof IntersectionSchemaMergedSchema>>();
    });

    it("AndSchema input matches v.InferInput", () => {
      expectTypeOf<IntersectionSchemaAndInput>().toEqualTypeOf<v.InferInput<typeof IntersectionSchemaAndSchema>>();
    });

    it("AndSchema output matches v.InferOutput", () => {
      expectTypeOf<IntersectionSchemaAndOutput>().toEqualTypeOf<v.InferOutput<typeof IntersectionSchemaAndSchema>>();
    });
  });
});
