// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- lazy-schema ---
import { CategorySchema as LazySchemaCategorySchema, TreeNodeSchema as LazySchemaTreeNodeSchema, JsonValueSchema as LazySchemaJsonValueSchema } from "../fixtures/lazy-schema";
import type {
  CategoryInput as LazySchemaCategoryInput,
  CategoryOutput as LazySchemaCategoryOutput,
  TreeNodeInput as LazySchemaTreeNodeInput,
  TreeNodeOutput as LazySchemaTreeNodeOutput,
  JsonValueInput as LazySchemaJsonValueInput,
  JsonValueOutput as LazySchemaJsonValueOutput,
} from "./lazy-schema";

describe("Type equality tests", () => {
  describe("lazy-schema", () => {
    it("CategorySchema input matches v.InferInput", () => {
      expectTypeOf<LazySchemaCategoryInput>().toEqualTypeOf<v.InferInput<typeof LazySchemaCategorySchema>>();
    });

    it("CategorySchema output matches v.InferOutput", () => {
      expectTypeOf<LazySchemaCategoryOutput>().toEqualTypeOf<v.InferOutput<typeof LazySchemaCategorySchema>>();
    });

    it("TreeNodeSchema input matches v.InferInput", () => {
      expectTypeOf<LazySchemaTreeNodeInput>().toEqualTypeOf<v.InferInput<typeof LazySchemaTreeNodeSchema>>();
    });

    it("TreeNodeSchema output matches v.InferOutput", () => {
      expectTypeOf<LazySchemaTreeNodeOutput>().toEqualTypeOf<v.InferOutput<typeof LazySchemaTreeNodeSchema>>();
    });

    it("JsonValueSchema input matches v.InferInput", () => {
      expectTypeOf<LazySchemaJsonValueInput>().toEqualTypeOf<v.InferInput<typeof LazySchemaJsonValueSchema>>();
    });

    it("JsonValueSchema output matches v.InferOutput", () => {
      expectTypeOf<LazySchemaJsonValueOutput>().toEqualTypeOf<v.InferOutput<typeof LazySchemaJsonValueSchema>>();
    });
  });
});
