// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- mergeSame-multi-schema ---
import { AddressSchema as MergeSameMultiSchemaAddressSchema, PersonSchema as MergeSameMultiSchemaPersonSchema } from "../fixtures/mergeSame-multi-schema";
import type {
  AddressInput as MergeSameMultiSchemaAddressInput,
  AddressOutput as MergeSameMultiSchemaAddressOutput,
  PersonInput as MergeSameMultiSchemaPersonInput,
  PersonOutput as MergeSameMultiSchemaPersonOutput,
} from "./mergeSame-multi-schema";

describe("Type equality tests", () => {
  describe("mergeSame-multi-schema", () => {
    it("AddressSchema input matches v.InferInput", () => {
      expectTypeOf<MergeSameMultiSchemaAddressInput>().toEqualTypeOf<v.InferInput<typeof MergeSameMultiSchemaAddressSchema>>();
    });

    it("AddressSchema output matches v.InferOutput", () => {
      expectTypeOf<MergeSameMultiSchemaAddressOutput>().toEqualTypeOf<v.InferOutput<typeof MergeSameMultiSchemaAddressSchema>>();
    });

    it("PersonSchema input matches v.InferInput", () => {
      expectTypeOf<MergeSameMultiSchemaPersonInput>().toEqualTypeOf<v.InferInput<typeof MergeSameMultiSchemaPersonSchema>>();
    });

    it("PersonSchema output matches v.InferOutput", () => {
      expectTypeOf<MergeSameMultiSchemaPersonOutput>().toEqualTypeOf<v.InferOutput<typeof MergeSameMultiSchemaPersonSchema>>();
    });
  });
});
