// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- mixed-export-schema ---
import { PublicDataSchema as MixedExportSchemaPublicDataSchema } from "../fixtures/mixed-export-schema";
import type { PublicDataInput as MixedExportSchemaPublicDataInput, PublicDataOutput as MixedExportSchemaPublicDataOutput } from "./mixed-export-schema";

describe("Type equality tests", () => {
  describe("mixed-export-schema", () => {
    it("PublicDataSchema input matches v.InferInput", () => {
      expectTypeOf<MixedExportSchemaPublicDataInput>().toEqualTypeOf<v.InferInput<typeof MixedExportSchemaPublicDataSchema>>();
    });

    it("PublicDataSchema output matches v.InferOutput", () => {
      expectTypeOf<MixedExportSchemaPublicDataOutput>().toEqualTypeOf<v.InferOutput<typeof MixedExportSchemaPublicDataSchema>>();
    });
  });
});
