// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- mixed-union-reference-common ---
import { functionSchema as MixedUnionReferenceCommonfunctionSchema } from "../fixtures/mixed-union-reference-common";
import type { functionInput as MixedUnionReferenceCommonfunctionInput, functionOutput as MixedUnionReferenceCommonfunctionOutput } from "./mixed-union-reference-common";

describe("Type equality tests", () => {
  describe("mixed-union-reference-common", () => {
    it("functionSchema input matches v.InferInput", () => {
      expectTypeOf<MixedUnionReferenceCommonfunctionInput>().toEqualTypeOf<v.InferInput<typeof MixedUnionReferenceCommonfunctionSchema>>();
    });

    it("functionSchema output matches v.InferOutput", () => {
      expectTypeOf<MixedUnionReferenceCommonfunctionOutput>().toEqualTypeOf<v.InferOutput<typeof MixedUnionReferenceCommonfunctionSchema>>();
    });
  });
});
