// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- multi-schema ---
import { UserSchema as MultiSchemaUserSchema, PostSchema as MultiSchemaPostSchema, CommentSchema as MultiSchemaCommentSchema, DateStringSchema as MultiSchemaDateStringSchema, AliasedSchema as MultiSchemaAliasedSchema } from "../fixtures/multi-schema";
import type {
  UserInput as MultiSchemaUserInput,
  UserOutput as MultiSchemaUserOutput,
  PostInput as MultiSchemaPostInput,
  PostOutput as MultiSchemaPostOutput,
  CommentInput as MultiSchemaCommentInput,
  CommentOutput as MultiSchemaCommentOutput,
  DateStringInput as MultiSchemaDateStringInput,
  DateStringOutput as MultiSchemaDateStringOutput,
  AliasedInput as MultiSchemaAliasedInput,
  AliasedOutput as MultiSchemaAliasedOutput,
} from "./multi-schema";

describe("Type equality tests", () => {
  describe("multi-schema", () => {
    it("UserSchema input matches v.InferInput", () => {
      expectTypeOf<MultiSchemaUserInput>().toEqualTypeOf<v.InferInput<typeof MultiSchemaUserSchema>>();
    });

    it("UserSchema output matches v.InferOutput", () => {
      expectTypeOf<MultiSchemaUserOutput>().toEqualTypeOf<v.InferOutput<typeof MultiSchemaUserSchema>>();
    });

    it("PostSchema input matches v.InferInput", () => {
      expectTypeOf<MultiSchemaPostInput>().toEqualTypeOf<v.InferInput<typeof MultiSchemaPostSchema>>();
    });

    it("PostSchema output matches v.InferOutput", () => {
      expectTypeOf<MultiSchemaPostOutput>().toEqualTypeOf<v.InferOutput<typeof MultiSchemaPostSchema>>();
    });

    it("CommentSchema input matches v.InferInput", () => {
      expectTypeOf<MultiSchemaCommentInput>().toEqualTypeOf<v.InferInput<typeof MultiSchemaCommentSchema>>();
    });

    it("CommentSchema output matches v.InferOutput", () => {
      expectTypeOf<MultiSchemaCommentOutput>().toEqualTypeOf<v.InferOutput<typeof MultiSchemaCommentSchema>>();
    });

    it("DateStringSchema input matches v.InferInput", () => {
      expectTypeOf<MultiSchemaDateStringInput>().toEqualTypeOf<v.InferInput<typeof MultiSchemaDateStringSchema>>();
    });

    it("DateStringSchema output matches v.InferOutput", () => {
      expectTypeOf<MultiSchemaDateStringOutput>().toEqualTypeOf<v.InferOutput<typeof MultiSchemaDateStringSchema>>();
    });

    it("AliasedSchema input matches v.InferInput", () => {
      expectTypeOf<MultiSchemaAliasedInput>().toEqualTypeOf<v.InferInput<typeof MultiSchemaAliasedSchema>>();
    });

    it("AliasedSchema output matches v.InferOutput", () => {
      expectTypeOf<MultiSchemaAliasedOutput>().toEqualTypeOf<v.InferOutput<typeof MultiSchemaAliasedSchema>>();
    });
  });
});
