// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- multiline-description-schema ---
import { MultilineSchema as MultilineDescriptionSchemaMultilineSchema } from "../fixtures/multiline-description-schema";
import type { MultilineInput as MultilineDescriptionSchemaMultilineInput, MultilineOutput as MultilineDescriptionSchemaMultilineOutput } from "./multiline-description-schema";

describe("Type equality tests", () => {
  describe("multiline-description-schema", () => {
    it("MultilineSchema input matches v.InferInput", () => {
      expectTypeOf<MultilineDescriptionSchemaMultilineInput>().toEqualTypeOf<v.InferInput<typeof MultilineDescriptionSchemaMultilineSchema>>();
    });

    it("MultilineSchema output matches v.InferOutput", () => {
      expectTypeOf<MultilineDescriptionSchemaMultilineOutput>().toEqualTypeOf<v.InferOutput<typeof MultilineDescriptionSchemaMultilineSchema>>();
    });
  });
});
