// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- namespace-alias-schema ---
import { AliasedAddressSchema as NamespaceAliasSchemaAliasedAddressSchema, AliasedUserSchema as NamespaceAliasSchemaAliasedUserSchema } from "../fixtures/namespace-alias-schema";
import type {
  AliasedAddressInput as NamespaceAliasSchemaAliasedAddressInput,
  AliasedAddressOutput as NamespaceAliasSchemaAliasedAddressOutput,
  AliasedUserInput as NamespaceAliasSchemaAliasedUserInput,
  AliasedUserOutput as NamespaceAliasSchemaAliasedUserOutput,
} from "./namespace-alias-schema";

describe("Type equality tests", () => {
  describe("namespace-alias-schema", () => {
    it("AliasedAddressSchema input matches v.InferInput", () => {
      expectTypeOf<NamespaceAliasSchemaAliasedAddressInput>().toEqualTypeOf<v.InferInput<typeof NamespaceAliasSchemaAliasedAddressSchema>>();
    });

    it("AliasedAddressSchema output matches v.InferOutput", () => {
      expectTypeOf<NamespaceAliasSchemaAliasedAddressOutput>().toEqualTypeOf<v.InferOutput<typeof NamespaceAliasSchemaAliasedAddressSchema>>();
    });

    it("AliasedUserSchema input matches v.InferInput", () => {
      expectTypeOf<NamespaceAliasSchemaAliasedUserInput>().toEqualTypeOf<v.InferInput<typeof NamespaceAliasSchemaAliasedUserSchema>>();
    });

    it("AliasedUserSchema output matches v.InferOutput", () => {
      expectTypeOf<NamespaceAliasSchemaAliasedUserOutput>().toEqualTypeOf<v.InferOutput<typeof NamespaceAliasSchemaAliasedUserSchema>>();
    });
  });
});
