// Generated by vinfer - Do not edit manually

export type NamedAddressInput = {
  street: string;
  city: string;
};

export type NamedAddressOutput = {
  street: string;
  city: string;
};

export type NamedUserInput = {
  name: string;
  active: boolean;
  address: NamedAddressInput;
  previousAddresses?: NamedAddressInput[];
  visits: string;
  score?: number | undefined;
};

export type NamedUserOutput = {
  name: string;
  active: boolean;
  address: NamedAddressOutput;
  previousAddresses?: NamedAddressOutput[];
  visits: number;
  score?: number | undefined;
};
