// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- named-import-schema ---
import { NamedAddressSchema as NamedImportSchemaNamedAddressSchema, NamedUserSchema as NamedImportSchemaNamedUserSchema } from "../fixtures/named-import-schema";
import type {
  NamedAddressInput as NamedImportSchemaNamedAddressInput,
  NamedAddressOutput as NamedImportSchemaNamedAddressOutput,
  NamedUserInput as NamedImportSchemaNamedUserInput,
  NamedUserOutput as NamedImportSchemaNamedUserOutput,
} from "./named-import-schema";

describe("Type equality tests", () => {
  describe("named-import-schema", () => {
    it("NamedAddressSchema input matches v.InferInput", () => {
      expectTypeOf<NamedImportSchemaNamedAddressInput>().toEqualTypeOf<v.InferInput<typeof NamedImportSchemaNamedAddressSchema>>();
    });

    it("NamedAddressSchema output matches v.InferOutput", () => {
      expectTypeOf<NamedImportSchemaNamedAddressOutput>().toEqualTypeOf<v.InferOutput<typeof NamedImportSchemaNamedAddressSchema>>();
    });

    it("NamedUserSchema input matches v.InferInput", () => {
      expectTypeOf<NamedImportSchemaNamedUserInput>().toEqualTypeOf<v.InferInput<typeof NamedImportSchemaNamedUserSchema>>();
    });

    it("NamedUserSchema output matches v.InferOutput", () => {
      expectTypeOf<NamedImportSchemaNamedUserOutput>().toEqualTypeOf<v.InferOutput<typeof NamedImportSchemaNamedUserSchema>>();
    });
  });
});
