// Generated by vinfer - Do not edit manually

export type AliasedAddressInput = {
  street: string;
};

export type AliasedAddressOutput = {
  street: string;
};

export type AliasedUserInput = {
  name: string;
  address: AliasedAddressInput;
  addresses: AliasedAddressInput[];
};

export type AliasedUserOutput = {
  name: string;
  address: AliasedAddressOutput;
  addresses: AliasedAddressOutput[];
};
