// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- nested-inline-description-schema ---
import { GroupSchema as NestedInlineDescriptionSchemaGroupSchema, ContainerSchema as NestedInlineDescriptionSchemaContainerSchema, SiblingUnionSchema as NestedInlineDescriptionSchemaSiblingUnionSchema } from "../fixtures/nested-inline-description-schema";
import type {
  GroupInput as NestedInlineDescriptionSchemaGroupInput,
  GroupOutput as NestedInlineDescriptionSchemaGroupOutput,
  ContainerInput as NestedInlineDescriptionSchemaContainerInput,
  ContainerOutput as NestedInlineDescriptionSchemaContainerOutput,
  SiblingUnionInput as NestedInlineDescriptionSchemaSiblingUnionInput,
  SiblingUnionOutput as NestedInlineDescriptionSchemaSiblingUnionOutput,
} from "./nested-inline-description-schema";

describe("Type equality tests", () => {
  describe("nested-inline-description-schema", () => {
    it("GroupSchema input matches v.InferInput", () => {
      expectTypeOf<NestedInlineDescriptionSchemaGroupInput>().toEqualTypeOf<v.InferInput<typeof NestedInlineDescriptionSchemaGroupSchema>>();
    });

    it("GroupSchema output matches v.InferOutput", () => {
      expectTypeOf<NestedInlineDescriptionSchemaGroupOutput>().toEqualTypeOf<v.InferOutput<typeof NestedInlineDescriptionSchemaGroupSchema>>();
    });

    it("ContainerSchema input matches v.InferInput", () => {
      expectTypeOf<NestedInlineDescriptionSchemaContainerInput>().toEqualTypeOf<v.InferInput<typeof NestedInlineDescriptionSchemaContainerSchema>>();
    });

    it("ContainerSchema output matches v.InferOutput", () => {
      expectTypeOf<NestedInlineDescriptionSchemaContainerOutput>().toEqualTypeOf<v.InferOutput<typeof NestedInlineDescriptionSchemaContainerSchema>>();
    });

    it("SiblingUnionSchema input matches v.InferInput", () => {
      expectTypeOf<NestedInlineDescriptionSchemaSiblingUnionInput>().toEqualTypeOf<v.InferInput<typeof NestedInlineDescriptionSchemaSiblingUnionSchema>>();
    });

    it("SiblingUnionSchema output matches v.InferOutput", () => {
      expectTypeOf<NestedInlineDescriptionSchemaSiblingUnionOutput>().toEqualTypeOf<v.InferOutput<typeof NestedInlineDescriptionSchemaSiblingUnionSchema>>();
    });
  });
});
