// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- nested-schema ---
import { PersonSchema as NestedSchemaPersonSchema } from "../fixtures/nested-schema";
import type { PersonInput as NestedSchemaPersonInput, PersonOutput as NestedSchemaPersonOutput } from "./nested-schema";

describe("Type equality tests", () => {
  describe("nested-schema", () => {
    it("PersonSchema input matches v.InferInput", () => {
      expectTypeOf<NestedSchemaPersonInput>().toEqualTypeOf<v.InferInput<typeof NestedSchemaPersonSchema>>();
    });

    it("PersonSchema output matches v.InferOutput", () => {
      expectTypeOf<NestedSchemaPersonOutput>().toEqualTypeOf<v.InferOutput<typeof NestedSchemaPersonSchema>>();
    });
  });
});
