// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- non-generated-intermediate-schema ---
import { IntermediateNodeSchema as NonGeneratedIntermediateSchemaIntermediateNodeSchema, OrganizationSchema as NonGeneratedIntermediateSchemaOrganizationSchema } from "../fixtures/non-generated-intermediate-schema";
import type {
  IntermediateNodeInput as NonGeneratedIntermediateSchemaIntermediateNodeInput,
  IntermediateNodeOutput as NonGeneratedIntermediateSchemaIntermediateNodeOutput,
  OrganizationInput as NonGeneratedIntermediateSchemaOrganizationInput,
  OrganizationOutput as NonGeneratedIntermediateSchemaOrganizationOutput,
} from "./non-generated-intermediate-schema";

describe("Type equality tests", () => {
  describe("non-generated-intermediate-schema", () => {
    it("IntermediateNodeSchema input matches v.InferInput", () => {
      expectTypeOf<NonGeneratedIntermediateSchemaIntermediateNodeInput>().toEqualTypeOf<v.InferInput<typeof NonGeneratedIntermediateSchemaIntermediateNodeSchema>>();
    });

    it("IntermediateNodeSchema output matches v.InferOutput", () => {
      expectTypeOf<NonGeneratedIntermediateSchemaIntermediateNodeOutput>().toEqualTypeOf<v.InferOutput<typeof NonGeneratedIntermediateSchemaIntermediateNodeSchema>>();
    });

    it("OrganizationSchema input matches v.InferInput", () => {
      expectTypeOf<NonGeneratedIntermediateSchemaOrganizationInput>().toEqualTypeOf<v.InferInput<typeof NonGeneratedIntermediateSchemaOrganizationSchema>>();
    });

    it("OrganizationSchema output matches v.InferOutput", () => {
      expectTypeOf<NonGeneratedIntermediateSchemaOrganizationOutput>().toEqualTypeOf<v.InferOutput<typeof NonGeneratedIntermediateSchemaOrganizationSchema>>();
    });
  });
});
