// Generated by vinfer - Do not edit manually

export type IntermediateNodeInput = {
  name: string;
  children: {
    [x: string]: IntermediateNodeInput;
  };
};

export type IntermediateNodeOutput = {
  name: string;
  children: {
    [x: string]: IntermediateNodeOutput;
  };
};

type LocalRecursiveInput = {
  label: string;
  kids: {
    [x: string]: LocalRecursiveInput;
  };
};

type LocalRecursiveOutput = {
  label: string;
  kids: {
    [x: string]: LocalRecursiveOutput;
  };
};

export type OrganizationInput = {
  direct: IntermediateNodeInput;
  viaGroup: {
    members: IntermediateNodeInput[];
    byKey: {
      [x: string]: IntermediateNodeInput;
    };
    lead?: IntermediateNodeInput;
  };
  viaDepartment: {
    group: {
      members: IntermediateNodeInput[];
      byKey: {
        [x: string]: IntermediateNodeInput;
      };
      lead?: IntermediateNodeInput;
    };
  };
  localRecursive: LocalRecursiveInput;
};

export type OrganizationOutput = {
  direct: IntermediateNodeOutput;
  viaGroup: {
    members: IntermediateNodeOutput[];
    byKey: {
      [x: string]: IntermediateNodeOutput;
    };
    lead?: IntermediateNodeOutput;
  };
  viaDepartment: {
    group: {
      members: IntermediateNodeOutput[];
      byKey: {
        [x: string]: IntermediateNodeOutput;
      };
      lead?: IntermediateNodeOutput;
    };
  };
  localRecursive: LocalRecursiveOutput;
};
