// Generated by vinfer - Do not edit manually

export type ValidatedInput = {
  email: string;
  slug: string;
  count: number;
  items: string[];
  checked: string;
};

export type ValidatedOutput = {
  email: string;
  slug: string;
  count: number;
  items: string[];
  checked: string;
};

export type CoercedInput = {
  parsed: string;
};

export type CoercedOutput = {
  parsed: number;
};

export type AnnotatedInput = {
  id: string;
};

export type AnnotatedOutput = {
  id: string;
};
