// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- pipe-validation-schema ---
import { ValidatedSchema as PipeValidationSchemaValidatedSchema, CoercedSchema as PipeValidationSchemaCoercedSchema, AnnotatedSchema as PipeValidationSchemaAnnotatedSchema } from "../fixtures/pipe-validation-schema";
import type {
  ValidatedInput as PipeValidationSchemaValidatedInput,
  ValidatedOutput as PipeValidationSchemaValidatedOutput,
  CoercedInput as PipeValidationSchemaCoercedInput,
  CoercedOutput as PipeValidationSchemaCoercedOutput,
  AnnotatedInput as PipeValidationSchemaAnnotatedInput,
  AnnotatedOutput as PipeValidationSchemaAnnotatedOutput,
} from "./pipe-validation-schema";

describe("Type equality tests", () => {
  describe("pipe-validation-schema", () => {
    it("ValidatedSchema input matches v.InferInput", () => {
      expectTypeOf<PipeValidationSchemaValidatedInput>().toEqualTypeOf<v.InferInput<typeof PipeValidationSchemaValidatedSchema>>();
    });

    it("ValidatedSchema output matches v.InferOutput", () => {
      expectTypeOf<PipeValidationSchemaValidatedOutput>().toEqualTypeOf<v.InferOutput<typeof PipeValidationSchemaValidatedSchema>>();
    });

    it("CoercedSchema input matches v.InferInput", () => {
      expectTypeOf<PipeValidationSchemaCoercedInput>().toEqualTypeOf<v.InferInput<typeof PipeValidationSchemaCoercedSchema>>();
    });

    it("CoercedSchema output matches v.InferOutput", () => {
      expectTypeOf<PipeValidationSchemaCoercedOutput>().toEqualTypeOf<v.InferOutput<typeof PipeValidationSchemaCoercedSchema>>();
    });

    it("AnnotatedSchema input matches v.InferInput", () => {
      expectTypeOf<PipeValidationSchemaAnnotatedInput>().toEqualTypeOf<v.InferInput<typeof PipeValidationSchemaAnnotatedSchema>>();
    });

    it("AnnotatedSchema output matches v.InferOutput", () => {
      expectTypeOf<PipeValidationSchemaAnnotatedOutput>().toEqualTypeOf<v.InferOutput<typeof PipeValidationSchemaAnnotatedSchema>>();
    });
  });
});
