// Generated by vinfer - Do not edit manually

export type RecursiveRecordInput = {
  name: string;
  children: {
    [x: string]: RecursiveRecordInput;
  };
};

export type RecursiveRecordOutput = {
  name: string;
  children: {
    [x: string]: RecursiveRecordOutput;
  };
};

export type OptionalRecursiveRecordInput = {
  name: string;
  children?: {
    [x: string]: OptionalRecursiveRecordInput;
  };
};

export type OptionalRecursiveRecordOutput = {
  name: string;
  children?: {
    [x: string]: OptionalRecursiveRecordOutput;
  };
};

export type InferredOptionalRecordInput = {
  name: string;
  children?: {
    [x: string]: InferredOptionalRecordInput;
  };
};

export type InferredOptionalRecordOutput = {
  name: string;
  children?: {
    [x: string]: InferredOptionalRecordOutput;
  };
};

export type RecursiveArrayInput = {
  name: string;
  children: RecursiveArrayInput[];
};

export type RecursiveArrayOutput = {
  name: string;
  children: RecursiveArrayOutput[];
};

export type LeafRecordInput = {
  leaves: {
    [x: string]: {
      label: string;
    };
  };
};

export type LeafRecordOutput = {
  leaves: {
    [x: string]: {
      label: string;
    };
  };
};
