// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- recursive-record-schema ---
import { RecursiveRecordSchema as RecursiveRecordSchemaRecursiveRecordSchema, OptionalRecursiveRecordSchema as RecursiveRecordSchemaOptionalRecursiveRecordSchema, InferredOptionalRecordSchema as RecursiveRecordSchemaInferredOptionalRecordSchema, RecursiveArraySchema as RecursiveRecordSchemaRecursiveArraySchema, LeafRecordSchema as RecursiveRecordSchemaLeafRecordSchema } from "../fixtures/recursive-record-schema";
import type {
  RecursiveRecordInput as RecursiveRecordSchemaRecursiveRecordInput,
  RecursiveRecordOutput as RecursiveRecordSchemaRecursiveRecordOutput,
  OptionalRecursiveRecordInput as RecursiveRecordSchemaOptionalRecursiveRecordInput,
  OptionalRecursiveRecordOutput as RecursiveRecordSchemaOptionalRecursiveRecordOutput,
  InferredOptionalRecordInput as RecursiveRecordSchemaInferredOptionalRecordInput,
  InferredOptionalRecordOutput as RecursiveRecordSchemaInferredOptionalRecordOutput,
  RecursiveArrayInput as RecursiveRecordSchemaRecursiveArrayInput,
  RecursiveArrayOutput as RecursiveRecordSchemaRecursiveArrayOutput,
  LeafRecordInput as RecursiveRecordSchemaLeafRecordInput,
  LeafRecordOutput as RecursiveRecordSchemaLeafRecordOutput,
} from "./recursive-record-schema";

describe("Type equality tests", () => {
  describe("recursive-record-schema", () => {
    it("RecursiveRecordSchema input matches v.InferInput", () => {
      expectTypeOf<RecursiveRecordSchemaRecursiveRecordInput>().toEqualTypeOf<v.InferInput<typeof RecursiveRecordSchemaRecursiveRecordSchema>>();
    });

    it("RecursiveRecordSchema output matches v.InferOutput", () => {
      expectTypeOf<RecursiveRecordSchemaRecursiveRecordOutput>().toEqualTypeOf<v.InferOutput<typeof RecursiveRecordSchemaRecursiveRecordSchema>>();
    });

    it("OptionalRecursiveRecordSchema input matches v.InferInput", () => {
      expectTypeOf<RecursiveRecordSchemaOptionalRecursiveRecordInput>().toEqualTypeOf<v.InferInput<typeof RecursiveRecordSchemaOptionalRecursiveRecordSchema>>();
    });

    it("OptionalRecursiveRecordSchema output matches v.InferOutput", () => {
      expectTypeOf<RecursiveRecordSchemaOptionalRecursiveRecordOutput>().toEqualTypeOf<v.InferOutput<typeof RecursiveRecordSchemaOptionalRecursiveRecordSchema>>();
    });

    it("InferredOptionalRecordSchema input matches v.InferInput", () => {
      expectTypeOf<RecursiveRecordSchemaInferredOptionalRecordInput>().toEqualTypeOf<v.InferInput<typeof RecursiveRecordSchemaInferredOptionalRecordSchema>>();
    });

    it("InferredOptionalRecordSchema output matches v.InferOutput", () => {
      expectTypeOf<RecursiveRecordSchemaInferredOptionalRecordOutput>().toEqualTypeOf<v.InferOutput<typeof RecursiveRecordSchemaInferredOptionalRecordSchema>>();
    });

    it("RecursiveArraySchema input matches v.InferInput", () => {
      expectTypeOf<RecursiveRecordSchemaRecursiveArrayInput>().toEqualTypeOf<v.InferInput<typeof RecursiveRecordSchemaRecursiveArraySchema>>();
    });

    it("RecursiveArraySchema output matches v.InferOutput", () => {
      expectTypeOf<RecursiveRecordSchemaRecursiveArrayOutput>().toEqualTypeOf<v.InferOutput<typeof RecursiveRecordSchemaRecursiveArraySchema>>();
    });

    it("LeafRecordSchema input matches v.InferInput", () => {
      expectTypeOf<RecursiveRecordSchemaLeafRecordInput>().toEqualTypeOf<v.InferInput<typeof RecursiveRecordSchemaLeafRecordSchema>>();
    });

    it("LeafRecordSchema output matches v.InferOutput", () => {
      expectTypeOf<RecursiveRecordSchemaLeafRecordOutput>().toEqualTypeOf<v.InferOutput<typeof RecursiveRecordSchemaLeafRecordSchema>>();
    });
  });
});
