// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- strict-object-schema ---
import { AddressSchema as StrictObjectSchemaAddressSchema, UserSchema as StrictObjectSchemaUserSchema, LooseProfileSchema as StrictObjectSchemaLooseProfileSchema, ObjectWithRestSchema as StrictObjectSchemaObjectWithRestSchema } from "../fixtures/strict-object-schema";
import type {
  AddressInput as StrictObjectSchemaAddressInput,
  AddressOutput as StrictObjectSchemaAddressOutput,
  UserInput as StrictObjectSchemaUserInput,
  UserOutput as StrictObjectSchemaUserOutput,
  LooseProfileInput as StrictObjectSchemaLooseProfileInput,
  LooseProfileOutput as StrictObjectSchemaLooseProfileOutput,
  ObjectWithRestInput as StrictObjectSchemaObjectWithRestInput,
  ObjectWithRestOutput as StrictObjectSchemaObjectWithRestOutput,
} from "./strict-object-schema";

describe("Type equality tests", () => {
  describe("strict-object-schema", () => {
    it("AddressSchema input matches v.InferInput", () => {
      expectTypeOf<StrictObjectSchemaAddressInput>().toEqualTypeOf<v.InferInput<typeof StrictObjectSchemaAddressSchema>>();
    });

    it("AddressSchema output matches v.InferOutput", () => {
      expectTypeOf<StrictObjectSchemaAddressOutput>().toEqualTypeOf<v.InferOutput<typeof StrictObjectSchemaAddressSchema>>();
    });

    it("UserSchema input matches v.InferInput", () => {
      expectTypeOf<StrictObjectSchemaUserInput>().toEqualTypeOf<v.InferInput<typeof StrictObjectSchemaUserSchema>>();
    });

    it("UserSchema output matches v.InferOutput", () => {
      expectTypeOf<StrictObjectSchemaUserOutput>().toEqualTypeOf<v.InferOutput<typeof StrictObjectSchemaUserSchema>>();
    });

    it("LooseProfileSchema input matches v.InferInput", () => {
      expectTypeOf<StrictObjectSchemaLooseProfileInput>().toEqualTypeOf<v.InferInput<typeof StrictObjectSchemaLooseProfileSchema>>();
    });

    it("LooseProfileSchema output matches v.InferOutput", () => {
      expectTypeOf<StrictObjectSchemaLooseProfileOutput>().toEqualTypeOf<v.InferOutput<typeof StrictObjectSchemaLooseProfileSchema>>();
    });

    it("ObjectWithRestSchema input matches v.InferInput", () => {
      expectTypeOf<StrictObjectSchemaObjectWithRestInput>().toEqualTypeOf<v.InferInput<typeof StrictObjectSchemaObjectWithRestSchema>>();
    });

    it("ObjectWithRestSchema output matches v.InferOutput", () => {
      expectTypeOf<StrictObjectSchemaObjectWithRestOutput>().toEqualTypeOf<v.InferOutput<typeof StrictObjectSchemaObjectWithRestSchema>>();
    });
  });
});
