// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- transform-schema ---
import { DateSchema as TransformSchemaDateSchema } from "../fixtures/transform-schema";
import type { DateInput as TransformSchemaDateInput, DateOutput as TransformSchemaDateOutput } from "./transform-schema";

describe("Type equality tests", () => {
  describe("transform-schema", () => {
    it("DateSchema input matches v.InferInput", () => {
      expectTypeOf<TransformSchemaDateInput>().toEqualTypeOf<v.InferInput<typeof TransformSchemaDateSchema>>();
    });

    it("DateSchema output matches v.InferOutput", () => {
      expectTypeOf<TransformSchemaDateOutput>().toEqualTypeOf<v.InferOutput<typeof TransformSchemaDateSchema>>();
    });
  });
});
