// Generated by vinfer - Do not edit manually

export type PointInput = {
  coordinates: [number, number];
  label: string;
};

export type PointOutput = {
  coordinates: [number, number];
  label: string;
};

export type MixedTupleInput = {
  entry: [string, number, boolean];
};

export type MixedTupleOutput = {
  entry: [string, number, boolean];
};

export type TupleWithRestInput = {
  entry: [string, ...number[]];
};

export type TupleWithRestOutput = {
  entry: [string, ...number[]];
};
