// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- tuple-schema ---
import { PointSchema as TupleSchemaPointSchema, MixedTupleSchema as TupleSchemaMixedTupleSchema, TupleWithRestSchema as TupleSchemaTupleWithRestSchema } from "../fixtures/tuple-schema";
import type {
  PointInput as TupleSchemaPointInput,
  PointOutput as TupleSchemaPointOutput,
  MixedTupleInput as TupleSchemaMixedTupleInput,
  MixedTupleOutput as TupleSchemaMixedTupleOutput,
  TupleWithRestInput as TupleSchemaTupleWithRestInput,
  TupleWithRestOutput as TupleSchemaTupleWithRestOutput,
} from "./tuple-schema";

describe("Type equality tests", () => {
  describe("tuple-schema", () => {
    it("PointSchema input matches v.InferInput", () => {
      expectTypeOf<TupleSchemaPointInput>().toEqualTypeOf<v.InferInput<typeof TupleSchemaPointSchema>>();
    });

    it("PointSchema output matches v.InferOutput", () => {
      expectTypeOf<TupleSchemaPointOutput>().toEqualTypeOf<v.InferOutput<typeof TupleSchemaPointSchema>>();
    });

    it("MixedTupleSchema input matches v.InferInput", () => {
      expectTypeOf<TupleSchemaMixedTupleInput>().toEqualTypeOf<v.InferInput<typeof TupleSchemaMixedTupleSchema>>();
    });

    it("MixedTupleSchema output matches v.InferOutput", () => {
      expectTypeOf<TupleSchemaMixedTupleOutput>().toEqualTypeOf<v.InferOutput<typeof TupleSchemaMixedTupleSchema>>();
    });

    it("TupleWithRestSchema input matches v.InferInput", () => {
      expectTypeOf<TupleSchemaTupleWithRestInput>().toEqualTypeOf<v.InferInput<typeof TupleSchemaTupleWithRestSchema>>();
    });

    it("TupleWithRestSchema output matches v.InferOutput", () => {
      expectTypeOf<TupleSchemaTupleWithRestOutput>().toEqualTypeOf<v.InferOutput<typeof TupleSchemaTupleWithRestSchema>>();
    });
  });
});
