// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- tuple-brand-schema ---
import { CoordSchema as TupleBrandSchemaCoordSchema, TagListSchema as TupleBrandSchemaTagListSchema, FrozenPairSchema as TupleBrandSchemaFrozenPairSchema, HeadedListSchema as TupleBrandSchemaHeadedListSchema, ShapeSchema as TupleBrandSchemaShapeSchema } from "../fixtures/tuple-brand-schema";
import type {
  CoordInput as TupleBrandSchemaCoordInput,
  CoordOutput as TupleBrandSchemaCoordOutput,
  TagListInput as TupleBrandSchemaTagListInput,
  TagListOutput as TupleBrandSchemaTagListOutput,
  FrozenPairInput as TupleBrandSchemaFrozenPairInput,
  FrozenPairOutput as TupleBrandSchemaFrozenPairOutput,
  HeadedListInput as TupleBrandSchemaHeadedListInput,
  HeadedListOutput as TupleBrandSchemaHeadedListOutput,
  ShapeInput as TupleBrandSchemaShapeInput,
  ShapeOutput as TupleBrandSchemaShapeOutput,
} from "./tuple-brand-schema";

describe("Type equality tests", () => {
  describe("tuple-brand-schema", () => {
    it("CoordSchema input matches v.InferInput", () => {
      expectTypeOf<TupleBrandSchemaCoordInput>().toEqualTypeOf<v.InferInput<typeof TupleBrandSchemaCoordSchema>>();
    });

    it("CoordSchema output matches v.InferOutput", () => {
      expectTypeOf<TupleBrandSchemaCoordOutput>().toEqualTypeOf<v.InferOutput<typeof TupleBrandSchemaCoordSchema>>();
    });

    it("TagListSchema input matches v.InferInput", () => {
      expectTypeOf<TupleBrandSchemaTagListInput>().toEqualTypeOf<v.InferInput<typeof TupleBrandSchemaTagListSchema>>();
    });

    it("TagListSchema output matches v.InferOutput", () => {
      expectTypeOf<TupleBrandSchemaTagListOutput>().toEqualTypeOf<v.InferOutput<typeof TupleBrandSchemaTagListSchema>>();
    });

    it("FrozenPairSchema input matches v.InferInput", () => {
      expectTypeOf<TupleBrandSchemaFrozenPairInput>().toEqualTypeOf<v.InferInput<typeof TupleBrandSchemaFrozenPairSchema>>();
    });

    it("FrozenPairSchema output matches v.InferOutput", () => {
      expectTypeOf<TupleBrandSchemaFrozenPairOutput>().toEqualTypeOf<v.InferOutput<typeof TupleBrandSchemaFrozenPairSchema>>();
    });

    it("HeadedListSchema input matches v.InferInput", () => {
      expectTypeOf<TupleBrandSchemaHeadedListInput>().toEqualTypeOf<v.InferInput<typeof TupleBrandSchemaHeadedListSchema>>();
    });

    it("HeadedListSchema output matches v.InferOutput", () => {
      expectTypeOf<TupleBrandSchemaHeadedListOutput>().toEqualTypeOf<v.InferOutput<typeof TupleBrandSchemaHeadedListSchema>>();
    });

    it("ShapeSchema input matches v.InferInput", () => {
      expectTypeOf<TupleBrandSchemaShapeInput>().toEqualTypeOf<v.InferInput<typeof TupleBrandSchemaShapeSchema>>();
    });

    it("ShapeSchema output matches v.InferOutput", () => {
      expectTypeOf<TupleBrandSchemaShapeOutput>().toEqualTypeOf<v.InferOutput<typeof TupleBrandSchemaShapeSchema>>();
    });
  });
});
