// Generated by vinfer - Do not edit manually

import type { Brand } from "valibot";

export type CoordInput = [number, number];

export type CoordOutput = [number, number] & Brand<"Coord">;

export type TagListInput = string[];

export type TagListOutput = string[] & Brand<"TagList">;

export type HeadedListInput = [string, ...number[]];

export type HeadedListOutput = [string, ...number[]] & Brand<"HeadedList">;

export type ShapeInput = {
  origin: [number, number];
  size: [number, number];
};

export type ShapeOutput = {
  origin: [number, number] & Brand<"Coord">;
  size: [number, number];
};
