// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- union-nonexport-member-schema ---
import { ResponseSchema as UnionNonexportMemberSchemaResponseSchema } from "../fixtures/union-nonexport-member-schema";
import type { ResponseInput as UnionNonexportMemberSchemaResponseInput, ResponseOutput as UnionNonexportMemberSchemaResponseOutput } from "./union-nonexport-member-schema";

describe("Type equality tests", () => {
  describe("union-nonexport-member-schema", () => {
    it("ResponseSchema input matches v.InferInput", () => {
      expectTypeOf<UnionNonexportMemberSchemaResponseInput>().toEqualTypeOf<v.InferInput<typeof UnionNonexportMemberSchemaResponseSchema>>();
    });

    it("ResponseSchema output matches v.InferOutput", () => {
      expectTypeOf<UnionNonexportMemberSchemaResponseOutput>().toEqualTypeOf<v.InferOutput<typeof UnionNonexportMemberSchemaResponseSchema>>();
    });
  });
});
