// Generated by vinfer - Do not edit manually

export type StatusInput = "active" | "inactive" | "pending";

export type StatusOutput = "active" | "inactive" | "pending";

export type ResultInput = {
  type: "success";
  data: string;
} | {
  type: "error";
  message: string;
};

export type ResultOutput = {
  type: "success";
  data: string;
} | {
  type: "error";
  message: string;
};

export type StringOrNumberInput = string | number;

export type StringOrNumberOutput = string | number;

export type RoleInput = "admin" | "user" | "guest";

export type RoleOutput = "admin" | "user" | "guest";
