// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- union-ref-schema ---
import { DogSchema as UnionRefSchemaDogSchema, CatSchema as UnionRefSchemaCatSchema, BirdSchema as UnionRefSchemaBirdSchema, PetSchema as UnionRefSchemaPetSchema, AnimalSchema as UnionRefSchemaAnimalSchema } from "../fixtures/union-ref-schema";
import type {
  DogInput as UnionRefSchemaDogInput,
  DogOutput as UnionRefSchemaDogOutput,
  CatInput as UnionRefSchemaCatInput,
  CatOutput as UnionRefSchemaCatOutput,
  BirdInput as UnionRefSchemaBirdInput,
  BirdOutput as UnionRefSchemaBirdOutput,
  PetInput as UnionRefSchemaPetInput,
  PetOutput as UnionRefSchemaPetOutput,
  AnimalInput as UnionRefSchemaAnimalInput,
  AnimalOutput as UnionRefSchemaAnimalOutput,
} from "./union-ref-schema";

describe("Type equality tests", () => {
  describe("union-ref-schema", () => {
    it("DogSchema input matches v.InferInput", () => {
      expectTypeOf<UnionRefSchemaDogInput>().toEqualTypeOf<v.InferInput<typeof UnionRefSchemaDogSchema>>();
    });

    it("DogSchema output matches v.InferOutput", () => {
      expectTypeOf<UnionRefSchemaDogOutput>().toEqualTypeOf<v.InferOutput<typeof UnionRefSchemaDogSchema>>();
    });

    it("CatSchema input matches v.InferInput", () => {
      expectTypeOf<UnionRefSchemaCatInput>().toEqualTypeOf<v.InferInput<typeof UnionRefSchemaCatSchema>>();
    });

    it("CatSchema output matches v.InferOutput", () => {
      expectTypeOf<UnionRefSchemaCatOutput>().toEqualTypeOf<v.InferOutput<typeof UnionRefSchemaCatSchema>>();
    });

    it("BirdSchema input matches v.InferInput", () => {
      expectTypeOf<UnionRefSchemaBirdInput>().toEqualTypeOf<v.InferInput<typeof UnionRefSchemaBirdSchema>>();
    });

    it("BirdSchema output matches v.InferOutput", () => {
      expectTypeOf<UnionRefSchemaBirdOutput>().toEqualTypeOf<v.InferOutput<typeof UnionRefSchemaBirdSchema>>();
    });

    it("PetSchema input matches v.InferInput", () => {
      expectTypeOf<UnionRefSchemaPetInput>().toEqualTypeOf<v.InferInput<typeof UnionRefSchemaPetSchema>>();
    });

    it("PetSchema output matches v.InferOutput", () => {
      expectTypeOf<UnionRefSchemaPetOutput>().toEqualTypeOf<v.InferOutput<typeof UnionRefSchemaPetSchema>>();
    });

    it("AnimalSchema input matches v.InferInput", () => {
      expectTypeOf<UnionRefSchemaAnimalInput>().toEqualTypeOf<v.InferInput<typeof UnionRefSchemaAnimalSchema>>();
    });

    it("AnimalSchema output matches v.InferOutput", () => {
      expectTypeOf<UnionRefSchemaAnimalOutput>().toEqualTypeOf<v.InferOutput<typeof UnionRefSchemaAnimalSchema>>();
    });
  });
});
