// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- union-schema ---
import { StatusSchema as UnionSchemaStatusSchema, ResultSchema as UnionSchemaResultSchema, StringOrNumberSchema as UnionSchemaStringOrNumberSchema, RoleSchema as UnionSchemaRoleSchema } from "../fixtures/union-schema";
import type {
  StatusInput as UnionSchemaStatusInput,
  StatusOutput as UnionSchemaStatusOutput,
  ResultInput as UnionSchemaResultInput,
  ResultOutput as UnionSchemaResultOutput,
  StringOrNumberInput as UnionSchemaStringOrNumberInput,
  StringOrNumberOutput as UnionSchemaStringOrNumberOutput,
  RoleInput as UnionSchemaRoleInput,
  RoleOutput as UnionSchemaRoleOutput,
} from "./union-schema";

describe("Type equality tests", () => {
  describe("union-schema", () => {
    it("StatusSchema input matches v.InferInput", () => {
      expectTypeOf<UnionSchemaStatusInput>().toEqualTypeOf<v.InferInput<typeof UnionSchemaStatusSchema>>();
    });

    it("StatusSchema output matches v.InferOutput", () => {
      expectTypeOf<UnionSchemaStatusOutput>().toEqualTypeOf<v.InferOutput<typeof UnionSchemaStatusSchema>>();
    });

    it("ResultSchema input matches v.InferInput", () => {
      expectTypeOf<UnionSchemaResultInput>().toEqualTypeOf<v.InferInput<typeof UnionSchemaResultSchema>>();
    });

    it("ResultSchema output matches v.InferOutput", () => {
      expectTypeOf<UnionSchemaResultOutput>().toEqualTypeOf<v.InferOutput<typeof UnionSchemaResultSchema>>();
    });

    it("StringOrNumberSchema input matches v.InferInput", () => {
      expectTypeOf<UnionSchemaStringOrNumberInput>().toEqualTypeOf<v.InferInput<typeof UnionSchemaStringOrNumberSchema>>();
    });

    it("StringOrNumberSchema output matches v.InferOutput", () => {
      expectTypeOf<UnionSchemaStringOrNumberOutput>().toEqualTypeOf<v.InferOutput<typeof UnionSchemaStringOrNumberSchema>>();
    });

    it("RoleSchema input matches v.InferInput", () => {
      expectTypeOf<UnionSchemaRoleInput>().toEqualTypeOf<v.InferInput<typeof UnionSchemaRoleSchema>>();
    });

    it("RoleSchema output matches v.InferOutput", () => {
      expectTypeOf<UnionSchemaRoleOutput>().toEqualTypeOf<v.InferOutput<typeof UnionSchemaRoleSchema>>();
    });
  });
});
