// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- utility-types-schema ---
import { PartialUserSchema as UtilityTypesSchemaPartialUserSchema, UserIdNameSchema as UtilityTypesSchemaUserIdNameSchema, UserWithoutEmailSchema as UtilityTypesSchemaUserWithoutEmailSchema, RequiredUserSchema as UtilityTypesSchemaRequiredUserSchema, UserKeySchema as UtilityTypesSchemaUserKeySchema, NestedSchema as UtilityTypesSchemaNestedSchema, DeepPartialNestedSchema as UtilityTypesSchemaDeepPartialNestedSchema } from "../fixtures/utility-types-schema";
import type {
  PartialUserInput as UtilityTypesSchemaPartialUserInput,
  PartialUserOutput as UtilityTypesSchemaPartialUserOutput,
  UserIdNameInput as UtilityTypesSchemaUserIdNameInput,
  UserIdNameOutput as UtilityTypesSchemaUserIdNameOutput,
  UserWithoutEmailInput as UtilityTypesSchemaUserWithoutEmailInput,
  UserWithoutEmailOutput as UtilityTypesSchemaUserWithoutEmailOutput,
  RequiredUserInput as UtilityTypesSchemaRequiredUserInput,
  RequiredUserOutput as UtilityTypesSchemaRequiredUserOutput,
  UserKeyInput as UtilityTypesSchemaUserKeyInput,
  UserKeyOutput as UtilityTypesSchemaUserKeyOutput,
  NestedInput as UtilityTypesSchemaNestedInput,
  NestedOutput as UtilityTypesSchemaNestedOutput,
  DeepPartialNestedInput as UtilityTypesSchemaDeepPartialNestedInput,
  DeepPartialNestedOutput as UtilityTypesSchemaDeepPartialNestedOutput,
} from "./utility-types-schema";

describe("Type equality tests", () => {
  describe("utility-types-schema", () => {
    it("PartialUserSchema input matches v.InferInput", () => {
      expectTypeOf<UtilityTypesSchemaPartialUserInput>().toEqualTypeOf<v.InferInput<typeof UtilityTypesSchemaPartialUserSchema>>();
    });

    it("PartialUserSchema output matches v.InferOutput", () => {
      expectTypeOf<UtilityTypesSchemaPartialUserOutput>().toEqualTypeOf<v.InferOutput<typeof UtilityTypesSchemaPartialUserSchema>>();
    });

    it("UserIdNameSchema input matches v.InferInput", () => {
      expectTypeOf<UtilityTypesSchemaUserIdNameInput>().toEqualTypeOf<v.InferInput<typeof UtilityTypesSchemaUserIdNameSchema>>();
    });

    it("UserIdNameSchema output matches v.InferOutput", () => {
      expectTypeOf<UtilityTypesSchemaUserIdNameOutput>().toEqualTypeOf<v.InferOutput<typeof UtilityTypesSchemaUserIdNameSchema>>();
    });

    it("UserWithoutEmailSchema input matches v.InferInput", () => {
      expectTypeOf<UtilityTypesSchemaUserWithoutEmailInput>().toEqualTypeOf<v.InferInput<typeof UtilityTypesSchemaUserWithoutEmailSchema>>();
    });

    it("UserWithoutEmailSchema output matches v.InferOutput", () => {
      expectTypeOf<UtilityTypesSchemaUserWithoutEmailOutput>().toEqualTypeOf<v.InferOutput<typeof UtilityTypesSchemaUserWithoutEmailSchema>>();
    });

    it("RequiredUserSchema input matches v.InferInput", () => {
      expectTypeOf<UtilityTypesSchemaRequiredUserInput>().toEqualTypeOf<v.InferInput<typeof UtilityTypesSchemaRequiredUserSchema>>();
    });

    it("RequiredUserSchema output matches v.InferOutput", () => {
      expectTypeOf<UtilityTypesSchemaRequiredUserOutput>().toEqualTypeOf<v.InferOutput<typeof UtilityTypesSchemaRequiredUserSchema>>();
    });

    it("UserKeySchema input matches v.InferInput", () => {
      expectTypeOf<UtilityTypesSchemaUserKeyInput>().toEqualTypeOf<v.InferInput<typeof UtilityTypesSchemaUserKeySchema>>();
    });

    it("UserKeySchema output matches v.InferOutput", () => {
      expectTypeOf<UtilityTypesSchemaUserKeyOutput>().toEqualTypeOf<v.InferOutput<typeof UtilityTypesSchemaUserKeySchema>>();
    });

    it("NestedSchema input matches v.InferInput", () => {
      expectTypeOf<UtilityTypesSchemaNestedInput>().toEqualTypeOf<v.InferInput<typeof UtilityTypesSchemaNestedSchema>>();
    });

    it("NestedSchema output matches v.InferOutput", () => {
      expectTypeOf<UtilityTypesSchemaNestedOutput>().toEqualTypeOf<v.InferOutput<typeof UtilityTypesSchemaNestedSchema>>();
    });

    it("DeepPartialNestedSchema input matches v.InferInput", () => {
      expectTypeOf<UtilityTypesSchemaDeepPartialNestedInput>().toEqualTypeOf<v.InferInput<typeof UtilityTypesSchemaDeepPartialNestedSchema>>();
    });

    it("DeepPartialNestedSchema output matches v.InferOutput", () => {
      expectTypeOf<UtilityTypesSchemaDeepPartialNestedOutput>().toEqualTypeOf<v.InferOutput<typeof UtilityTypesSchemaDeepPartialNestedSchema>>();
    });
  });
});
