// This file is auto-generated by vinfer --generate-tests
// Do not edit manually. Regenerate with: vinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type * as v from "valibot";

// --- wrapper-schema ---
import { WrappedSchema as WrapperSchemaWrappedSchema, DefaultedSchema as WrapperSchemaDefaultedSchema, FallbackSchema as WrapperSchemaFallbackSchema, NonWrappedSchema as WrapperSchemaNonWrappedSchema } from "../fixtures/wrapper-schema";
import type {
  WrappedInput as WrapperSchemaWrappedInput,
  WrappedOutput as WrapperSchemaWrappedOutput,
  DefaultedInput as WrapperSchemaDefaultedInput,
  DefaultedOutput as WrapperSchemaDefaultedOutput,
  FallbackInput as WrapperSchemaFallbackInput,
  FallbackOutput as WrapperSchemaFallbackOutput,
  NonWrappedInput as WrapperSchemaNonWrappedInput,
  NonWrappedOutput as WrapperSchemaNonWrappedOutput,
} from "./wrapper-schema";

describe("Type equality tests", () => {
  describe("wrapper-schema", () => {
    it("WrappedSchema input matches v.InferInput", () => {
      expectTypeOf<WrapperSchemaWrappedInput>().toEqualTypeOf<v.InferInput<typeof WrapperSchemaWrappedSchema>>();
    });

    it("WrappedSchema output matches v.InferOutput", () => {
      expectTypeOf<WrapperSchemaWrappedOutput>().toEqualTypeOf<v.InferOutput<typeof WrapperSchemaWrappedSchema>>();
    });

    it("DefaultedSchema input matches v.InferInput", () => {
      expectTypeOf<WrapperSchemaDefaultedInput>().toEqualTypeOf<v.InferInput<typeof WrapperSchemaDefaultedSchema>>();
    });

    it("DefaultedSchema output matches v.InferOutput", () => {
      expectTypeOf<WrapperSchemaDefaultedOutput>().toEqualTypeOf<v.InferOutput<typeof WrapperSchemaDefaultedSchema>>();
    });

    it("FallbackSchema input matches v.InferInput", () => {
      expectTypeOf<WrapperSchemaFallbackInput>().toEqualTypeOf<v.InferInput<typeof WrapperSchemaFallbackSchema>>();
    });

    it("FallbackSchema output matches v.InferOutput", () => {
      expectTypeOf<WrapperSchemaFallbackOutput>().toEqualTypeOf<v.InferOutput<typeof WrapperSchemaFallbackSchema>>();
    });

    it("NonWrappedSchema input matches v.InferInput", () => {
      expectTypeOf<WrapperSchemaNonWrappedInput>().toEqualTypeOf<v.InferInput<typeof WrapperSchemaNonWrappedSchema>>();
    });

    it("NonWrappedSchema output matches v.InferOutput", () => {
      expectTypeOf<WrapperSchemaNonWrappedOutput>().toEqualTypeOf<v.InferOutput<typeof WrapperSchemaNonWrappedSchema>>();
    });
  });
});
