// Generated by vinfer - Do not edit manually

export type WrappedInput = {
  optional?: string | undefined;
  exactOptional?: string | undefined;
  nullable: string | null;
  nullish?: string | null | undefined;
  undefinedable: string | undefined;
  required: string;
};

export type WrappedOutput = {
  optional?: string | undefined;
  exactOptional?: string | undefined;
  nullable: string | null;
  nullish?: string | null | undefined;
  undefinedable: string | undefined;
  required: string;
};

export type DefaultedInput = {
  withDefault?: string | undefined;
  withNullishDefault?: number | null | undefined;
  withComputedDefault?: Date | undefined;
};

export type DefaultedOutput = {
  withDefault: string;
  withNullishDefault: number;
  withComputedDefault: Date;
};

export type FallbackInput = {
  count: number;
};

export type FallbackOutput = {
  count: number;
};

export type NonWrappedInput = {
  value: string;
  other: number;
};

export type NonWrappedOutput = {
  value: string;
  other: number;
};
