// Generated by zinfer - Do not edit manually

export type QuxInput = import("../../fixtures/degenerate-explicit-type/default-export-explicit-type-schema").default;

export type QuxOutput = import("../../fixtures/degenerate-explicit-type/default-export-explicit-type-schema").default;
