// Generated by zinfer - Do not edit manually

export type FooInput = import("../../fixtures/degenerate-explicit-type-cross-file/other").ImportedClass;

export type FooOutput = import("../../fixtures/degenerate-explicit-type-cross-file/other").ImportedClass;
