// Generated by zinfer - Do not edit manually

export type SuffixWrapInput = {
  callbacks: ((value: string) => string)[];
};

export type SuffixWrapOutput = {
  callbacks: ((value: string) => string)[];
};
