// Generated by zinfer - Do not edit manually

export type DirectTypeofQueryInput = {
  value: typeof import("../../../fixtures/inline-external-types/typeof-query/kind").Kind;
};

export type DirectTypeofQueryOutput = {
  value: typeof import("../../../fixtures/inline-external-types/typeof-query/kind").Kind;
};
