// Generated by zinfer - Do not edit manually

export type TypeofQueryInput = {
  holder: {
    value: typeof import("../../../fixtures/inline-external-types/typeof-query/kind").Kind;
  };
};

export type TypeofQueryOutput = {
  holder: {
    value: typeof import("../../../fixtures/inline-external-types/typeof-query/kind").Kind;
  };
};
