// Generated by zinfer - Do not edit manually

export type TypeofQueryInput = {
  holder: import("../../../fixtures/inline-external-types/typeof-query/holder").Holder;
};

export type TypeofQueryOutput = {
  holder: import("../../../fixtures/inline-external-types/typeof-query/holder").Holder;
};
