// Generated by vinfer - Do not edit manually

export type FooInput = import("../../fixtures/degenerate-explicit-type-cross-file/other").ImportedInterface;

export type FooOutput = import("../../fixtures/degenerate-explicit-type-cross-file/other").ImportedInterface;
