// Generated by vinfer - Do not edit manually

export type QualifiedInput = {
  holder: import("../../../fixtures/inline-external-types/qualified/holder").Holder;
};

export type QualifiedOutput = {
  holder: import("../../../fixtures/inline-external-types/qualified/holder").Holder;
};
