// Generated by vinfer - Do not edit manually

export type QualifiedInput = {
  holder: {
    kind: import("../../../fixtures/inline-external-types/qualified/kind").Kind.A;
    box: import("../../../fixtures/inline-external-types/qualified/kind").Box<string>;
  };
};

export type QualifiedOutput = {
  holder: {
    kind: import("../../../fixtures/inline-external-types/qualified/kind").Kind.A;
    box: import("../../../fixtures/inline-external-types/qualified/kind").Box<string>;
  };
};
