// Generated by vinfer - Do not edit manually

export type FieldInput = {
  type: import("../../../../fixtures/nested-import-path/deep/nested/common").FieldType;
  fields?: Record<string, FieldInput>;
};

export type FieldOutput = {
  type: import("../../../../fixtures/nested-import-path/deep/nested/common").FieldType;
  fields?: Record<string, FieldOutput>;
};
