// Generated by zinfer-mini - Do not edit manually

export type UserInput = {
  id: string;
  name: string;
  email: string | null;
  age?: number | undefined;
};

export type UserOutput = {
  id: string;
  name: string;
  email: string | null;
  age?: number | undefined;
};
