// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- basic-schema ---
import { UserSchema as BasicSchemaUserSchema } from "../fixtures/basic-schema";
import type { UserInput as BasicSchemaUserInput, UserOutput as BasicSchemaUserOutput } from "./basic-schema";

describe("Type equality tests", () => {
  describe("basic-schema", () => {
    it("UserSchema input matches z.input", () => {
      expectTypeOf<BasicSchemaUserInput>().toEqualTypeOf<z.input<typeof BasicSchemaUserSchema>>();
    });

    it("UserSchema output matches z.output", () => {
      expectTypeOf<BasicSchemaUserOutput>().toEqualTypeOf<z.output<typeof BasicSchemaUserSchema>>();
    });
  });
});
