// Generated by zinfer - Do not edit manually

export type BaseInput = {
  id: string;
  name: string;
  age: number;
};

export type BaseOutput = {
  id: string;
  name: string;
  age: number;
};

export type PickedInput = {
  id: string;
  name: string;
};

export type PickedOutput = {
  id: string;
  name: string;
};

export type OmittedInput = {
  id: string;
  name: string;
};

export type OmittedOutput = {
  id: string;
  name: string;
};

export type PartialInput = {
  id?: string | undefined;
  name?: string | undefined;
  age?: number | undefined;
};

export type PartialOutput = {
  id?: string | undefined;
  name?: string | undefined;
  age?: number | undefined;
};

export type RequiredInput = {
  id: string;
  name: string;
  age: number;
};

export type RequiredOutput = {
  id: string;
  name: string;
  age: number;
};

export type ExtendedInput = {
  id: string;
  name: string;
  age: number;
  active: boolean;
};

export type ExtendedOutput = {
  id: string;
  name: string;
  age: number;
  active: boolean;
};

export type TupleInput = [string, number, boolean];

export type TupleOutput = [string, number, boolean];

export type RecordInput = {
  [x: string]: number;
};

export type RecordOutput = {
  [x: string]: number;
};

export type MapInput = Map<string, number>;

export type MapOutput = Map<string, number>;

export type SetInput = Set<string>;

export type SetOutput = Set<string>;

export type IntersectionInput = {
  a: string;
  b: number;
};

export type IntersectionOutput = {
  a: string;
  b: number;
};

export type LiteralUnionInput = "a" | "b" | "c";

export type LiteralUnionOutput = "a" | "b" | "c";

export type TemplateLiteralInput = `prefix-${string}`;

export type TemplateLiteralOutput = `prefix-${string}`;

export type DefaultedInput = {
  count?: number | undefined;
};

export type DefaultedOutput = {
  count: number;
};

export type PrefaultedInput = {
  label?: string | undefined;
};

export type PrefaultedOutput = {
  label: string;
};

export type CaughtInput = {
  value: number;
};

export type CaughtOutput = {
  value: number;
};

export type CustomInput = `${string}@${string}`;

export type CustomOutput = `${string}@${string}`;

export type RefinedInput = string;

export type RefinedOutput = string;

export type SuperRefinedInput = {
  a: number;
  b: number;
};

export type SuperRefinedOutput = {
  a: number;
  b: number;
};

export type ReadonlyInput = {
  readonly locked: boolean;
};

export type ReadonlyOutput = {
  readonly locked: boolean;
};

export type PromiseInput = string | Promise<string>;

export type PromiseOutput = Promise<string>;

export type ExactOptionalInput = {
  maybe?: string | undefined;
};

export type ExactOptionalOutput = {
  maybe?: string | undefined;
};

export type NonOptionalInput = string;

export type NonOptionalOutput = string;

export type NullishInput = {
  value?: string | null | undefined;
};

export type NullishOutput = {
  value?: string | null | undefined;
};
