// This file is auto-generated by zinfer-mini --generate-tests
// Do not edit manually. Regenerate with: zinfer-mini --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- builders-schema ---
import { BaseSchema as BuildersSchemaBaseSchema, PickedSchema as BuildersSchemaPickedSchema, OmittedSchema as BuildersSchemaOmittedSchema, PartialSchema as BuildersSchemaPartialSchema, RequiredSchema as BuildersSchemaRequiredSchema, ExtendedSchema as BuildersSchemaExtendedSchema, TupleSchema as BuildersSchemaTupleSchema, RecordSchema as BuildersSchemaRecordSchema, MapSchema as BuildersSchemaMapSchema, SetSchema as BuildersSchemaSetSchema, IntersectionSchema as BuildersSchemaIntersectionSchema, LiteralUnionSchema as BuildersSchemaLiteralUnionSchema, TemplateLiteralSchema as BuildersSchemaTemplateLiteralSchema, DefaultedSchema as BuildersSchemaDefaultedSchema, PrefaultedSchema as BuildersSchemaPrefaultedSchema, CaughtSchema as BuildersSchemaCaughtSchema, CustomSchema as BuildersSchemaCustomSchema, RefinedSchema as BuildersSchemaRefinedSchema, SuperRefinedSchema as BuildersSchemaSuperRefinedSchema, ReadonlySchema as BuildersSchemaReadonlySchema, PromiseSchema as BuildersSchemaPromiseSchema, ExactOptionalSchema as BuildersSchemaExactOptionalSchema, NonOptionalSchema as BuildersSchemaNonOptionalSchema, NullishSchema as BuildersSchemaNullishSchema } from "../fixtures/builders-schema";
import type {
  BaseInput as BuildersSchemaBaseInput,
  BaseOutput as BuildersSchemaBaseOutput,
  PickedInput as BuildersSchemaPickedInput,
  PickedOutput as BuildersSchemaPickedOutput,
  OmittedInput as BuildersSchemaOmittedInput,
  OmittedOutput as BuildersSchemaOmittedOutput,
  PartialInput as BuildersSchemaPartialInput,
  PartialOutput as BuildersSchemaPartialOutput,
  RequiredInput as BuildersSchemaRequiredInput,
  RequiredOutput as BuildersSchemaRequiredOutput,
  ExtendedInput as BuildersSchemaExtendedInput,
  ExtendedOutput as BuildersSchemaExtendedOutput,
  TupleInput as BuildersSchemaTupleInput,
  TupleOutput as BuildersSchemaTupleOutput,
  RecordInput as BuildersSchemaRecordInput,
  RecordOutput as BuildersSchemaRecordOutput,
  MapInput as BuildersSchemaMapInput,
  MapOutput as BuildersSchemaMapOutput,
  SetInput as BuildersSchemaSetInput,
  SetOutput as BuildersSchemaSetOutput,
  IntersectionInput as BuildersSchemaIntersectionInput,
  IntersectionOutput as BuildersSchemaIntersectionOutput,
  LiteralUnionInput as BuildersSchemaLiteralUnionInput,
  LiteralUnionOutput as BuildersSchemaLiteralUnionOutput,
  TemplateLiteralInput as BuildersSchemaTemplateLiteralInput,
  TemplateLiteralOutput as BuildersSchemaTemplateLiteralOutput,
  DefaultedInput as BuildersSchemaDefaultedInput,
  DefaultedOutput as BuildersSchemaDefaultedOutput,
  PrefaultedInput as BuildersSchemaPrefaultedInput,
  PrefaultedOutput as BuildersSchemaPrefaultedOutput,
  CaughtInput as BuildersSchemaCaughtInput,
  CaughtOutput as BuildersSchemaCaughtOutput,
  CustomInput as BuildersSchemaCustomInput,
  CustomOutput as BuildersSchemaCustomOutput,
  RefinedInput as BuildersSchemaRefinedInput,
  RefinedOutput as BuildersSchemaRefinedOutput,
  SuperRefinedInput as BuildersSchemaSuperRefinedInput,
  SuperRefinedOutput as BuildersSchemaSuperRefinedOutput,
  ReadonlyInput as BuildersSchemaReadonlyInput,
  ReadonlyOutput as BuildersSchemaReadonlyOutput,
  PromiseInput as BuildersSchemaPromiseInput,
  PromiseOutput as BuildersSchemaPromiseOutput,
  ExactOptionalInput as BuildersSchemaExactOptionalInput,
  ExactOptionalOutput as BuildersSchemaExactOptionalOutput,
  NonOptionalInput as BuildersSchemaNonOptionalInput,
  NonOptionalOutput as BuildersSchemaNonOptionalOutput,
  NullishInput as BuildersSchemaNullishInput,
  NullishOutput as BuildersSchemaNullishOutput,
} from "./builders-schema";

describe("Type equality tests", () => {
  describe("builders-schema", () => {
    it("BaseSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaBaseInput>().toEqualTypeOf<z.input<typeof BuildersSchemaBaseSchema>>();
    });

    it("BaseSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaBaseOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaBaseSchema>>();
    });

    it("PickedSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaPickedInput>().toEqualTypeOf<z.input<typeof BuildersSchemaPickedSchema>>();
    });

    it("PickedSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaPickedOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaPickedSchema>>();
    });

    it("OmittedSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaOmittedInput>().toEqualTypeOf<z.input<typeof BuildersSchemaOmittedSchema>>();
    });

    it("OmittedSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaOmittedOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaOmittedSchema>>();
    });

    it("PartialSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaPartialInput>().toEqualTypeOf<z.input<typeof BuildersSchemaPartialSchema>>();
    });

    it("PartialSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaPartialOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaPartialSchema>>();
    });

    it("RequiredSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaRequiredInput>().toEqualTypeOf<z.input<typeof BuildersSchemaRequiredSchema>>();
    });

    it("RequiredSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaRequiredOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaRequiredSchema>>();
    });

    it("ExtendedSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaExtendedInput>().toEqualTypeOf<z.input<typeof BuildersSchemaExtendedSchema>>();
    });

    it("ExtendedSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaExtendedOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaExtendedSchema>>();
    });

    it("TupleSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaTupleInput>().toEqualTypeOf<z.input<typeof BuildersSchemaTupleSchema>>();
    });

    it("TupleSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaTupleOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaTupleSchema>>();
    });

    it("RecordSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaRecordInput>().toEqualTypeOf<z.input<typeof BuildersSchemaRecordSchema>>();
    });

    it("RecordSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaRecordOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaRecordSchema>>();
    });

    it("MapSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaMapInput>().toEqualTypeOf<z.input<typeof BuildersSchemaMapSchema>>();
    });

    it("MapSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaMapOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaMapSchema>>();
    });

    it("SetSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaSetInput>().toEqualTypeOf<z.input<typeof BuildersSchemaSetSchema>>();
    });

    it("SetSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaSetOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaSetSchema>>();
    });

    it("IntersectionSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaIntersectionInput>().toEqualTypeOf<z.input<typeof BuildersSchemaIntersectionSchema>>();
    });

    it("IntersectionSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaIntersectionOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaIntersectionSchema>>();
    });

    it("LiteralUnionSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaLiteralUnionInput>().toEqualTypeOf<z.input<typeof BuildersSchemaLiteralUnionSchema>>();
    });

    it("LiteralUnionSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaLiteralUnionOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaLiteralUnionSchema>>();
    });

    it("TemplateLiteralSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaTemplateLiteralInput>().toEqualTypeOf<z.input<typeof BuildersSchemaTemplateLiteralSchema>>();
    });

    it("TemplateLiteralSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaTemplateLiteralOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaTemplateLiteralSchema>>();
    });

    it("DefaultedSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaDefaultedInput>().toEqualTypeOf<z.input<typeof BuildersSchemaDefaultedSchema>>();
    });

    it("DefaultedSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaDefaultedOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaDefaultedSchema>>();
    });

    it("PrefaultedSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaPrefaultedInput>().toEqualTypeOf<z.input<typeof BuildersSchemaPrefaultedSchema>>();
    });

    it("PrefaultedSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaPrefaultedOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaPrefaultedSchema>>();
    });

    it("CaughtSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaCaughtInput>().toEqualTypeOf<z.input<typeof BuildersSchemaCaughtSchema>>();
    });

    it("CaughtSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaCaughtOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaCaughtSchema>>();
    });

    it("CustomSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaCustomInput>().toEqualTypeOf<z.input<typeof BuildersSchemaCustomSchema>>();
    });

    it("CustomSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaCustomOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaCustomSchema>>();
    });

    it("RefinedSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaRefinedInput>().toEqualTypeOf<z.input<typeof BuildersSchemaRefinedSchema>>();
    });

    it("RefinedSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaRefinedOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaRefinedSchema>>();
    });

    it("SuperRefinedSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaSuperRefinedInput>().toEqualTypeOf<z.input<typeof BuildersSchemaSuperRefinedSchema>>();
    });

    it("SuperRefinedSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaSuperRefinedOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaSuperRefinedSchema>>();
    });

    it("ReadonlySchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaReadonlyInput>().toEqualTypeOf<z.input<typeof BuildersSchemaReadonlySchema>>();
    });

    it("ReadonlySchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaReadonlyOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaReadonlySchema>>();
    });

    it("PromiseSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaPromiseInput>().toEqualTypeOf<z.input<typeof BuildersSchemaPromiseSchema>>();
    });

    it("PromiseSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaPromiseOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaPromiseSchema>>();
    });

    it("ExactOptionalSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaExactOptionalInput>().toEqualTypeOf<z.input<typeof BuildersSchemaExactOptionalSchema>>();
    });

    it("ExactOptionalSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaExactOptionalOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaExactOptionalSchema>>();
    });

    it("NonOptionalSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaNonOptionalInput>().toEqualTypeOf<z.input<typeof BuildersSchemaNonOptionalSchema>>();
    });

    it("NonOptionalSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaNonOptionalOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaNonOptionalSchema>>();
    });

    it("NullishSchema input matches z.input", () => {
      expectTypeOf<BuildersSchemaNullishInput>().toEqualTypeOf<z.input<typeof BuildersSchemaNullishSchema>>();
    });

    it("NullishSchema output matches z.output", () => {
      expectTypeOf<BuildersSchemaNullishOutput>().toEqualTypeOf<z.output<typeof BuildersSchemaNullishSchema>>();
    });
  });
});
