// This file is auto-generated by zinfer-mini --generate-tests
// Do not edit manually. Regenerate with: zinfer-mini --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- cross-ref-schema ---
import { AddressSchema as CrossRefSchemaAddressSchema, UserSchema as CrossRefSchemaUserSchema, CatSchema as CrossRefSchemaCatSchema, DogSchema as CrossRefSchemaDogSchema, PetSchema as CrossRefSchemaPetSchema, TreeSchema as CrossRefSchemaTreeSchema, UserIdSchema as CrossRefSchemaUserIdSchema } from "../fixtures/cross-ref-schema";
import type {
  AddressInput as CrossRefSchemaAddressInput,
  AddressOutput as CrossRefSchemaAddressOutput,
  UserInput as CrossRefSchemaUserInput,
  UserOutput as CrossRefSchemaUserOutput,
  CatInput as CrossRefSchemaCatInput,
  CatOutput as CrossRefSchemaCatOutput,
  DogInput as CrossRefSchemaDogInput,
  DogOutput as CrossRefSchemaDogOutput,
  PetInput as CrossRefSchemaPetInput,
  PetOutput as CrossRefSchemaPetOutput,
  TreeInput as CrossRefSchemaTreeInput,
  TreeOutput as CrossRefSchemaTreeOutput,
  UserIdInput as CrossRefSchemaUserIdInput,
  UserIdOutput as CrossRefSchemaUserIdOutput,
} from "./cross-ref-schema";

describe("Type equality tests", () => {
  describe("cross-ref-schema", () => {
    it("AddressSchema input matches z.input", () => {
      expectTypeOf<CrossRefSchemaAddressInput>().toEqualTypeOf<z.input<typeof CrossRefSchemaAddressSchema>>();
    });

    it("AddressSchema output matches z.output", () => {
      expectTypeOf<CrossRefSchemaAddressOutput>().toEqualTypeOf<z.output<typeof CrossRefSchemaAddressSchema>>();
    });

    it("UserSchema input matches z.input", () => {
      expectTypeOf<CrossRefSchemaUserInput>().toEqualTypeOf<z.input<typeof CrossRefSchemaUserSchema>>();
    });

    it("UserSchema output matches z.output", () => {
      expectTypeOf<CrossRefSchemaUserOutput>().toEqualTypeOf<z.output<typeof CrossRefSchemaUserSchema>>();
    });

    it("CatSchema input matches z.input", () => {
      expectTypeOf<CrossRefSchemaCatInput>().toEqualTypeOf<z.input<typeof CrossRefSchemaCatSchema>>();
    });

    it("CatSchema output matches z.output", () => {
      expectTypeOf<CrossRefSchemaCatOutput>().toEqualTypeOf<z.output<typeof CrossRefSchemaCatSchema>>();
    });

    it("DogSchema input matches z.input", () => {
      expectTypeOf<CrossRefSchemaDogInput>().toEqualTypeOf<z.input<typeof CrossRefSchemaDogSchema>>();
    });

    it("DogSchema output matches z.output", () => {
      expectTypeOf<CrossRefSchemaDogOutput>().toEqualTypeOf<z.output<typeof CrossRefSchemaDogSchema>>();
    });

    it("PetSchema input matches z.input", () => {
      expectTypeOf<CrossRefSchemaPetInput>().toEqualTypeOf<z.input<typeof CrossRefSchemaPetSchema>>();
    });

    it("PetSchema output matches z.output", () => {
      expectTypeOf<CrossRefSchemaPetOutput>().toEqualTypeOf<z.output<typeof CrossRefSchemaPetSchema>>();
    });

    it("TreeSchema input matches z.input", () => {
      expectTypeOf<CrossRefSchemaTreeInput>().toEqualTypeOf<z.input<typeof CrossRefSchemaTreeSchema>>();
    });

    it("TreeSchema output matches z.output", () => {
      expectTypeOf<CrossRefSchemaTreeOutput>().toEqualTypeOf<z.output<typeof CrossRefSchemaTreeSchema>>();
    });

    it("UserIdSchema input matches z.input", () => {
      expectTypeOf<CrossRefSchemaUserIdInput>().toEqualTypeOf<z.input<typeof CrossRefSchemaUserIdSchema>>();
    });

    it("UserIdSchema output matches z.output", () => {
      expectTypeOf<CrossRefSchemaUserIdOutput>().toEqualTypeOf<z.output<typeof CrossRefSchemaUserIdSchema>>();
    });
  });
});
