// Generated by zinfer - Do not edit manually

import type { BRAND } from "zod";

export type AddressInput = {
  city: string;
  zip: string;
};

export type AddressOutput = {
  city: string;
  zip: string;
};

export type UserInput = {
  id: string;
  address: AddressInput;
  previousAddresses: AddressInput[];
  billingAddress?: AddressInput;
};

export type UserOutput = {
  id: string;
  address: AddressOutput;
  previousAddresses: AddressOutput[];
  billingAddress?: AddressOutput;
};

export type CatInput = {
  kind: "cat";
  meow: boolean;
};

export type CatOutput = {
  kind: "cat";
  meow: boolean;
};

export type DogInput = {
  kind: "dog";
  bark: boolean;
};

export type DogOutput = {
  kind: "dog";
  bark: boolean;
};

export type PetInput = CatInput | DogInput;

export type PetOutput = CatOutput | DogOutput;

export type TreeInput = import("../fixtures/cross-ref-schema").TreeNode;

export type TreeOutput = import("../fixtures/cross-ref-schema").TreeNode;

export type UserIdInput = string;

export type UserIdOutput = string & BRAND<"UserId">;
