// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- described-schema ---
import { UserSchema as DescribedSchemaUserSchema } from "../fixtures/described-schema";
import type { UserInput as DescribedSchemaUserInput, UserOutput as DescribedSchemaUserOutput } from "./described-schema";

describe("Type equality tests", () => {
  describe("described-schema", () => {
    it("UserSchema input matches z.input", () => {
      expectTypeOf<DescribedSchemaUserInput>().toEqualTypeOf<z.input<typeof DescribedSchemaUserSchema>>();
    });

    it("UserSchema output matches z.output", () => {
      expectTypeOf<DescribedSchemaUserOutput>().toEqualTypeOf<z.output<typeof DescribedSchemaUserSchema>>();
    });
  });
});
