// This file is auto-generated by zinfer-mini --generate-tests
// Do not edit manually. Regenerate with: zinfer-mini --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- explicit-function-type-schema ---
import { CallbackSchema as ExplicitFunctionTypeSchemaCallbackSchema } from "../fixtures/explicit-function-type-schema";
import type { CallbackInput as ExplicitFunctionTypeSchemaCallbackInput, CallbackOutput as ExplicitFunctionTypeSchemaCallbackOutput } from "./explicit-function-type-schema";

describe("Type equality tests", () => {
  describe("explicit-function-type-schema", () => {
    it("CallbackSchema input matches z.input", () => {
      expectTypeOf<ExplicitFunctionTypeSchemaCallbackInput>().toEqualTypeOf<z.input<typeof ExplicitFunctionTypeSchemaCallbackSchema>>();
    });

    it("CallbackSchema output matches z.output", () => {
      expectTypeOf<ExplicitFunctionTypeSchemaCallbackOutput>().toEqualTypeOf<z.output<typeof ExplicitFunctionTypeSchemaCallbackSchema>>();
    });
  });
});
