// Generated by zinfer-mini - Do not edit manually

export type CallbackInput = (value: string) => number;

export type CallbackOutput = (value: string) => number;

export type CallbackListInput = unknown[];

export type CallbackListOutput = ((value: string) => number)[];
