// Generated by zinfer-mini - Do not edit manually

export type CategoryInput = import("../fixtures/getter-schema").Category;

export type CategoryOutput = import("../fixtures/getter-schema").Category;
