// This file is auto-generated by zinfer-mini --generate-tests
// Do not edit manually. Regenerate with: zinfer-mini --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- getter-schema ---
import { CategorySchema as GetterSchemaCategorySchema } from "../fixtures/getter-schema";
import type { CategoryInput as GetterSchemaCategoryInput, CategoryOutput as GetterSchemaCategoryOutput } from "./getter-schema";

describe("Type equality tests", () => {
  describe("getter-schema", () => {
    it("CategorySchema input matches z.input", () => {
      expectTypeOf<GetterSchemaCategoryInput>().toEqualTypeOf<z.input<typeof GetterSchemaCategorySchema>>();
    });

    it("CategorySchema output matches z.output", () => {
      expectTypeOf<GetterSchemaCategoryOutput>().toEqualTypeOf<z.output<typeof GetterSchemaCategorySchema>>();
    });
  });
});
