// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- lazy-schema ---
import { CategorySchema as LazySchemaCategorySchema } from "../fixtures/lazy-schema";
import type { CategoryInput as LazySchemaCategoryInput, CategoryOutput as LazySchemaCategoryOutput } from "./lazy-schema";

describe("Type equality tests", () => {
  describe("lazy-schema", () => {
    it("CategorySchema input matches z.input", () => {
      expectTypeOf<LazySchemaCategoryInput>().toEqualTypeOf<z.input<typeof LazySchemaCategorySchema>>();
    });

    it("CategorySchema output matches z.output", () => {
      expectTypeOf<LazySchemaCategoryOutput>().toEqualTypeOf<z.output<typeof LazySchemaCategorySchema>>();
    });
  });
});
