// This file is auto-generated by zinfer --generate-tests
// Do not edit manually. Regenerate with: zinfer --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- named-import-schema ---
import { ProductSchema as NamedImportSchemaProductSchema, ProductSummarySchema as NamedImportSchemaProductSummarySchema } from "../fixtures/named-import-schema";
import type {
  ProductInput as NamedImportSchemaProductInput,
  ProductOutput as NamedImportSchemaProductOutput,
  ProductSummaryInput as NamedImportSchemaProductSummaryInput,
  ProductSummaryOutput as NamedImportSchemaProductSummaryOutput,
} from "./named-import-schema";

describe("Type equality tests", () => {
  describe("named-import-schema", () => {
    it("ProductSchema input matches z.input", () => {
      expectTypeOf<NamedImportSchemaProductInput>().toEqualTypeOf<z.input<typeof NamedImportSchemaProductSchema>>();
    });

    it("ProductSchema output matches z.output", () => {
      expectTypeOf<NamedImportSchemaProductOutput>().toEqualTypeOf<z.output<typeof NamedImportSchemaProductSchema>>();
    });

    it("ProductSummarySchema input matches z.input", () => {
      expectTypeOf<NamedImportSchemaProductSummaryInput>().toEqualTypeOf<z.input<typeof NamedImportSchemaProductSummarySchema>>();
    });

    it("ProductSummarySchema output matches z.output", () => {
      expectTypeOf<NamedImportSchemaProductSummaryOutput>().toEqualTypeOf<z.output<typeof NamedImportSchemaProductSummarySchema>>();
    });
  });
});
