// Generated by zinfer - Do not edit manually

export type ProductInput = {
  id: string;
  title: string;
  price: number;
  description?: string | undefined;
};

export type ProductOutput = {
  id: string;
  title: string;
  price: number;
  description?: string | undefined;
};

export type ProductSummaryInput = {
  id: string;
  title: string;
};

export type ProductSummaryOutput = {
  id: string;
  title: string;
};
