// Generated by zinfer-mini - Do not edit manually

export type OtherInput = {
  x: string;
};

export type OtherOutput = {
  x: string;
};

export type NestedObjectReferenceInput = {
  bar: {
    x: string;
  };
  wrapper: {
    bar: {
      x: string;
    };
  };
};

export type NestedObjectReferenceOutput = {
  bar: {
    x: string;
  };
  wrapper: {
    bar: {
      x: string;
    };
  };
};
