// Generated by zinfer-mini - Do not edit manually

type LocalRecursiveInput = {
  label: string;
  kids: {
    [x: string]: LocalRecursiveInput;
  };
};

type LocalRecursiveOutput = {
  label: string;
  kids: {
    [x: string]: LocalRecursiveOutput;
  };
};

export type NonexportedRecursiveContainerInput = {
  localRecursive: LocalRecursiveInput;
};

export type NonexportedRecursiveContainerOutput = {
  localRecursive: LocalRecursiveOutput;
};
