// Generated by zinfer-mini - Do not edit manually

export type NonexportedRecursiveContainerInput = {
  localRecursive: {
    label: string;
    kids: {
      [x: string]: any;
    };
  };
};

export type NonexportedRecursiveContainerOutput = {
  localRecursive: {
    label: string;
    kids: {
      [x: string]: any;
    };
  };
};
