// This file is auto-generated by zinfer-mini --generate-tests
// Do not edit manually. Regenerate with: zinfer-mini --generate-tests [schema-files] --types-dir [types-dir] --out [output]

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

// --- standalone-mini-package-schema ---
import { UserSchema as StandaloneMiniPackageSchemaUserSchema } from "../fixtures/standalone-mini-package-schema";
import type { UserInput as StandaloneMiniPackageSchemaUserInput, UserOutput as StandaloneMiniPackageSchemaUserOutput } from "./standalone-mini-package-schema";

describe("Type equality tests", () => {
  describe("standalone-mini-package-schema", () => {
    it("UserSchema input matches z.input", () => {
      expectTypeOf<StandaloneMiniPackageSchemaUserInput>().toEqualTypeOf<z.input<typeof StandaloneMiniPackageSchemaUserSchema>>();
    });

    it("UserSchema output matches z.output", () => {
      expectTypeOf<StandaloneMiniPackageSchemaUserOutput>().toEqualTypeOf<z.output<typeof StandaloneMiniPackageSchemaUserSchema>>();
    });
  });
});
