name: Preview

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          standalone: true
          run_install: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        name: Install Node.js
        with:
          node-version: 24.20.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm -r build
      - name: Publish preview
        run: pnpm dlx pkg-pr-new publish ./packages/zinfer ./packages/vinfer ./packages/zinfer-mini
